// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package auth

type CreateSecretResponse struct {
	SecretOptions *SecretOptions1 `json:"data,omitempty"`
}

func (c *CreateSecretResponse) GetSecretOptions() *SecretOptions1 {
	if c == nil {
		return nil
	}
	return c.SecretOptions
}
