// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3aea21e4e7ca

package auth

type ListUsersResponse struct {
	Data []User `json:"data,omitempty"`
}

func (l *ListUsersResponse) GetData() []User {
	if l == nil {
		return nil
	}
	return l.Data
}
