// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package auth

type SecretOptions struct {
	Metadata map[string]string `json:"metadata,omitempty"`
	Name     string            `json:"name"`
}

func (s *SecretOptions) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SecretOptions) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}
