// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package v3

import (
	"github.com/formancehq/formance-sdk-go/v3/internal/config"
	"github.com/formancehq/formance-sdk-go/v3/internal/hooks"
)

type Auth struct {
	V1 *V1

	rootSDK          *Formance
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newAuth(rootSDK *Formance, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Auth {
	return &Auth{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		V1:               newV1(rootSDK, sdkConfig, hooks),
	}
}
