/*
Formance Stack API

Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 

API version: develop
Contact: support@formance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package formance

import (
	"encoding/json"
)

// checks if the BalanceWithAssetsAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalanceWithAssetsAllOf{}

// BalanceWithAssetsAllOf struct for BalanceWithAssetsAllOf
type BalanceWithAssetsAllOf struct {
	Assets map[string]float32 `json:"assets"`
}

// NewBalanceWithAssetsAllOf instantiates a new BalanceWithAssetsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceWithAssetsAllOf(assets map[string]float32) *BalanceWithAssetsAllOf {
	this := BalanceWithAssetsAllOf{}
	this.Assets = assets
	return &this
}

// NewBalanceWithAssetsAllOfWithDefaults instantiates a new BalanceWithAssetsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceWithAssetsAllOfWithDefaults() *BalanceWithAssetsAllOf {
	this := BalanceWithAssetsAllOf{}
	return &this
}

// GetAssets returns the Assets field value
func (o *BalanceWithAssetsAllOf) GetAssets() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *BalanceWithAssetsAllOf) GetAssetsOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Assets, true
}

// SetAssets sets field value
func (o *BalanceWithAssetsAllOf) SetAssets(v map[string]float32) {
	o.Assets = v
}

func (o BalanceWithAssetsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceWithAssetsAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assets"] = o.Assets
	return toSerialize, nil
}

type NullableBalanceWithAssetsAllOf struct {
	value *BalanceWithAssetsAllOf
	isSet bool
}

func (v NullableBalanceWithAssetsAllOf) Get() *BalanceWithAssetsAllOf {
	return v.value
}

func (v *NullableBalanceWithAssetsAllOf) Set(val *BalanceWithAssetsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceWithAssetsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceWithAssetsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceWithAssetsAllOf(val *BalanceWithAssetsAllOf) *NullableBalanceWithAssetsAllOf {
	return &NullableBalanceWithAssetsAllOf{value: val, isSet: true}
}

func (v NullableBalanceWithAssetsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceWithAssetsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


