/*
Formance Stack API

Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 

API version: v1.0.0-rc.1
Contact: support@formance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package formance

import (
	"encoding/json"
)

// checks if the TaskDescriptorBankingCircleAllOfDescriptor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskDescriptorBankingCircleAllOfDescriptor{}

// TaskDescriptorBankingCircleAllOfDescriptor struct for TaskDescriptorBankingCircleAllOfDescriptor
type TaskDescriptorBankingCircleAllOfDescriptor struct {
	Name *string `json:"name,omitempty"`
	Key *string `json:"key,omitempty"`
}

// NewTaskDescriptorBankingCircleAllOfDescriptor instantiates a new TaskDescriptorBankingCircleAllOfDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskDescriptorBankingCircleAllOfDescriptor() *TaskDescriptorBankingCircleAllOfDescriptor {
	this := TaskDescriptorBankingCircleAllOfDescriptor{}
	return &this
}

// NewTaskDescriptorBankingCircleAllOfDescriptorWithDefaults instantiates a new TaskDescriptorBankingCircleAllOfDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskDescriptorBankingCircleAllOfDescriptorWithDefaults() *TaskDescriptorBankingCircleAllOfDescriptor {
	this := TaskDescriptorBankingCircleAllOfDescriptor{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) SetName(v string) {
	o.Name = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) GetKey() string {
	if o == nil || isNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) GetKeyOk() (*string, bool) {
	if o == nil || isNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) HasKey() bool {
	if o != nil && !isNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TaskDescriptorBankingCircleAllOfDescriptor) SetKey(v string) {
	o.Key = &v
}

func (o TaskDescriptorBankingCircleAllOfDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskDescriptorBankingCircleAllOfDescriptor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return toSerialize, nil
}

type NullableTaskDescriptorBankingCircleAllOfDescriptor struct {
	value *TaskDescriptorBankingCircleAllOfDescriptor
	isSet bool
}

func (v NullableTaskDescriptorBankingCircleAllOfDescriptor) Get() *TaskDescriptorBankingCircleAllOfDescriptor {
	return v.value
}

func (v *NullableTaskDescriptorBankingCircleAllOfDescriptor) Set(val *TaskDescriptorBankingCircleAllOfDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskDescriptorBankingCircleAllOfDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskDescriptorBankingCircleAllOfDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskDescriptorBankingCircleAllOfDescriptor(val *TaskDescriptorBankingCircleAllOfDescriptor) *NullableTaskDescriptorBankingCircleAllOfDescriptor {
	return &NullableTaskDescriptorBankingCircleAllOfDescriptor{value: val, isSet: true}
}

func (v NullableTaskDescriptorBankingCircleAllOfDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskDescriptorBankingCircleAllOfDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


