/*
Formance Stack API

Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 

API version: v1.0.0-rc.1
Contact: support@formance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package formance

import (
	"encoding/json"
)

// checks if the TaskDescriptorStripeAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskDescriptorStripeAllOf{}

// TaskDescriptorStripeAllOf struct for TaskDescriptorStripeAllOf
type TaskDescriptorStripeAllOf struct {
	Descriptor *TaskDescriptorStripeAllOfDescriptor `json:"descriptor,omitempty"`
}

// NewTaskDescriptorStripeAllOf instantiates a new TaskDescriptorStripeAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskDescriptorStripeAllOf() *TaskDescriptorStripeAllOf {
	this := TaskDescriptorStripeAllOf{}
	return &this
}

// NewTaskDescriptorStripeAllOfWithDefaults instantiates a new TaskDescriptorStripeAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskDescriptorStripeAllOfWithDefaults() *TaskDescriptorStripeAllOf {
	this := TaskDescriptorStripeAllOf{}
	return &this
}

// GetDescriptor returns the Descriptor field value if set, zero value otherwise.
func (o *TaskDescriptorStripeAllOf) GetDescriptor() TaskDescriptorStripeAllOfDescriptor {
	if o == nil || isNil(o.Descriptor) {
		var ret TaskDescriptorStripeAllOfDescriptor
		return ret
	}
	return *o.Descriptor
}

// GetDescriptorOk returns a tuple with the Descriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskDescriptorStripeAllOf) GetDescriptorOk() (*TaskDescriptorStripeAllOfDescriptor, bool) {
	if o == nil || isNil(o.Descriptor) {
		return nil, false
	}
	return o.Descriptor, true
}

// HasDescriptor returns a boolean if a field has been set.
func (o *TaskDescriptorStripeAllOf) HasDescriptor() bool {
	if o != nil && !isNil(o.Descriptor) {
		return true
	}

	return false
}

// SetDescriptor gets a reference to the given TaskDescriptorStripeAllOfDescriptor and assigns it to the Descriptor field.
func (o *TaskDescriptorStripeAllOf) SetDescriptor(v TaskDescriptorStripeAllOfDescriptor) {
	o.Descriptor = &v
}

func (o TaskDescriptorStripeAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskDescriptorStripeAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Descriptor) {
		toSerialize["descriptor"] = o.Descriptor
	}
	return toSerialize, nil
}

type NullableTaskDescriptorStripeAllOf struct {
	value *TaskDescriptorStripeAllOf
	isSet bool
}

func (v NullableTaskDescriptorStripeAllOf) Get() *TaskDescriptorStripeAllOf {
	return v.value
}

func (v *NullableTaskDescriptorStripeAllOf) Set(val *TaskDescriptorStripeAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskDescriptorStripeAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskDescriptorStripeAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskDescriptorStripeAllOf(val *TaskDescriptorStripeAllOf) *NullableTaskDescriptorStripeAllOf {
	return &NullableTaskDescriptorStripeAllOf{value: val, isSet: true}
}

func (v NullableTaskDescriptorStripeAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskDescriptorStripeAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


