// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package v3

import (
	"github.com/formancehq/formance-sdk-go/v3/internal/config"
	"github.com/formancehq/formance-sdk-go/v3/internal/hooks"
)

// Search - search.v1
// Elasticsearch.v1 query engine
type Search struct {
	V1 *FormanceSearchV1

	rootSDK          *Formance
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newSearch(rootSDK *Formance, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Search {
	return &Search{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		V1:               newFormanceSearchV1(rootSDK, sdkConfig, hooks),
	}
}
