// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package formancesdkgo

import (
	"github.com/formancehq/formance-sdk-go/v3/internal/config"
	"github.com/formancehq/formance-sdk-go/v3/internal/hooks"
)

type Webhooks struct {
	V1 *FormanceWebhooksV1

	rootSDK          *Formance
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newWebhooks(rootSDK *Formance, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Webhooks {
	return &Webhooks{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		V1:               newFormanceWebhooksV1(rootSDK, sdkConfig, hooks),
	}
}
