// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fb1b58b0e24d

package search

type ServerInfo struct {
	Version string `json:"version"`
}

func (s *ServerInfo) GetVersion() string {
	if s == nil {
		return ""
	}
	return s.Version
}
