// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type ActivateConfigRequest struct {
	// Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (a *ActivateConfigRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

type ActivateConfigResponse struct {
	// Config successfully activated.
	ConfigResponse *shared.ConfigResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (a *ActivateConfigResponse) GetConfigResponse() *shared.ConfigResponse {
	if a == nil {
		return nil
	}
	return a.ConfigResponse
}

func (a *ActivateConfigResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *ActivateConfigResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *ActivateConfigResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}
