// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"net/http"
)

type AddMetadataOnTransactionRequest struct {
	// metadata
	RequestBody map[string]any `request:"mediaType=application/json"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// Transaction ID.
	Txid *big.Int `pathParam:"style=simple,explode=false,name=txid"`
}

func (a AddMetadataOnTransactionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddMetadataOnTransactionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"ledger", "txid"}); err != nil {
		return err
	}
	return nil
}

func (a *AddMetadataOnTransactionRequest) GetRequestBody() map[string]any {
	if a == nil {
		return nil
	}
	return a.RequestBody
}

func (a *AddMetadataOnTransactionRequest) GetLedger() string {
	if a == nil {
		return ""
	}
	return a.Ledger
}

func (a *AddMetadataOnTransactionRequest) GetTxid() *big.Int {
	if a == nil {
		return big.NewInt(0)
	}
	return a.Txid
}

type AddMetadataOnTransactionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (a *AddMetadataOnTransactionResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AddMetadataOnTransactionResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AddMetadataOnTransactionResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}
