// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type ConnectorsTransferRequest struct {
	TransferRequest shared.TransferRequest `request:"mediaType=application/json"`
	// The name of the connector.
	Connector shared.Connector `pathParam:"style=simple,explode=false,name=connector"`
}

func (c *ConnectorsTransferRequest) GetTransferRequest() shared.TransferRequest {
	if c == nil {
		return shared.TransferRequest{}
	}
	return c.TransferRequest
}

func (c *ConnectorsTransferRequest) GetConnector() shared.Connector {
	if c == nil {
		return shared.Connector("")
	}
	return c.Connector
}

type ConnectorsTransferResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TransferResponse *shared.TransferResponse
}

func (c *ConnectorsTransferResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ConnectorsTransferResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ConnectorsTransferResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ConnectorsTransferResponse) GetTransferResponse() *shared.TransferResponse {
	if c == nil {
		return nil
	}
	return c.TransferResponse
}
