// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/auth"
	"net/http"
)

var CreateSecretServerList = []string{
	"http://localhost:8080/",
}

type CreateSecretRequest struct {
	SecretOptions *auth.SecretOptions `request:"mediaType=application/json"`
	// Client ID
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (c *CreateSecretRequest) GetSecretOptions() *auth.SecretOptions {
	if c == nil {
		return nil
	}
	return c.SecretOptions
}

func (c *CreateSecretRequest) GetClientID() string {
	if c == nil {
		return ""
	}
	return c.ClientID
}

type CreateSecretResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Created secret
	CreateSecretResponse *auth.CreateSecretResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateSecretResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateSecretResponse) GetCreateSecretResponse() *auth.CreateSecretResponse {
	if c == nil {
		return nil
	}
	return c.CreateSecretResponse
}

func (c *CreateSecretResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateSecretResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
