// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type CreditWalletRequest struct {
	CreditWalletRequest *shared.CreditWalletRequest `request:"mediaType=application/json"`
	// Use an idempotency key
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
	ID             string  `pathParam:"style=simple,explode=false,name=id"`
}

func (c *CreditWalletRequest) GetCreditWalletRequest() *shared.CreditWalletRequest {
	if c == nil {
		return nil
	}
	return c.CreditWalletRequest
}

func (c *CreditWalletRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreditWalletRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CreditWalletResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreditWalletResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreditWalletResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreditWalletResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
