// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetBankAccountRequest struct {
	// The bank account ID.
	BankAccountID string `pathParam:"style=simple,explode=false,name=bankAccountId"`
}

func (g *GetBankAccountRequest) GetBankAccountID() string {
	if g == nil {
		return ""
	}
	return g.BankAccountID
}

type GetBankAccountResponse struct {
	// OK
	BankAccountResponse *shared.BankAccountResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetBankAccountResponse) GetBankAccountResponse() *shared.BankAccountResponse {
	if g == nil {
		return nil
	}
	return g.BankAccountResponse
}

func (g *GetBankAccountResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetBankAccountResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetBankAccountResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
