// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/models/webhooks"
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"net/http"
)

type GetDeliveryAttemptsRequest struct {
	Cursor   *string `queryParam:"style=form,explode=true,name=cursor"`
	ID       string  `pathParam:"style=simple,explode=false,name=id"`
	PageSize *int64  `default:"100" queryParam:"style=form,explode=true,name=pageSize"`
}

func (g GetDeliveryAttemptsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDeliveryAttemptsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetDeliveryAttemptsRequest) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetDeliveryAttemptsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetDeliveryAttemptsRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

type GetDeliveryAttemptsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Paginated append-only attempt history.
	DeliveryAttemptsResponse *webhooks.DeliveryAttemptsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetDeliveryAttemptsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDeliveryAttemptsResponse) GetDeliveryAttemptsResponse() *webhooks.DeliveryAttemptsResponse {
	if g == nil {
		return nil
	}
	return g.DeliveryAttemptsResponse
}

func (g *GetDeliveryAttemptsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDeliveryAttemptsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
