// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetInstanceRequest struct {
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
}

func (g *GetInstanceRequest) GetInstanceID() string {
	if g == nil {
		return ""
	}
	return g.InstanceID
}

type GetInstanceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The workflow instance
	GetWorkflowInstanceResponse *shared.GetWorkflowInstanceResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetInstanceResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetInstanceResponse) GetGetWorkflowInstanceResponse() *shared.GetWorkflowInstanceResponse {
	if g == nil {
		return nil
	}
	return g.GetWorkflowInstanceResponse
}

func (g *GetInstanceResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetInstanceResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
