// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetReconciliationRequest struct {
	// The reconciliation ID.
	ReconciliationID string `pathParam:"style=simple,explode=false,name=reconciliationID"`
}

func (g *GetReconciliationRequest) GetReconciliationID() string {
	if g == nil {
		return ""
	}
	return g.ReconciliationID
}

type GetReconciliationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ReconciliationResponse *shared.ReconciliationResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetReconciliationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetReconciliationResponse) GetReconciliationResponse() *shared.ReconciliationResponse {
	if g == nil {
		return nil
	}
	return g.ReconciliationResponse
}

func (g *GetReconciliationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetReconciliationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
