// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type InstallConnectorRequest struct {
	ConnectorConfig shared.ConnectorConfig `request:"mediaType=application/json"`
	// The name of the connector.
	Connector shared.Connector `pathParam:"style=simple,explode=false,name=connector"`
}

func (o *InstallConnectorRequest) GetConnectorConfig() shared.ConnectorConfig {
	if o == nil {
		return shared.ConnectorConfig{}
	}
	return o.ConnectorConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigAdyen() *shared.AdyenConfig {
	return o.GetConnectorConfig().AdyenConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigAtlar() *shared.AtlarConfig {
	return o.GetConnectorConfig().AtlarConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigBankingcircle() *shared.BankingCircleConfig {
	return o.GetConnectorConfig().BankingCircleConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigCurrencycloud() *shared.CurrencyCloudConfig {
	return o.GetConnectorConfig().CurrencyCloudConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigDummypay() *shared.DummyPayConfig {
	return o.GetConnectorConfig().DummyPayConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigGeneric() *shared.GenericConfig {
	return o.GetConnectorConfig().GenericConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigMangopay() *shared.MangoPayConfig {
	return o.GetConnectorConfig().MangoPayConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigModulr() *shared.ModulrConfig {
	return o.GetConnectorConfig().ModulrConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigMoneycorp() *shared.MoneycorpConfig {
	return o.GetConnectorConfig().MoneycorpConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigStripe() *shared.StripeConfig {
	return o.GetConnectorConfig().StripeConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigWise() *shared.WiseConfig {
	return o.GetConnectorConfig().WiseConfig
}

func (o *InstallConnectorRequest) GetConnector() shared.Connector {
	if o == nil {
		return shared.Connector("")
	}
	return o.Connector
}

type InstallConnectorResponse struct {
	// OK
	ConnectorResponse *shared.ConnectorResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *InstallConnectorResponse) GetConnectorResponse() *shared.ConnectorResponse {
	if o == nil {
		return nil
	}
	return o.ConnectorResponse
}

func (o *InstallConnectorResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *InstallConnectorResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *InstallConnectorResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
