// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/models/payments"
	"net/http"
)

type InstallConnectorRequest struct {
	ConnectorConfig payments.ConnectorConfig `request:"mediaType=application/json"`
	// The name of the connector.
	Connector payments.Connector `pathParam:"style=simple,explode=false,name=connector"`
}

func (i *InstallConnectorRequest) GetConnectorConfig() payments.ConnectorConfig {
	if i == nil {
		return payments.ConnectorConfig{}
	}
	return i.ConnectorConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigAdyen() *payments.AdyenConfig {
	return i.GetConnectorConfig().AdyenConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigAtlar() *payments.AtlarConfig {
	return i.GetConnectorConfig().AtlarConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigBankingcircle() *payments.BankingCircleConfig {
	return i.GetConnectorConfig().BankingCircleConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigCurrencycloud() *payments.CurrencyCloudConfig {
	return i.GetConnectorConfig().CurrencyCloudConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigDummypay() *payments.DummyPayConfig {
	return i.GetConnectorConfig().DummyPayConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigGeneric() *payments.GenericConfig {
	return i.GetConnectorConfig().GenericConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigMangopay() *payments.MangoPayConfig {
	return i.GetConnectorConfig().MangoPayConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigModulr() *payments.ModulrConfig {
	return i.GetConnectorConfig().ModulrConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigMoneycorp() *payments.MoneycorpConfig {
	return i.GetConnectorConfig().MoneycorpConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigStripe() *payments.StripeConfig {
	return i.GetConnectorConfig().StripeConfig
}

func (i *InstallConnectorRequest) GetConnectorConfigWise() *payments.WiseConfig {
	return i.GetConnectorConfig().WiseConfig
}

func (i *InstallConnectorRequest) GetConnector() payments.Connector {
	if i == nil {
		return payments.Connector("")
	}
	return i.Connector
}

type InstallConnectorResponse struct {
	// OK
	ConnectorResponse *payments.ConnectorResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (i *InstallConnectorResponse) GetConnectorResponse() *payments.ConnectorResponse {
	if i == nil {
		return nil
	}
	return i.ConnectorResponse
}

func (i *InstallConnectorResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *InstallConnectorResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *InstallConnectorResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}
