// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type ListBalancesRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (l *ListBalancesRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

type ListBalancesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Balances list
	ListBalancesResponse *shared.ListBalancesResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListBalancesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListBalancesResponse) GetListBalancesResponse() *shared.ListBalancesResponse {
	if l == nil {
		return nil
	}
	return l.ListBalancesResponse
}

func (l *ListBalancesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListBalancesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
