// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"net/http"
)

type PaymentslistAccountsRequest struct {
	RequestBody map[string]any `request:"mediaType=application/json"`
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of results to return per page.
	//
	PageSize *int64 `default:"15" queryParam:"style=form,explode=true,name=pageSize"`
	// Filters used to filter resources.
	//
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Fields used to sort payments (default is date:desc).
	Sort []string `queryParam:"style=form,explode=true,name=sort"`
}

func (p PaymentslistAccountsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentslistAccountsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentslistAccountsRequest) GetRequestBody() map[string]any {
	if p == nil {
		return nil
	}
	return p.RequestBody
}

func (p *PaymentslistAccountsRequest) GetCursor() *string {
	if p == nil {
		return nil
	}
	return p.Cursor
}

func (p *PaymentslistAccountsRequest) GetPageSize() *int64 {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PaymentslistAccountsRequest) GetQuery() *string {
	if p == nil {
		return nil
	}
	return p.Query
}

func (p *PaymentslistAccountsRequest) GetSort() []string {
	if p == nil {
		return nil
	}
	return p.Sort
}

type PaymentslistAccountsResponse struct {
	// OK
	AccountsCursor *shared.AccountsCursor
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PaymentslistAccountsResponse) GetAccountsCursor() *shared.AccountsCursor {
	if p == nil {
		return nil
	}
	return p.AccountsCursor
}

func (p *PaymentslistAccountsResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PaymentslistAccountsResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PaymentslistAccountsResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
