// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type PaymentsgetAccountRequest struct {
	// The account ID.
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
}

func (p *PaymentsgetAccountRequest) GetAccountID() string {
	if p == nil {
		return ""
	}
	return p.AccountID
}

type PaymentsgetAccountResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PaymentsAccountResponse *shared.PaymentsAccountResponse
}

func (p *PaymentsgetAccountResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PaymentsgetAccountResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PaymentsgetAccountResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PaymentsgetAccountResponse) GetPaymentsAccountResponse() *shared.PaymentsAccountResponse {
	if p == nil {
		return nil
	}
	return p.PaymentsAccountResponse
}
