// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type PaymentsgetServerInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Server information
	PaymentsServerInfo *shared.PaymentsServerInfo
}

func (p *PaymentsgetServerInfoResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PaymentsgetServerInfoResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PaymentsgetServerInfoResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PaymentsgetServerInfoResponse) GetPaymentsServerInfo() *shared.PaymentsServerInfo {
	if p == nil {
		return nil
	}
	return p.PaymentsServerInfo
}
