// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8f77139607b3

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/payments"
	"net/http"
)

type ReverseTransferInitiationRequest struct {
	ReverseTransferInitiationRequest payments.ReverseTransferInitiationRequest `request:"mediaType=application/json"`
	// The transfer ID.
	TransferID string `pathParam:"style=simple,explode=false,name=transferId"`
}

func (r *ReverseTransferInitiationRequest) GetReverseTransferInitiationRequest() payments.ReverseTransferInitiationRequest {
	if r == nil {
		return payments.ReverseTransferInitiationRequest{}
	}
	return r.ReverseTransferInitiationRequest
}

func (r *ReverseTransferInitiationRequest) GetTransferID() string {
	if r == nil {
		return ""
	}
	return r.TransferID
}

type ReverseTransferInitiationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *ReverseTransferInitiationResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReverseTransferInitiationResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReverseTransferInitiationResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
