// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type RunScriptRequest struct {
	Script shared.Script `request:"mediaType=application/json"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// Set the preview mode. Preview mode doesn't add the logs to the database or publish a message to the message broker.
	Preview *bool `queryParam:"style=form,explode=true,name=preview"`
}

func (r *RunScriptRequest) GetScript() shared.Script {
	if r == nil {
		return shared.Script{}
	}
	return r.Script
}

func (r *RunScriptRequest) GetLedger() string {
	if r == nil {
		return ""
	}
	return r.Ledger
}

func (r *RunScriptRequest) GetPreview() *bool {
	if r == nil {
		return nil
	}
	return r.Preview
}

type RunScriptResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// On success, it will return a 200 status code, and the resulting transaction under the `transaction` field.
	//
	// On failure, it will also return a 200 status code, and the following fields:
	//   - `details`: contains a URL. When there is an error parsing Numscript, the result can be difficult to read—the provided URL will render the error in an easy-to-read format.
	//   - `errorCode` and `error_code` (deprecated): contains the string code of the error
	//   - `errorMessage` and `error_message` (deprecated): contains a human-readable indication of what went wrong, for example that an account had insufficient funds, or that there was an error in the provided Numscript.
	//
	ScriptResponse *shared.ScriptResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *RunScriptResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RunScriptResponse) GetScriptResponse() *shared.ScriptResponse {
	if r == nil {
		return nil
	}
	return r.ScriptResponse
}

func (r *RunScriptResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RunScriptResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
