// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type RunWorkflowRequest struct {
	RequestBody map[string]string `request:"mediaType=application/json"`
	// Wait end of the workflow before return
	Wait *bool `queryParam:"style=form,explode=true,name=wait"`
	// The flow id
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowID"`
}

func (r *RunWorkflowRequest) GetRequestBody() map[string]string {
	if r == nil {
		return nil
	}
	return r.RequestBody
}

func (r *RunWorkflowRequest) GetWait() *bool {
	if r == nil {
		return nil
	}
	return r.Wait
}

func (r *RunWorkflowRequest) GetWorkflowID() string {
	if r == nil {
		return ""
	}
	return r.WorkflowID
}

type RunWorkflowResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The workflow instance
	RunWorkflowResponse *shared.RunWorkflowResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *RunWorkflowResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RunWorkflowResponse) GetRunWorkflowResponse() *shared.RunWorkflowResponse {
	if r == nil {
		return nil
	}
	return r.RunWorkflowResponse
}

func (r *RunWorkflowResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RunWorkflowResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
