// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v4/pkg/models/reconciliation"
	"net/http"
)

type SnoozeAlertRequest struct {
	SnoozeAlertRequest reconciliation.SnoozeAlertRequest `request:"mediaType=application/json"`
	// The alert ID.
	AlertID string `pathParam:"style=simple,explode=false,name=alertID"`
}

func (s *SnoozeAlertRequest) GetSnoozeAlertRequest() reconciliation.SnoozeAlertRequest {
	if s == nil {
		return reconciliation.SnoozeAlertRequest{}
	}
	return s.SnoozeAlertRequest
}

func (s *SnoozeAlertRequest) GetAlertID() string {
	if s == nil {
		return ""
	}
	return s.AlertID
}

type SnoozeAlertResponse struct {
	// OK
	AlertResponse *reconciliation.AlertResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (s *SnoozeAlertResponse) GetAlertResponse() *reconciliation.AlertResponse {
	if s == nil {
		return nil
	}
	return s.AlertResponse
}

func (s *SnoozeAlertResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SnoozeAlertResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SnoozeAlertResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}
