// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/orchestration"
	"net/http"
)

var TestTriggerServerList = []string{
	"http://localhost:8080/",
}

type TestTriggerRequest struct {
	RequestBody map[string]any `request:"mediaType=application/json"`
	// The trigger id
	TriggerID string `pathParam:"style=simple,explode=false,name=triggerID"`
}

func (t *TestTriggerRequest) GetRequestBody() map[string]any {
	if t == nil {
		return nil
	}
	return t.RequestBody
}

func (t *TestTriggerRequest) GetTriggerID() string {
	if t == nil {
		return ""
	}
	return t.TriggerID
}

type TestTriggerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Test a trigger
	V2TestTriggerResponse *orchestration.V2TestTriggerResponse
}

func (t *TestTriggerResponse) GetContentType() string {
	if t == nil {
		return ""
	}
	return t.ContentType
}

func (t *TestTriggerResponse) GetStatusCode() int {
	if t == nil {
		return 0
	}
	return t.StatusCode
}

func (t *TestTriggerResponse) GetRawResponse() *http.Response {
	if t == nil {
		return nil
	}
	return t.RawResponse
}

func (t *TestTriggerResponse) GetV2TestTriggerResponse() *orchestration.V2TestTriggerResponse {
	if t == nil {
		return nil
	}
	return t.V2TestTriggerResponse
}
