// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type UpdateClientRequest struct {
	ClientOptions *shared.ClientOptions `request:"mediaType=application/json"`
	// Client ID
	ClientID string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (o *UpdateClientRequest) GetClientOptions() *shared.ClientOptions {
	if o == nil {
		return nil
	}
	return o.ClientOptions
}

func (o *UpdateClientRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

type UpdateClientResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Updated client
	CreateClientResponse *shared.CreateClientResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateClientResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateClientResponse) GetCreateClientResponse() *shared.CreateClientResponse {
	if o == nil {
		return nil
	}
	return o.CreateClientResponse
}

func (o *UpdateClientResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateClientResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
