// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type UpdateBankAccountMetadataRequest struct {
	UpdateBankAccountMetadataRequest shared.UpdateBankAccountMetadataRequest `request:"mediaType=application/json"`
	// The bank account ID.
	BankAccountID string `pathParam:"style=simple,explode=false,name=bankAccountId"`
}

func (u *UpdateBankAccountMetadataRequest) GetUpdateBankAccountMetadataRequest() shared.UpdateBankAccountMetadataRequest {
	if u == nil {
		return shared.UpdateBankAccountMetadataRequest{}
	}
	return u.UpdateBankAccountMetadataRequest
}

func (u *UpdateBankAccountMetadataRequest) GetBankAccountID() string {
	if u == nil {
		return ""
	}
	return u.BankAccountID
}

type UpdateBankAccountMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateBankAccountMetadataResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateBankAccountMetadataResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateBankAccountMetadataResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
