// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type UpdateConfigRequest struct {
	ConfigUser shared.ConfigUser `request:"mediaType=application/json"`
	// Config ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (u *UpdateConfigRequest) GetConfigUser() shared.ConfigUser {
	if u == nil {
		return shared.ConfigUser{}
	}
	return u.ConfigUser
}

func (u *UpdateConfigRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

type UpdateConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateConfigResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateConfigResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateConfigResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
