// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type V2DeleteExporterRequest struct {
	// The exporter id
	ExporterID string `pathParam:"style=simple,explode=false,name=exporterID"`
}

func (v *V2DeleteExporterRequest) GetExporterID() string {
	if v == nil {
		return ""
	}
	return v.ExporterID
}

type V2DeleteExporterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V2DeleteExporterResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2DeleteExporterResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2DeleteExporterResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}
