// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"net/http"
)

type V2DeleteTransactionMetadataRequest struct {
	// Use an idempotency key
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
	// Transaction ID.
	ID *big.Int `pathParam:"style=simple,explode=false,name=id"`
	// The key to remove.
	Key string `pathParam:"style=simple,explode=false,name=key"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

func (v V2DeleteTransactionMetadataRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2DeleteTransactionMetadataRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "key", "ledger"}); err != nil {
		return err
	}
	return nil
}

func (v *V2DeleteTransactionMetadataRequest) GetIdempotencyKey() *string {
	if v == nil {
		return nil
	}
	return v.IdempotencyKey
}

func (v *V2DeleteTransactionMetadataRequest) GetID() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.ID
}

func (v *V2DeleteTransactionMetadataRequest) GetKey() string {
	if v == nil {
		return ""
	}
	return v.Key
}

func (v *V2DeleteTransactionMetadataRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

type V2DeleteTransactionMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V2DeleteTransactionMetadataResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2DeleteTransactionMetadataResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2DeleteTransactionMetadataResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}
