// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"net/http"
	"time"
)

type V2GetTransactionRequest struct {
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
	// Transaction ID.
	ID *big.Int `pathParam:"style=simple,explode=false,name=id"`
	// Name of the ledger.
	Ledger string     `pathParam:"style=simple,explode=false,name=ledger"`
	Pit    *time.Time `queryParam:"style=form,explode=true,name=pit"`
}

func (v V2GetTransactionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2GetTransactionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id", "ledger"}); err != nil {
		return err
	}
	return nil
}

func (v *V2GetTransactionRequest) GetExpand() *string {
	if v == nil {
		return nil
	}
	return v.Expand
}

func (v *V2GetTransactionRequest) GetID() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.ID
}

func (v *V2GetTransactionRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2GetTransactionRequest) GetPit() *time.Time {
	if v == nil {
		return nil
	}
	return v.Pit
}

type V2GetTransactionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V2GetTransactionResponse *shared.V2GetTransactionResponse
}

func (v *V2GetTransactionResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2GetTransactionResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2GetTransactionResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2GetTransactionResponse) GetV2GetTransactionResponse() *shared.V2GetTransactionResponse {
	if v == nil {
		return nil
	}
	return v.V2GetTransactionResponse
}
