// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2GetPipelineStateRequest struct {
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// The pipeline id
	PipelineID string `pathParam:"style=simple,explode=false,name=pipelineID"`
}

func (v *V2GetPipelineStateRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2GetPipelineStateRequest) GetPipelineID() string {
	if v == nil {
		return ""
	}
	return v.PipelineID
}

// V2GetPipelineStateResponseBody - Pipeline information
type V2GetPipelineStateResponseBody struct {
	Data shared.V2Pipeline `json:"data"`
}

func (v *V2GetPipelineStateResponseBody) GetData() shared.V2Pipeline {
	if v == nil {
		return shared.V2Pipeline{}
	}
	return v.Data
}

type V2GetPipelineStateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Pipeline information
	Object *V2GetPipelineStateResponseBody
}

func (v *V2GetPipelineStateResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2GetPipelineStateResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2GetPipelineStateResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2GetPipelineStateResponse) GetObject() *V2GetPipelineStateResponseBody {
	if v == nil {
		return nil
	}
	return v.Object
}
