// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2GetLedgerInfoRequest struct {
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

func (v *V2GetLedgerInfoRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

type V2GetLedgerInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V2LedgerInfoResponse *shared.V2LedgerInfoResponse
}

func (v *V2GetLedgerInfoResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2GetLedgerInfoResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2GetLedgerInfoResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2GetLedgerInfoResponse) GetV2LedgerInfoResponse() *shared.V2LedgerInfoResponse {
	if v == nil {
		return nil
	}
	return v.V2LedgerInfoResponse
}
