// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type V2ImportLogsRequest struct {
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	V2ImportLogsRequest any `request:"mediaType=application/octet-stream"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

func (v *V2ImportLogsRequest) GetV2ImportLogsRequest() any {
	if v == nil {
		return nil
	}
	return v.V2ImportLogsRequest
}

func (v *V2ImportLogsRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

type V2ImportLogsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V2ImportLogsResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2ImportLogsResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2ImportLogsResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}
