// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/ledger"
	"net/http"
)

var V2InsertSchemaServerList = []string{
	"http://localhost:8080/",
}

type V2InsertSchemaRequest struct {
	// Use an idempotency key
	IdempotencyKey *string                  `header:"style=simple,explode=false,name=Idempotency-Key"`
	V2SchemaData   ledger.V2SchemaDataInput `request:"mediaType=application/json"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// Schema version.
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (v *V2InsertSchemaRequest) GetIdempotencyKey() *string {
	if v == nil {
		return nil
	}
	return v.IdempotencyKey
}

func (v *V2InsertSchemaRequest) GetV2SchemaData() ledger.V2SchemaDataInput {
	if v == nil {
		return ledger.V2SchemaDataInput{}
	}
	return v.V2SchemaData
}

func (v *V2InsertSchemaRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2InsertSchemaRequest) GetVersion() string {
	if v == nil {
		return ""
	}
	return v.Version
}

// #region class-body-v2insertschemarequest
// #endregion class-body-v2insertschemarequest

type V2InsertSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V2InsertSchemaResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2InsertSchemaResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

func (v *V2InsertSchemaResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2InsertSchemaResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

// #region class-body-v2insertschemaresponse
// #endregion class-body-v2insertschemaresponse
