// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2ListInstancesRequest struct {
	// Parameter used in pagination requests.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The maximum number of results to return per page.
	//
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// Filter running instances
	Running *bool `queryParam:"style=form,explode=true,name=running"`
	// A workflow id
	WorkflowID *string `queryParam:"style=form,explode=true,name=workflowID"`
}

func (v *V2ListInstancesRequest) GetCursor() *string {
	if v == nil {
		return nil
	}
	return v.Cursor
}

func (v *V2ListInstancesRequest) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V2ListInstancesRequest) GetRunning() *bool {
	if v == nil {
		return nil
	}
	return v.Running
}

func (v *V2ListInstancesRequest) GetWorkflowID() *string {
	if v == nil {
		return nil
	}
	return v.WorkflowID
}

type V2ListInstancesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of workflow instances
	V2ListRunsResponse *shared.V2ListRunsResponse
}

func (v *V2ListInstancesResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2ListInstancesResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2ListInstancesResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2ListInstancesResponse) GetV2ListRunsResponse() *shared.V2ListRunsResponse {
	if v == nil {
		return nil
	}
	return v.V2ListRunsResponse
}
