// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type V2RestoreBucketRequest struct {
	// The bucket name
	Bucket string `pathParam:"style=simple,explode=false,name=bucket"`
}

func (v *V2RestoreBucketRequest) GetBucket() string {
	if v == nil {
		return ""
	}
	return v.Bucket
}

// #region class-body-v2restorebucketrequest
// #endregion class-body-v2restorebucketrequest

type V2RestoreBucketResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V2RestoreBucketResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2RestoreBucketResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2RestoreBucketResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

// #region class-body-v2restorebucketresponse
// #endregion class-body-v2restorebucketresponse
