// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2UpdateExporterRequest struct {
	V2CreateExporterRequest shared.V2CreateExporterRequest `request:"mediaType=application/json"`
	// The exporter id
	ExporterID string `pathParam:"style=simple,explode=false,name=exporterID"`
}

func (v *V2UpdateExporterRequest) GetV2CreateExporterRequest() shared.V2CreateExporterRequest {
	if v == nil {
		return shared.V2CreateExporterRequest{}
	}
	return v.V2CreateExporterRequest
}

func (v *V2UpdateExporterRequest) GetExporterID() string {
	if v == nil {
		return ""
	}
	return v.ExporterID
}

// #region class-body-v2updateexporterrequest
// #endregion class-body-v2updateexporterrequest

type V2UpdateExporterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V2UpdateExporterResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2UpdateExporterResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2UpdateExporterResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

// #region class-body-v2updateexporterresponse
// #endregion class-body-v2updateexporterresponse
