// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2UpdateLedgerMetadataRequest struct {
	RequestBody map[string]string `request:"mediaType=application/json"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

func (v *V2UpdateLedgerMetadataRequest) GetRequestBody() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.RequestBody
}

func (v *V2UpdateLedgerMetadataRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

type V2UpdateLedgerMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V2ErrorResponse *shared.V2ErrorResponse
}

func (v *V2UpdateLedgerMetadataResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2UpdateLedgerMetadataResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2UpdateLedgerMetadataResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2UpdateLedgerMetadataResponse) GetV2ErrorResponse() *shared.V2ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V2ErrorResponse
}
