// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/payments"
	"net/http"
)

var V3CreateLinkForPaymentServiceUserServerList = []string{
	"http://localhost:8080/",
}

type V3CreateLinkForPaymentServiceUserRequest struct {
	V3PaymentServiceUserCreateLinkRequest *payments.V3PaymentServiceUserCreateLinkRequest `request:"mediaType=application/json"`
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
}

func (v *V3CreateLinkForPaymentServiceUserRequest) GetV3PaymentServiceUserCreateLinkRequest() *payments.V3PaymentServiceUserCreateLinkRequest {
	if v == nil {
		return nil
	}
	return v.V3PaymentServiceUserCreateLinkRequest
}

func (v *V3CreateLinkForPaymentServiceUserRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3CreateLinkForPaymentServiceUserRequest) GetPaymentServiceUserID() string {
	if v == nil {
		return ""
	}
	return v.PaymentServiceUserID
}

// #region class-body-v3createlinkforpaymentserviceuserrequest
// #endregion class-body-v3createlinkforpaymentserviceuserrequest

type V3CreateLinkForPaymentServiceUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	V3PaymentServiceUserCreateLinkResponse *payments.V3PaymentServiceUserCreateLinkResponse
}

func (v *V3CreateLinkForPaymentServiceUserResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3CreateLinkForPaymentServiceUserResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3CreateLinkForPaymentServiceUserResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3CreateLinkForPaymentServiceUserResponse) GetV3PaymentServiceUserCreateLinkResponse() *payments.V3PaymentServiceUserCreateLinkResponse {
	if v == nil {
		return nil
	}
	return v.V3PaymentServiceUserCreateLinkResponse
}

// #region class-body-v3createlinkforpaymentserviceuserresponse
// #endregion class-body-v3createlinkforpaymentserviceuserresponse
