// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5ef3d2f8cb3d

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/payments"
	"net/http"
)

type V3DeletePaymentServiceUserRequest struct {
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
}

func (v *V3DeletePaymentServiceUserRequest) GetPaymentServiceUserID() string {
	if v == nil {
		return ""
	}
	return v.PaymentServiceUserID
}

// #region class-body-v3deletepaymentserviceuserrequest
// #endregion class-body-v3deletepaymentserviceuserrequest

type V3DeletePaymentServiceUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Accepted
	V3PaymentServiceUserDeleteResponse *payments.V3PaymentServiceUserDeleteResponse
}

func (v *V3DeletePaymentServiceUserResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3DeletePaymentServiceUserResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3DeletePaymentServiceUserResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3DeletePaymentServiceUserResponse) GetV3PaymentServiceUserDeleteResponse() *payments.V3PaymentServiceUserDeleteResponse {
	if v == nil {
		return nil
	}
	return v.V3PaymentServiceUserDeleteResponse
}

// #region class-body-v3deletepaymentserviceuserresponse
// #endregion class-body-v3deletepaymentserviceuserresponse
