// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 14492a603557

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/payments"
	"net/http"
)

type V3DeletePaymentServiceUserConnectionFromConnectorIDRequest struct {
	// The connection ID
	ConnectionID string `pathParam:"style=simple,explode=false,name=connectionID"`
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDRequest) GetConnectionID() string {
	if v == nil {
		return ""
	}
	return v.ConnectionID
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDRequest) GetPaymentServiceUserID() string {
	if v == nil {
		return ""
	}
	return v.PaymentServiceUserID
}

// #region class-body-v3deletepaymentserviceuserconnectionfromconnectoridrequest
// #endregion class-body-v3deletepaymentserviceuserconnectionfromconnectoridrequest

type V3DeletePaymentServiceUserConnectionFromConnectorIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Accepted
	V3PaymentServiceUserDeleteConnectionResponse *payments.V3PaymentServiceUserDeleteConnectionResponse
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3DeletePaymentServiceUserConnectionFromConnectorIDResponse) GetV3PaymentServiceUserDeleteConnectionResponse() *payments.V3PaymentServiceUserDeleteConnectionResponse {
	if v == nil {
		return nil
	}
	return v.V3PaymentServiceUserDeleteConnectionResponse
}

// #region class-body-v3deletepaymentserviceuserconnectionfromconnectoridresponse
// #endregion class-body-v3deletepaymentserviceuserconnectionfromconnectoridresponse
