// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3ForwardBankAccountRequest struct {
	V3ForwardBankAccountRequest *shared.V3ForwardBankAccountRequest `request:"mediaType=application/json"`
	// The bank account ID
	BankAccountID string `pathParam:"style=simple,explode=false,name=bankAccountID"`
}

func (o *V3ForwardBankAccountRequest) GetV3ForwardBankAccountRequest() *shared.V3ForwardBankAccountRequest {
	if o == nil {
		return nil
	}
	return o.V3ForwardBankAccountRequest
}

func (o *V3ForwardBankAccountRequest) GetBankAccountID() string {
	if o == nil {
		return ""
	}
	return o.BankAccountID
}

type V3ForwardBankAccountResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Accepted
	V3ForwardBankAccountResponse *shared.V3ForwardBankAccountResponse
}

func (o *V3ForwardBankAccountResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V3ForwardBankAccountResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V3ForwardBankAccountResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V3ForwardBankAccountResponse) GetV3ForwardBankAccountResponse() *shared.V3ForwardBankAccountResponse {
	if o == nil {
		return nil
	}
	return o.V3ForwardBankAccountResponse
}
