// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3GetTaskRequest struct {
	// The task ID
	TaskID string `pathParam:"style=simple,explode=false,name=taskID"`
}

func (v *V3GetTaskRequest) GetTaskID() string {
	if v == nil {
		return ""
	}
	return v.TaskID
}

type V3GetTaskResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V3GetTaskResponse *shared.V3GetTaskResponse
}

func (v *V3GetTaskResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3GetTaskResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3GetTaskResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3GetTaskResponse) GetV3GetTaskResponse() *shared.V3GetTaskResponse {
	if v == nil {
		return nil
	}
	return v.V3GetTaskResponse
}
