// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3GetConnectorScheduleRequest struct {
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
	// The schedule ID
	ScheduleID string `pathParam:"style=simple,explode=false,name=scheduleID"`
}

func (o *V3GetConnectorScheduleRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3GetConnectorScheduleRequest) GetScheduleID() string {
	if o == nil {
		return ""
	}
	return o.ScheduleID
}

type V3GetConnectorScheduleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V3ConnectorScheduleResponse *shared.V3ConnectorScheduleResponse
}

func (o *V3GetConnectorScheduleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V3GetConnectorScheduleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V3GetConnectorScheduleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V3GetConnectorScheduleResponse) GetV3ConnectorScheduleResponse() *shared.V3ConnectorScheduleResponse {
	if o == nil {
		return nil
	}
	return o.V3ConnectorScheduleResponse
}
