// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3GetPoolRequest struct {
	// The pool ID
	PoolID string `pathParam:"style=simple,explode=false,name=poolID"`
}

func (v *V3GetPoolRequest) GetPoolID() string {
	if v == nil {
		return ""
	}
	return v.PoolID
}

type V3GetPoolResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V3GetPoolResponse *shared.V3GetPoolResponse
}

func (v *V3GetPoolResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3GetPoolResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3GetPoolResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3GetPoolResponse) GetV3GetPoolResponse() *shared.V3GetPoolResponse {
	if v == nil {
		return nil
	}
	return v.V3GetPoolResponse
}
