// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 95653bfaf133

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/payments"
	"net/http"
)

type V3ListPaymentServiceUserLinkAttemptsFromConnectorIDRequest struct {
	RequestBody map[string]any `request:"mediaType=application/json"`
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
	// Parameter used in pagination requests. Set to the value of next for the next page of results. Set to the value of previous for the previous page of results. No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// The number of items to return
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDRequest) GetRequestBody() map[string]any {
	if v == nil {
		return nil
	}
	return v.RequestBody
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDRequest) GetCursor() *string {
	if v == nil {
		return nil
	}
	return v.Cursor
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDRequest) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDRequest) GetPaymentServiceUserID() string {
	if v == nil {
		return ""
	}
	return v.PaymentServiceUserID
}

// #region class-body-v3listpaymentserviceuserlinkattemptsfromconnectoridrequest
// #endregion class-body-v3listpaymentserviceuserlinkattemptsfromconnectoridrequest

type V3ListPaymentServiceUserLinkAttemptsFromConnectorIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V3PaymentServiceUserLinkAttemptsCursorResponse *payments.V3PaymentServiceUserLinkAttemptsCursorResponse
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3ListPaymentServiceUserLinkAttemptsFromConnectorIDResponse) GetV3PaymentServiceUserLinkAttemptsCursorResponse() *payments.V3PaymentServiceUserLinkAttemptsCursorResponse {
	if v == nil {
		return nil
	}
	return v.V3PaymentServiceUserLinkAttemptsCursorResponse
}

// #region class-body-v3listpaymentserviceuserlinkattemptsfromconnectoridresponse
// #endregion class-body-v3listpaymentserviceuserlinkattemptsfromconnectoridresponse
