// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/models/payments"
	"net/http"
)

type V3ListConnectorCapabilitiesRequest struct {
	// ETag from a previous response; a matching value yields 304 Not Modified.
	IfNoneMatch *string `header:"style=simple,explode=false,name=If-None-Match"`
}

func (v *V3ListConnectorCapabilitiesRequest) GetIfNoneMatch() *string {
	if v == nil {
		return nil
	}
	return v.IfNoneMatch
}

// #region class-body-v3listconnectorcapabilitiesrequest
// #endregion class-body-v3listconnectorcapabilitiesrequest

type V3ListConnectorCapabilitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	V3ConnectorCapabilitiesResponse *payments.V3ConnectorCapabilitiesResponse
}

func (v *V3ListConnectorCapabilitiesResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3ListConnectorCapabilitiesResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

func (v *V3ListConnectorCapabilitiesResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3ListConnectorCapabilitiesResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3ListConnectorCapabilitiesResponse) GetV3ConnectorCapabilitiesResponse() *payments.V3ConnectorCapabilitiesResponse {
	if v == nil {
		return nil
	}
	return v.V3ConnectorCapabilitiesResponse
}

// #region class-body-v3listconnectorcapabilitiesresponse
// #endregion class-body-v3listconnectorcapabilitiesresponse
