// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3ReversePaymentInitiationRequest struct {
	V3ReversePaymentInitiationRequest *shared.V3ReversePaymentInitiationRequest `request:"mediaType=application/json"`
	// The payment initiation ID
	PaymentInitiationID string `pathParam:"style=simple,explode=false,name=paymentInitiationID"`
}

func (v *V3ReversePaymentInitiationRequest) GetV3ReversePaymentInitiationRequest() *shared.V3ReversePaymentInitiationRequest {
	if v == nil {
		return nil
	}
	return v.V3ReversePaymentInitiationRequest
}

func (v *V3ReversePaymentInitiationRequest) GetPaymentInitiationID() string {
	if v == nil {
		return ""
	}
	return v.PaymentInitiationID
}

type V3ReversePaymentInitiationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Accepted
	V3ReversePaymentInitiationResponse *shared.V3ReversePaymentInitiationResponse
}

func (v *V3ReversePaymentInitiationResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3ReversePaymentInitiationResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3ReversePaymentInitiationResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3ReversePaymentInitiationResponse) GetV3ReversePaymentInitiationResponse() *shared.V3ReversePaymentInitiationResponse {
	if v == nil {
		return nil
	}
	return v.V3ReversePaymentInitiationResponse
}
