// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3UpdatePaymentMetadataRequest struct {
	V3UpdatePaymentMetadataRequest *shared.V3UpdatePaymentMetadataRequest `request:"mediaType=application/json"`
	// The payment ID
	PaymentID string `pathParam:"style=simple,explode=false,name=paymentID"`
}

func (v *V3UpdatePaymentMetadataRequest) GetV3UpdatePaymentMetadataRequest() *shared.V3UpdatePaymentMetadataRequest {
	if v == nil {
		return nil
	}
	return v.V3UpdatePaymentMetadataRequest
}

func (v *V3UpdatePaymentMetadataRequest) GetPaymentID() string {
	if v == nil {
		return ""
	}
	return v.PaymentID
}

type V3UpdatePaymentMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V3UpdatePaymentMetadataResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3UpdatePaymentMetadataResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3UpdatePaymentMetadataResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}
