// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d810f93ba80d

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/payments"
	"net/http"
)

type V3UpdateConnectorConfigRequest struct {
	V3ConnectorConfig *payments.V3ConnectorConfig `request:"mediaType=application/json"`
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
}

func (v *V3UpdateConnectorConfigRequest) GetV3ConnectorConfig() *payments.V3ConnectorConfig {
	if v == nil {
		return nil
	}
	return v.V3ConnectorConfig
}

func (v *V3UpdateConnectorConfigRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

// #region class-body-v3updateconnectorconfigrequest
// #endregion class-body-v3updateconnectorconfigrequest

type V3UpdateConnectorConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *V3UpdateConnectorConfigResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3UpdateConnectorConfigResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3UpdateConnectorConfigResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

// #region class-body-v3updateconnectorconfigresponse
// #endregion class-body-v3updateconnectorconfigresponse
