// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3UpdateConnectorConfigRequest struct {
	V3InstallConnectorRequest *shared.V3InstallConnectorRequest `request:"mediaType=application/json"`
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequest() *shared.V3InstallConnectorRequest {
	if o == nil {
		return nil
	}
	return o.V3InstallConnectorRequest
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestAdyen() *shared.V3AdyenConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3AdyenConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestAtlar() *shared.V3AtlarConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3AtlarConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestBankingcircle() *shared.V3BankingcircleConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3BankingcircleConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestColumn() *shared.V3ColumnConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3ColumnConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestCurrencycloud() *shared.V3CurrencycloudConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3CurrencycloudConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestDummypay() *shared.V3DummypayConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3DummypayConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestGeneric() *shared.V3GenericConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3GenericConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestMangopay() *shared.V3MangopayConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3MangopayConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestModulr() *shared.V3ModulrConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3ModulrConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestMoneycorp() *shared.V3MoneycorpConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3MoneycorpConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestQonto() *shared.V3QontoConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3QontoConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestStripe() *shared.V3StripeConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3StripeConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetV3InstallConnectorRequestWise() *shared.V3WiseConfig {
	if v := o.GetV3InstallConnectorRequest(); v != nil {
		return v.V3WiseConfig
	}
	return nil
}

func (o *V3UpdateConnectorConfigRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

type V3UpdateConnectorConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *V3UpdateConnectorConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V3UpdateConnectorConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V3UpdateConnectorConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
