// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3ed02d1aa328

package orchestration

type AccountResponse struct {
	Account Account `json:"data"`
}

func (a *AccountResponse) GetAccount() Account {
	if a == nil {
		return Account{}
	}
	return a.Account
}
