// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type Account struct {
	Address          string            `json:"address"`
	EffectiveVolumes map[string]Volume `json:"effectiveVolumes,omitempty"`
	Metadata         map[string]string `json:"metadata"`
	Volumes          map[string]Volume `json:"volumes,omitempty"`
}

func (a *Account) GetAddress() string {
	if a == nil {
		return ""
	}
	return a.Address
}

func (a *Account) GetEffectiveVolumes() map[string]Volume {
	if a == nil {
		return nil
	}
	return a.EffectiveVolumes
}

func (a *Account) GetMetadata() map[string]string {
	if a == nil {
		return map[string]string{}
	}
	return a.Metadata
}

func (a *Account) GetVolumes() map[string]Volume {
	if a == nil {
		return nil
	}
	return a.Volumes
}
