// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ad8f47fcfdf0

package orchestration

type ActivityGetPayment struct {
	ID string `json:"id"`
}

func (a *ActivityGetPayment) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}
