// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type CreateTransactionResponse struct {
	Data Transaction `json:"data"`
}

func (c *CreateTransactionResponse) GetData() Transaction {
	if c == nil {
		return Transaction{}
	}
	return c.Data
}
