// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5044252fa9cd

package orchestration

type CreateTriggerResponse struct {
	TriggerData TriggerData `json:"data"`
}

func (c *CreateTriggerResponse) GetTriggerData() TriggerData {
	if c == nil {
		return TriggerData{}
	}
	return c.TriggerData
}
