// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type CreateWorkflowResponse struct {
	Workflow Workflow `json:"data"`
}

func (c *CreateWorkflowResponse) GetWorkflow() Workflow {
	if c == nil {
		return Workflow{}
	}
	return c.Workflow
}
