// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bafb22e99fe5

package orchestration

type DebitWalletResponse struct {
	Hold Hold `json:"data"`
}

func (d *DebitWalletResponse) GetHold() Hold {
	if d == nil {
		return Hold{}
	}
	return d.Hold
}
