// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type GetWorkflowInstanceResponse struct {
	WorkflowInstance WorkflowInstance `json:"data"`
}

func (g *GetWorkflowInstanceResponse) GetWorkflowInstance() WorkflowInstance {
	if g == nil {
		return WorkflowInstance{}
	}
	return g.WorkflowInstance
}
