// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type GetWalletResponse struct {
	WalletWithBalances WalletWithBalances `json:"data"`
}

func (g *GetWalletResponse) GetWalletWithBalances() WalletWithBalances {
	if g == nil {
		return WalletWithBalances{}
	}
	return g.WalletWithBalances
}
