// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b120fca01f6e

package orchestration

type ListRunsResponse struct {
	Data []WorkflowInstance `json:"data"`
}

func (l *ListRunsResponse) GetData() []WorkflowInstance {
	if l == nil {
		return []WorkflowInstance{}
	}
	return l.Data
}
