// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 699d3e2e5717

package orchestration

type ListTriggersResponse struct {
	Data []TriggerData `json:"data"`
}

func (l *ListTriggersResponse) GetData() []TriggerData {
	if l == nil {
		return []TriggerData{}
	}
	return l.Data
}
