// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 47bb1fafd495

package orchestration

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type Raw struct {
}

type Scheme string

const (
	SchemeVisa       Scheme = "visa"
	SchemeMastercard Scheme = "mastercard"
	SchemeAmex       Scheme = "amex"
	SchemeDiners     Scheme = "diners"
	SchemeDiscover   Scheme = "discover"
	SchemeJcb        Scheme = "jcb"
	SchemeUnionpay   Scheme = "unionpay"
	SchemeSepaDebit  Scheme = "sepa debit"
	SchemeSepaCredit Scheme = "sepa credit"
	SchemeSepa       Scheme = "sepa"
	SchemeApplePay   Scheme = "apple pay"
	SchemeGooglePay  Scheme = "google pay"
	SchemeA2a        Scheme = "a2a"
	SchemeAchDebit   Scheme = "ach debit"
	SchemeAch        Scheme = "ach"
	SchemeRtp        Scheme = "rtp"
	SchemeUnknown    Scheme = "unknown"
	SchemeOther      Scheme = "other"
)

func (e Scheme) ToPointer() *Scheme {
	return &e
}
func (e *Scheme) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "diners":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "sepa debit":
		fallthrough
	case "sepa credit":
		fallthrough
	case "sepa":
		fallthrough
	case "apple pay":
		fallthrough
	case "google pay":
		fallthrough
	case "a2a":
		fallthrough
	case "ach debit":
		fallthrough
	case "ach":
		fallthrough
	case "rtp":
		fallthrough
	case "unknown":
		fallthrough
	case "other":
		*e = Scheme(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Scheme: %v", v)
	}
}

type Type string

const (
	TypePayIn    Type = "PAY-IN"
	TypePayout   Type = "PAYOUT"
	TypeTransfer Type = "TRANSFER"
	TypeOther    Type = "OTHER"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PAY-IN":
		fallthrough
	case "PAYOUT":
		fallthrough
	case "TRANSFER":
		fallthrough
	case "OTHER":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type Payment struct {
	Connector            *Connector          `json:"provider,omitempty"`
	PaymentMetadata      *PaymentMetadata    `json:"metadata"`
	PaymentStatus        PaymentStatus       `json:"status"`
	Adjustments          []PaymentAdjustment `json:"adjustments"`
	Asset                string              `json:"asset"`
	ConnectorID          string              `json:"connectorID"`
	CreatedAt            time.Time           `json:"createdAt"`
	DestinationAccountID string              `json:"destinationAccountID"`
	ID                   string              `json:"id"`
	InitialAmount        *big.Int            `json:"initialAmount"`
	Raw                  *Raw                `json:"raw"`
	Reference            string              `json:"reference"`
	Scheme               Scheme              `json:"scheme"`
	SourceAccountID      string              `json:"sourceAccountID"`
	Type                 Type                `json:"type"`
}

func (p Payment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Payment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Payment) GetConnector() *Connector {
	if p == nil {
		return nil
	}
	return p.Connector
}

func (p *Payment) GetPaymentMetadata() *PaymentMetadata {
	if p == nil {
		return nil
	}
	return p.PaymentMetadata
}

func (p *Payment) GetPaymentStatus() PaymentStatus {
	if p == nil {
		return PaymentStatus("")
	}
	return p.PaymentStatus
}

func (p *Payment) GetAdjustments() []PaymentAdjustment {
	if p == nil {
		return []PaymentAdjustment{}
	}
	return p.Adjustments
}

func (p *Payment) GetAsset() string {
	if p == nil {
		return ""
	}
	return p.Asset
}

func (p *Payment) GetConnectorID() string {
	if p == nil {
		return ""
	}
	return p.ConnectorID
}

func (p *Payment) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Payment) GetDestinationAccountID() string {
	if p == nil {
		return ""
	}
	return p.DestinationAccountID
}

func (p *Payment) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Payment) GetInitialAmount() *big.Int {
	if p == nil {
		return big.NewInt(0)
	}
	return p.InitialAmount
}

func (p *Payment) GetRaw() *Raw {
	if p == nil {
		return nil
	}
	return p.Raw
}

func (p *Payment) GetReference() string {
	if p == nil {
		return ""
	}
	return p.Reference
}

func (p *Payment) GetScheme() Scheme {
	if p == nil {
		return Scheme("")
	}
	return p.Scheme
}

func (p *Payment) GetSourceAccountID() string {
	if p == nil {
		return ""
	}
	return p.SourceAccountID
}

func (p *Payment) GetType() Type {
	if p == nil {
		return Type("")
	}
	return p.Type
}
