// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type PaymentMetadata struct {
	Key *string `json:"key,omitempty"`
}

func (p *PaymentMetadata) GetKey() *string {
	if p == nil {
		return nil
	}
	return p.Key
}
