// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type ReadTriggerResponse struct {
	TriggerData TriggerData `json:"data"`
}

func (r *ReadTriggerResponse) GetTriggerData() TriggerData {
	if r == nil {
		return TriggerData{}
	}
	return r.TriggerData
}
