// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type StageSendSource struct {
	StageSendSourceAccount *StageSendSourceAccount `json:"account,omitempty"`
	StageSendSourcePayment *StageSendSourcePayment `json:"payment,omitempty"`
	StageSendSourceWallet  *StageSendSourceWallet  `json:"wallet,omitempty"`
}

func (s StageSendSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSendSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StageSendSource) GetStageSendSourceAccount() *StageSendSourceAccount {
	if s == nil {
		return nil
	}
	return s.StageSendSourceAccount
}

func (s *StageSendSource) GetStageSendSourcePayment() *StageSendSourcePayment {
	if s == nil {
		return nil
	}
	return s.StageSendSourcePayment
}

func (s *StageSendSource) GetStageSendSourceWallet() *StageSendSourceWallet {
	if s == nil {
		return nil
	}
	return s.StageSendSourceWallet
}
