// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
)

type StageSendSource struct {
	Account *StageSendSourceAccount `json:"account,omitempty"`
	Payment *StageSendSourcePayment `json:"payment,omitempty"`
	Wallet  *StageSendSourceWallet  `json:"wallet,omitempty"`
}

func (s StageSendSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSendSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StageSendSource) GetAccount() *StageSendSourceAccount {
	if s == nil {
		return nil
	}
	return s.Account
}

func (s *StageSendSource) GetPayment() *StageSendSourcePayment {
	if s == nil {
		return nil
	}
	return s.Payment
}

func (s *StageSendSource) GetWallet() *StageSendSourceWallet {
	if s == nil {
		return nil
	}
	return s.Wallet
}
