// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
)

type StageSendDestination struct {
	Account *StageSendSourceAccount      `json:"account,omitempty"`
	Payment *StageSendDestinationPayment `json:"payment,omitempty"`
	Wallet  *StageSendSourceWallet       `json:"wallet,omitempty"`
}

func (s StageSendDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSendDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StageSendDestination) GetAccount() *StageSendSourceAccount {
	if s == nil {
		return nil
	}
	return s.Account
}

func (s *StageSendDestination) GetPayment() *StageSendDestinationPayment {
	if s == nil {
		return nil
	}
	return s.Payment
}

func (s *StageSendDestination) GetWallet() *StageSendSourceWallet {
	if s == nil {
		return nil
	}
	return s.Wallet
}
