// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type TriggerData struct {
	CreatedAt  time.Time      `json:"createdAt"`
	Event      string         `json:"event"`
	Filter     *string        `json:"filter,omitempty"`
	ID         string         `json:"id"`
	Name       *string        `json:"name,omitempty"`
	Vars       map[string]any `json:"vars,omitempty"`
	Version    *string        `json:"version,omitempty"`
	WorkflowID string         `json:"workflowID"`
}

func (t TriggerData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TriggerData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TriggerData) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TriggerData) GetEvent() string {
	if t == nil {
		return ""
	}
	return t.Event
}

func (t *TriggerData) GetFilter() *string {
	if t == nil {
		return nil
	}
	return t.Filter
}

func (t *TriggerData) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TriggerData) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TriggerData) GetVars() map[string]any {
	if t == nil {
		return nil
	}
	return t.Vars
}

func (t *TriggerData) GetVersion() *string {
	if t == nil {
		return nil
	}
	return t.Version
}

func (t *TriggerData) GetWorkflowID() string {
	if t == nil {
		return ""
	}
	return t.WorkflowID
}
