// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type TriggerData1 struct {
	Event      string         `json:"event"`
	Filter     *string        `json:"filter,omitempty"`
	Name       *string        `json:"name,omitempty"`
	Vars       map[string]any `json:"vars,omitempty"`
	Version    *string        `json:"version,omitempty"`
	WorkflowID string         `json:"workflowID"`
}

func (t *TriggerData1) GetEvent() string {
	if t == nil {
		return ""
	}
	return t.Event
}

func (t *TriggerData1) GetFilter() *string {
	if t == nil {
		return nil
	}
	return t.Filter
}

func (t *TriggerData1) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TriggerData1) GetVars() map[string]any {
	if t == nil {
		return nil
	}
	return t.Vars
}

func (t *TriggerData1) GetVersion() *string {
	if t == nil {
		return nil
	}
	return t.Version
}

func (t *TriggerData1) GetWorkflowID() string {
	if t == nil {
		return ""
	}
	return t.WorkflowID
}

// #region class-body-triggerdata1
// #endregion class-body-triggerdata1
