// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type V2ActivityVoidHold struct {
	ID string `json:"id"`
}

func (v *V2ActivityVoidHold) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

// #region class-body-v2activityvoidhold
// #endregion class-body-v2activityvoidhold
