// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type V2GetWalletResponse struct {
	Data V2WalletWithBalances `json:"data"`
}

func (v *V2GetWalletResponse) GetData() V2WalletWithBalances {
	if v == nil {
		return V2WalletWithBalances{}
	}
	return v.Data
}

// #region class-body-v2getwalletresponse
// #endregion class-body-v2getwalletresponse
