// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type V2PaymentMetadata struct {
	Key *string `json:"key,omitempty"`
}

func (v *V2PaymentMetadata) GetKey() *string {
	if v == nil {
		return nil
	}
	return v.Key
}

// #region class-body-v2paymentmetadata
// #endregion class-body-v2paymentmetadata
