// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cec91642a11f

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2StageSendDestination struct {
	V2StageSendDestinationPayment *V2StageSendDestinationPayment `json:"payment,omitempty"`
	V2StageSendSourceAccount      *V2StageSendSourceAccount      `json:"account,omitempty"`
	V2StageSendSourceWallet       *V2StageSendSourceWallet       `json:"wallet,omitempty"`
}

func (v V2StageSendDestination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StageSendDestination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2StageSendDestination) GetV2StageSendDestinationPayment() *V2StageSendDestinationPayment {
	if v == nil {
		return nil
	}
	return v.V2StageSendDestinationPayment
}

func (v *V2StageSendDestination) GetV2StageSendSourceAccount() *V2StageSendSourceAccount {
	if v == nil {
		return nil
	}
	return v.V2StageSendSourceAccount
}

func (v *V2StageSendDestination) GetV2StageSendSourceWallet() *V2StageSendSourceWallet {
	if v == nil {
		return nil
	}
	return v.V2StageSendSourceWallet
}

// #region class-body-v2stagesenddestination
// #endregion class-body-v2stagesenddestination
