// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2StageSendSourceAccount struct {
	ID     string  `json:"id"`
	Ledger *string `json:"ledger,omitempty"`
}

func (v V2StageSendSourceAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StageSendSourceAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (v *V2StageSendSourceAccount) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V2StageSendSourceAccount) GetLedger() *string {
	if v == nil {
		return nil
	}
	return v.Ledger
}

// #region class-body-v2stagesendsourceaccount
// #endregion class-body-v2stagesendsourceaccount
