// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1648d71a460a

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2StageWaitEvent struct {
	Event string `json:"event"`
}

func (v V2StageWaitEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StageWaitEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"event"}); err != nil {
		return err
	}
	return nil
}

func (v *V2StageWaitEvent) GetEvent() string {
	if v == nil {
		return ""
	}
	return v.Event
}

// #region class-body-v2stagewaitevent
// #endregion class-body-v2stagewaitevent
