// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v4/pkg/utils"
)

type V2StageSendSource struct {
	Account *V2StageSendSourceAccount `json:"account,omitempty"`
	Payment *V2StageSendSourcePayment `json:"payment,omitempty"`
	Wallet  *V2StageSendSourceWallet  `json:"wallet,omitempty"`
}

func (v V2StageSendSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2StageSendSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2StageSendSource) GetAccount() *V2StageSendSourceAccount {
	if v == nil {
		return nil
	}
	return v.Account
}

func (v *V2StageSendSource) GetPayment() *V2StageSendSourcePayment {
	if v == nil {
		return nil
	}
	return v.Payment
}

func (v *V2StageSendSource) GetWallet() *V2StageSendSourceWallet {
	if v == nil {
		return nil
	}
	return v.Wallet
}

// #region class-body-v2stagesendsource
// #endregion class-body-v2stagesendsource
