// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type V2TestTriggerResponse struct {
	V2TriggerTest V2TriggerTest `json:"data"`
}

func (v *V2TestTriggerResponse) GetV2TriggerTest() V2TriggerTest {
	if v == nil {
		return V2TriggerTest{}
	}
	return v.V2TriggerTest
}

// #region class-body-v2testtriggerresponse
// #endregion class-body-v2testtriggerresponse
