// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type V2Transaction struct {
	V2Metadata map[string]string `json:"metadata"`
	Postings   []V2Posting       `json:"postings"`
	Reference  *string           `json:"reference,omitempty"`
	Timestamp  time.Time         `json:"timestamp"`
	Txid       *big.Int          `json:"txid"`
}

func (v V2Transaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2Transaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2Transaction) GetV2Metadata() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.V2Metadata
}

func (v *V2Transaction) GetPostings() []V2Posting {
	if v == nil {
		return []V2Posting{}
	}
	return v.Postings
}

func (v *V2Transaction) GetReference() *string {
	if v == nil {
		return nil
	}
	return v.Reference
}

func (v *V2Transaction) GetTimestamp() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.Timestamp
}

func (v *V2Transaction) GetTxid() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.Txid
}

// #region class-body-v2transaction
// #endregion class-body-v2transaction
