// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type V2TriggerData1 struct {
	Event      string         `json:"event"`
	Filter     *string        `json:"filter,omitempty"`
	Name       *string        `json:"name,omitempty"`
	Vars       map[string]any `json:"vars,omitempty"`
	Version    *string        `json:"version,omitempty"`
	WorkflowID string         `json:"workflowID"`
}

func (v *V2TriggerData1) GetEvent() string {
	if v == nil {
		return ""
	}
	return v.Event
}

func (v *V2TriggerData1) GetFilter() *string {
	if v == nil {
		return nil
	}
	return v.Filter
}

func (v *V2TriggerData1) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V2TriggerData1) GetVars() map[string]any {
	if v == nil {
		return nil
	}
	return v.Vars
}

func (v *V2TriggerData1) GetVersion() *string {
	if v == nil {
		return nil
	}
	return v.Version
}

func (v *V2TriggerData1) GetWorkflowID() string {
	if v == nil {
		return ""
	}
	return v.WorkflowID
}

// #region class-body-v2triggerdata1
// #endregion class-body-v2triggerdata1
