// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1aea92de632f

package orchestration

type V2WorkflowInstanceHistoryStageInput struct {
	V2ActivityAddAccountMetadata *V2ActivityAddAccountMetadata `json:"AddAccountMetadata,omitempty"`
	V2ActivityConfirmHold        *V2ActivityConfirmHold        `json:"ConfirmHold,omitempty"`
	V2ActivityCreateTransaction  *V2ActivityCreateTransaction  `json:"CreateTransaction,omitempty"`
	V2ActivityCreditWallet       *V2ActivityCreditWallet       `json:"CreditWallet,omitempty"`
	V2ActivityDebitWallet        *V2ActivityDebitWallet        `json:"DebitWallet,omitempty"`
	V2ActivityGetAccount         *V2ActivityGetAccount         `json:"GetAccount,omitempty"`
	V2ActivityGetPayment         *V2ActivityGetPayment         `json:"GetPayment,omitempty"`
	V2ActivityGetWallet          *V2ActivityGetWallet          `json:"GetWallet,omitempty"`
	V2ActivityListWallets        *V2ActivityListWallets        `json:"ListWallets,omitempty"`
	V2ActivityVoidHold           *V2ActivityVoidHold           `json:"VoidHold,omitempty"`
	V2StripeTransferRequest      *V2StripeTransferRequest      `json:"StripeTransfer,omitempty"`
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityAddAccountMetadata() *V2ActivityAddAccountMetadata {
	if v == nil {
		return nil
	}
	return v.V2ActivityAddAccountMetadata
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityConfirmHold() *V2ActivityConfirmHold {
	if v == nil {
		return nil
	}
	return v.V2ActivityConfirmHold
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityCreateTransaction() *V2ActivityCreateTransaction {
	if v == nil {
		return nil
	}
	return v.V2ActivityCreateTransaction
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityCreditWallet() *V2ActivityCreditWallet {
	if v == nil {
		return nil
	}
	return v.V2ActivityCreditWallet
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityDebitWallet() *V2ActivityDebitWallet {
	if v == nil {
		return nil
	}
	return v.V2ActivityDebitWallet
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityGetAccount() *V2ActivityGetAccount {
	if v == nil {
		return nil
	}
	return v.V2ActivityGetAccount
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityGetPayment() *V2ActivityGetPayment {
	if v == nil {
		return nil
	}
	return v.V2ActivityGetPayment
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityGetWallet() *V2ActivityGetWallet {
	if v == nil {
		return nil
	}
	return v.V2ActivityGetWallet
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityListWallets() *V2ActivityListWallets {
	if v == nil {
		return nil
	}
	return v.V2ActivityListWallets
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2ActivityVoidHold() *V2ActivityVoidHold {
	if v == nil {
		return nil
	}
	return v.V2ActivityVoidHold
}

func (v *V2WorkflowInstanceHistoryStageInput) GetV2StripeTransferRequest() *V2StripeTransferRequest {
	if v == nil {
		return nil
	}
	return v.V2StripeTransferRequest
}

// #region class-body-v2workflowinstancehistorystageinput
// #endregion class-body-v2workflowinstancehistorystageinput
