// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type V2WorkflowConfig struct {
	Name   *string          `json:"name,omitempty"`
	Stages []map[string]any `json:"stages"`
}

func (v *V2WorkflowConfig) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V2WorkflowConfig) GetStages() []map[string]any {
	if v == nil {
		return []map[string]any{}
	}
	return v.Stages
}

// #region class-body-v2workflowconfig
// #endregion class-body-v2workflowconfig
