// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package orchestration

type WorkflowInstanceHistoryStageInput struct {
	ActivityAddAccountMetadata *ActivityAddAccountMetadata `json:"AddAccountMetadata,omitempty"`
	ActivityConfirmHold        *ActivityConfirmHold        `json:"ConfirmHold,omitempty"`
	ActivityCreateTransaction  *ActivityCreateTransaction  `json:"CreateTransaction,omitempty"`
	ActivityCreditWallet       *ActivityCreditWallet       `json:"CreditWallet,omitempty"`
	ActivityDebitWallet        *ActivityDebitWallet        `json:"DebitWallet,omitempty"`
	ActivityGetAccount         *ActivityGetAccount         `json:"GetAccount,omitempty"`
	ActivityGetPayment         *ActivityGetPayment         `json:"GetPayment,omitempty"`
	ActivityGetWallet          *ActivityGetWallet          `json:"GetWallet,omitempty"`
	ActivityListWallets        *ActivityListWallets        `json:"ListWallets,omitempty"`
	ActivityRevertTransaction  *ActivityRevertTransaction  `json:"RevertTransaction,omitempty"`
	ActivityVoidHold           *ActivityVoidHold           `json:"VoidHold,omitempty"`
	StripeTransferRequest      *StripeTransferRequest      `json:"StripeTransfer,omitempty"`
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityAddAccountMetadata() *ActivityAddAccountMetadata {
	if w == nil {
		return nil
	}
	return w.ActivityAddAccountMetadata
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityConfirmHold() *ActivityConfirmHold {
	if w == nil {
		return nil
	}
	return w.ActivityConfirmHold
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityCreateTransaction() *ActivityCreateTransaction {
	if w == nil {
		return nil
	}
	return w.ActivityCreateTransaction
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityCreditWallet() *ActivityCreditWallet {
	if w == nil {
		return nil
	}
	return w.ActivityCreditWallet
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityDebitWallet() *ActivityDebitWallet {
	if w == nil {
		return nil
	}
	return w.ActivityDebitWallet
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityGetAccount() *ActivityGetAccount {
	if w == nil {
		return nil
	}
	return w.ActivityGetAccount
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityGetPayment() *ActivityGetPayment {
	if w == nil {
		return nil
	}
	return w.ActivityGetPayment
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityGetWallet() *ActivityGetWallet {
	if w == nil {
		return nil
	}
	return w.ActivityGetWallet
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityListWallets() *ActivityListWallets {
	if w == nil {
		return nil
	}
	return w.ActivityListWallets
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityRevertTransaction() *ActivityRevertTransaction {
	if w == nil {
		return nil
	}
	return w.ActivityRevertTransaction
}

func (w *WorkflowInstanceHistoryStageInput) GetActivityVoidHold() *ActivityVoidHold {
	if w == nil {
		return nil
	}
	return w.ActivityVoidHold
}

func (w *WorkflowInstanceHistoryStageInput) GetStripeTransferRequest() *StripeTransferRequest {
	if w == nil {
		return nil
	}
	return w.StripeTransferRequest
}
