// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 45d78fcef441

package orchestration

type WorkflowInstanceHistoryStageOutput struct {
	AccountResponse            *AccountResponse           `json:"GetAccount,omitempty"`
	CreateTransactionResponse  *CreateTransactionResponse `json:"CreateTransaction,omitempty"`
	CreateTransactionResponse1 *CreateTransactionResponse `json:"RevertTransaction,omitempty"`
	DebitWalletResponse        *DebitWalletResponse       `json:"DebitWallet,omitempty"`
	GetWalletResponse          *GetWalletResponse         `json:"GetWallet,omitempty"`
	ListWalletsResponse        *ListWalletsResponse       `json:"ListWallets,omitempty"`
	PaymentResponse            *PaymentResponse           `json:"GetPayment,omitempty"`
}

func (w *WorkflowInstanceHistoryStageOutput) GetAccountResponse() *AccountResponse {
	if w == nil {
		return nil
	}
	return w.AccountResponse
}

func (w *WorkflowInstanceHistoryStageOutput) GetCreateTransactionResponse() *CreateTransactionResponse {
	if w == nil {
		return nil
	}
	return w.CreateTransactionResponse
}

func (w *WorkflowInstanceHistoryStageOutput) GetCreateTransactionResponse1() *CreateTransactionResponse {
	if w == nil {
		return nil
	}
	return w.CreateTransactionResponse1
}

func (w *WorkflowInstanceHistoryStageOutput) GetDebitWalletResponse() *DebitWalletResponse {
	if w == nil {
		return nil
	}
	return w.DebitWalletResponse
}

func (w *WorkflowInstanceHistoryStageOutput) GetGetWalletResponse() *GetWalletResponse {
	if w == nil {
		return nil
	}
	return w.GetWalletResponse
}

func (w *WorkflowInstanceHistoryStageOutput) GetListWalletsResponse() *ListWalletsResponse {
	if w == nil {
		return nil
	}
	return w.ListWalletsResponse
}

func (w *WorkflowInstanceHistoryStageOutput) GetPaymentResponse() *PaymentResponse {
	if w == nil {
		return nil
	}
	return w.PaymentResponse
}
