// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Cursor struct {
	Data     []PaymentsAccount `json:"data"`
	HasMore  bool              `json:"hasMore"`
	Next     *string           `json:"next,omitempty"`
	PageSize int64             `json:"pageSize"`
	Previous *string           `json:"previous,omitempty"`
}

func (c *Cursor) GetData() []PaymentsAccount {
	if c == nil {
		return []PaymentsAccount{}
	}
	return c.Data
}

func (c *Cursor) GetHasMore() bool {
	if c == nil {
		return false
	}
	return c.HasMore
}

func (c *Cursor) GetNext() *string {
	if c == nil {
		return nil
	}
	return c.Next
}

func (c *Cursor) GetPageSize() int64 {
	if c == nil {
		return 0
	}
	return c.PageSize
}

func (c *Cursor) GetPrevious() *string {
	if c == nil {
		return nil
	}
	return c.Previous
}

// AccountsCursor - OK
type AccountsCursor struct {
	Cursor Cursor `json:"cursor"`
}

func (a *AccountsCursor) GetCursor() Cursor {
	if a == nil {
		return Cursor{}
	}
	return a.Cursor
}
