// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccountMetadata struct {
}

type Account struct {
	Address  string           `json:"address"`
	Metadata *AccountMetadata `json:"metadata,omitempty"`
	Type     *string          `json:"type,omitempty"`
}
