// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityGetWallet struct {
	ID string `json:"id"`
}

func (a *ActivityGetWallet) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}
