// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityDebitWallet struct {
	Data *DebitWalletRequest `json:"data,omitempty"`
	ID   *string             `json:"id,omitempty"`
}

func (a *ActivityDebitWallet) GetData() *DebitWalletRequest {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *ActivityDebitWallet) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}
