// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type BankAccount struct {
	AccountID       *string                      `json:"accountID,omitempty"`
	AccountNumber   *string                      `json:"accountNumber,omitempty"`
	ConnectorID     *string                      `json:"connectorID,omitempty"`
	Country         string                       `json:"country"`
	CreatedAt       time.Time                    `json:"createdAt"`
	Iban            *string                      `json:"iban,omitempty"`
	ID              string                       `json:"id"`
	Metadata        map[string]string            `json:"metadata,omitempty"`
	Name            string                       `json:"name"`
	Provider        *string                      `json:"provider,omitempty"`
	RelatedAccounts []BankAccountRelatedAccounts `json:"relatedAccounts,omitempty"`
	SwiftBicCode    *string                      `json:"swiftBicCode,omitempty"`
}

func (b BankAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BankAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"country", "createdAt", "id", "name"}); err != nil {
		return err
	}
	return nil
}

func (b *BankAccount) GetAccountID() *string {
	if b == nil {
		return nil
	}
	return b.AccountID
}

func (b *BankAccount) GetAccountNumber() *string {
	if b == nil {
		return nil
	}
	return b.AccountNumber
}

func (b *BankAccount) GetConnectorID() *string {
	if b == nil {
		return nil
	}
	return b.ConnectorID
}

func (b *BankAccount) GetCountry() string {
	if b == nil {
		return ""
	}
	return b.Country
}

func (b *BankAccount) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BankAccount) GetIban() *string {
	if b == nil {
		return nil
	}
	return b.Iban
}

func (b *BankAccount) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BankAccount) GetMetadata() map[string]string {
	if b == nil {
		return nil
	}
	return b.Metadata
}

func (b *BankAccount) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BankAccount) GetProvider() *string {
	if b == nil {
		return nil
	}
	return b.Provider
}

func (b *BankAccount) GetRelatedAccounts() []BankAccountRelatedAccounts {
	if b == nil {
		return nil
	}
	return b.RelatedAccounts
}

func (b *BankAccount) GetSwiftBicCode() *string {
	if b == nil {
		return nil
	}
	return b.SwiftBicCode
}
