// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateSecretRequest struct {
	Metadata map[string]any `json:"metadata,omitempty"`
	Name     string         `json:"name"`
}

func (c *CreateSecretRequest) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateSecretRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
