// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateBalanceResponse struct {
	Data CreateBalanceRequest `json:"data"`
}

func (c *CreateBalanceResponse) GetData() CreateBalanceRequest {
	if c == nil {
		return CreateBalanceRequest{}
	}
	return c.Data
}
