// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateSecretResponse struct {
	Data *Secret `json:"data,omitempty"`
}

func (c *CreateSecretResponse) GetData() *Secret {
	if c == nil {
		return nil
	}
	return c.Data
}
