// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateClientRequest struct {
	Description            *string           `json:"description,omitempty"`
	Metadata               map[string]string `json:"metadata,omitempty"`
	Name                   string            `json:"name"`
	PostLogoutRedirectUris []string          `json:"postLogoutRedirectUris,omitempty"`
	Public                 *bool             `json:"public,omitempty"`
	RedirectUris           []string          `json:"redirectUris,omitempty"`
	Scopes                 []string          `json:"scopes,omitempty"`
	Trusted                *bool             `json:"trusted,omitempty"`
}

func (c *CreateClientRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateClientRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateClientRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateClientRequest) GetPostLogoutRedirectUris() []string {
	if c == nil {
		return nil
	}
	return c.PostLogoutRedirectUris
}

func (c *CreateClientRequest) GetPublic() *bool {
	if c == nil {
		return nil
	}
	return c.Public
}

func (c *CreateClientRequest) GetRedirectUris() []string {
	if c == nil {
		return nil
	}
	return c.RedirectUris
}

func (c *CreateClientRequest) GetScopes() []string {
	if c == nil {
		return nil
	}
	return c.Scopes
}

func (c *CreateClientRequest) GetTrusted() *bool {
	if c == nil {
		return nil
	}
	return c.Trusted
}
