// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type CreditWalletRequest struct {
	Amount Monetary `json:"amount"`
	// The balance to credit
	Balance *string `json:"balance,omitempty"`
	// Metadata associated with the wallet.
	Metadata  map[string]string `json:"metadata,omitempty"`
	Reference *string           `json:"reference,omitempty"`
	Sources   []Subject         `json:"sources,omitempty"`
	Timestamp *time.Time        `json:"timestamp,omitempty"`
}

func (c CreditWalletRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditWalletRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"amount"}); err != nil {
		return err
	}
	return nil
}

func (c *CreditWalletRequest) GetAmount() Monetary {
	if c == nil {
		return Monetary{}
	}
	return c.Amount
}

func (c *CreditWalletRequest) GetBalance() *string {
	if c == nil {
		return nil
	}
	return c.Balance
}

func (c *CreditWalletRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreditWalletRequest) GetReference() *string {
	if c == nil {
		return nil
	}
	return c.Reference
}

func (c *CreditWalletRequest) GetSources() []Subject {
	if c == nil {
		return nil
	}
	return c.Sources
}

func (c *CreditWalletRequest) GetTimestamp() *time.Time {
	if c == nil {
		return nil
	}
	return c.Timestamp
}
