// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetBalanceResponse struct {
	Data BalanceWithAssets `json:"data"`
}

func (g *GetBalanceResponse) GetData() BalanceWithAssets {
	if g == nil {
		return BalanceWithAssets{}
	}
	return g.Data
}
