// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetTransactionsResponseCursor struct {
	Data     []WalletsTransaction `json:"data"`
	HasMore  *bool                `json:"hasMore,omitempty"`
	Next     *string              `json:"next,omitempty"`
	PageSize int64                `json:"pageSize"`
	Previous *string              `json:"previous,omitempty"`
}

func (g *GetTransactionsResponseCursor) GetData() []WalletsTransaction {
	if g == nil {
		return []WalletsTransaction{}
	}
	return g.Data
}

func (g *GetTransactionsResponseCursor) GetHasMore() *bool {
	if g == nil {
		return nil
	}
	return g.HasMore
}

func (g *GetTransactionsResponseCursor) GetNext() *string {
	if g == nil {
		return nil
	}
	return g.Next
}

func (g *GetTransactionsResponseCursor) GetPageSize() int64 {
	if g == nil {
		return 0
	}
	return g.PageSize
}

func (g *GetTransactionsResponseCursor) GetPrevious() *string {
	if g == nil {
		return nil
	}
	return g.Previous
}

type GetTransactionsResponse struct {
	Cursor GetTransactionsResponseCursor `json:"cursor"`
}

func (g *GetTransactionsResponse) GetCursor() GetTransactionsResponseCursor {
	if g == nil {
		return GetTransactionsResponseCursor{}
	}
	return g.Cursor
}
