// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetWorkflowResponse struct {
	Data Workflow `json:"data"`
}

func (g *GetWorkflowResponse) GetData() Workflow {
	if g == nil {
		return Workflow{}
	}
	return g.Data
}
