// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetWorkflowInstanceHistoryResponse struct {
	Data []WorkflowInstanceHistory `json:"data"`
}

func (g *GetWorkflowInstanceHistoryResponse) GetData() []WorkflowInstanceHistory {
	if g == nil {
		return []WorkflowInstanceHistory{}
	}
	return g.Data
}
