// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetWalletResponse struct {
	Data WalletWithBalances `json:"data"`
}

func (g *GetWalletResponse) GetData() WalletWithBalances {
	if g == nil {
		return WalletWithBalances{}
	}
	return g.Data
}
