// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetWorkflowInstanceResponse struct {
	Data WorkflowInstance `json:"data"`
}

func (g *GetWorkflowInstanceResponse) GetData() WorkflowInstance {
	if g == nil {
		return WorkflowInstance{}
	}
	return g.Data
}
