// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListClientsResponse struct {
	Data []Client `json:"data,omitempty"`
}

func (l *ListClientsResponse) GetData() []Client {
	if l == nil {
		return nil
	}
	return l.Data
}
