// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type PaymentsAccountRaw struct {
}

type PaymentsAccount struct {
	AccountName  string    `json:"accountName"`
	ConnectorID  string    `json:"connectorID"`
	CreatedAt    time.Time `json:"createdAt"`
	DefaultAsset string    `json:"defaultAsset"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	DefaultCurrency string              `json:"defaultCurrency"`
	ID              string              `json:"id"`
	Metadata        map[string]string   `json:"metadata"`
	Pools           []string            `json:"pools,omitempty"`
	Provider        *string             `json:"provider,omitempty"`
	Raw             *PaymentsAccountRaw `json:"raw"`
	Reference       string              `json:"reference"`
	Type            AccountType         `json:"type"`
}

func (p PaymentsAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentsAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"accountName", "connectorID", "createdAt", "defaultAsset", "defaultCurrency", "id", "metadata", "raw", "reference", "type"}); err != nil {
		return err
	}
	return nil
}

func (p *PaymentsAccount) GetAccountName() string {
	if p == nil {
		return ""
	}
	return p.AccountName
}

func (p *PaymentsAccount) GetConnectorID() string {
	if p == nil {
		return ""
	}
	return p.ConnectorID
}

func (p *PaymentsAccount) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PaymentsAccount) GetDefaultAsset() string {
	if p == nil {
		return ""
	}
	return p.DefaultAsset
}

func (p *PaymentsAccount) GetDefaultCurrency() string {
	if p == nil {
		return ""
	}
	return p.DefaultCurrency
}

func (p *PaymentsAccount) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PaymentsAccount) GetMetadata() map[string]string {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PaymentsAccount) GetPools() []string {
	if p == nil {
		return nil
	}
	return p.Pools
}

func (p *PaymentsAccount) GetProvider() *string {
	if p == nil {
		return nil
	}
	return p.Provider
}

func (p *PaymentsAccount) GetRaw() *PaymentsAccountRaw {
	if p == nil {
		return nil
	}
	return p.Raw
}

func (p *PaymentsAccount) GetReference() string {
	if p == nil {
		return ""
	}
	return p.Reference
}

func (p *PaymentsAccount) GetType() AccountType {
	if p == nil {
		return AccountType("")
	}
	return p.Type
}
