// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PaymentsAccountResponse - OK
type PaymentsAccountResponse struct {
	Data PaymentsAccount `json:"data"`
}

func (p *PaymentsAccountResponse) GetData() PaymentsAccount {
	if p == nil {
		return PaymentsAccount{}
	}
	return p.Data
}
