// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PoolsCursorCursor struct {
	Data     []Pool  `json:"data"`
	HasMore  bool    `json:"hasMore"`
	Next     *string `json:"next,omitempty"`
	PageSize int64   `json:"pageSize"`
	Previous *string `json:"previous,omitempty"`
}

func (p *PoolsCursorCursor) GetData() []Pool {
	if p == nil {
		return []Pool{}
	}
	return p.Data
}

func (p *PoolsCursorCursor) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PoolsCursorCursor) GetNext() *string {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *PoolsCursorCursor) GetPageSize() int64 {
	if p == nil {
		return 0
	}
	return p.PageSize
}

func (p *PoolsCursorCursor) GetPrevious() *string {
	if p == nil {
		return nil
	}
	return p.Previous
}

// PoolsCursor - OK
type PoolsCursor struct {
	Cursor PoolsCursorCursor `json:"cursor"`
}

func (p *PoolsCursor) GetCursor() PoolsCursorCursor {
	if p == nil {
		return PoolsCursorCursor{}
	}
	return p.Cursor
}
