// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
)

type PoolBalance struct {
	Amount *big.Int `json:"amount"`
	Asset  string   `json:"asset"`
}

func (p PoolBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PoolBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"amount", "asset"}); err != nil {
		return err
	}
	return nil
}

func (p *PoolBalance) GetAmount() *big.Int {
	if p == nil {
		return big.NewInt(0)
	}
	return p.Amount
}

func (p *PoolBalance) GetAsset() string {
	if p == nil {
		return ""
	}
	return p.Asset
}
