// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Posting struct {
	Amount      int64  `json:"amount"`
	Asset       string `json:"asset"`
	Destination string `json:"destination"`
	Source      string `json:"source"`
}

func (o *Posting) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *Posting) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *Posting) GetDestination() string {
	if o == nil {
		return ""
	}
	return o.Destination
}

func (o *Posting) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}
