// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type QueryRaw struct {
}

type Query struct {
	After    []string  `json:"after,omitempty"`
	Cursor   *string   `json:"cursor,omitempty"`
	Ledgers  []string  `json:"ledgers,omitempty"`
	PageSize *int64    `json:"pageSize,omitempty"`
	Policy   *string   `json:"policy,omitempty"`
	Raw      *QueryRaw `json:"raw,omitempty"`
	Sort     *string   `json:"sort,omitempty"`
	Target   *string   `json:"target,omitempty"`
	Terms    []string  `json:"terms,omitempty"`
}

func (q *Query) GetAfter() []string {
	if q == nil {
		return nil
	}
	return q.After
}

func (q *Query) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *Query) GetLedgers() []string {
	if q == nil {
		return nil
	}
	return q.Ledgers
}

func (q *Query) GetPageSize() *int64 {
	if q == nil {
		return nil
	}
	return q.PageSize
}

func (q *Query) GetPolicy() *string {
	if q == nil {
		return nil
	}
	return q.Policy
}

func (q *Query) GetRaw() *QueryRaw {
	if q == nil {
		return nil
	}
	return q.Raw
}

func (q *Query) GetSort() *string {
	if q == nil {
		return nil
	}
	return q.Sort
}

func (q *Query) GetTarget() *string {
	if q == nil {
		return nil
	}
	return q.Target
}

func (q *Query) GetTerms() []string {
	if q == nil {
		return nil
	}
	return q.Terms
}
