// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReadClientResponse struct {
	Data *Client `json:"data,omitempty"`
}

func (r *ReadClientResponse) GetData() *Client {
	if r == nil {
		return nil
	}
	return r.Data
}
