// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReadUserResponse struct {
	Data *User `json:"data,omitempty"`
}

func (r *ReadUserResponse) GetData() *User {
	if r == nil {
		return nil
	}
	return r.Data
}
