// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ReadScopeResponse struct {
	Data *Scope `json:"data,omitempty"`
}

func (o *ReadScopeResponse) GetData() *Scope {
	if o == nil {
		return nil
	}
	return o.Data
}
