// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type Reconciliation struct {
	CreatedAt            time.Time           `json:"createdAt"`
	DriftBalances        map[string]*big.Int `json:"driftBalances"`
	Error                *string             `json:"error,omitempty"`
	ID                   string              `json:"id"`
	LedgerBalances       map[string]*big.Int `json:"ledgerBalances"`
	PaymentsBalances     map[string]*big.Int `json:"paymentsBalances"`
	PolicyID             string              `json:"policyID"`
	ReconciledAtLedger   time.Time           `json:"reconciledAtLedger"`
	ReconciledAtPayments time.Time           `json:"reconciledAtPayments"`
	Status               string              `json:"status"`
}

func (r Reconciliation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Reconciliation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"createdAt", "driftBalances", "id", "ledgerBalances", "paymentsBalances", "policyID", "reconciledAtLedger", "reconciledAtPayments", "status"}); err != nil {
		return err
	}
	return nil
}

func (r *Reconciliation) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *Reconciliation) GetDriftBalances() map[string]*big.Int {
	if r == nil {
		return map[string]*big.Int{}
	}
	return r.DriftBalances
}

func (r *Reconciliation) GetError() *string {
	if r == nil {
		return nil
	}
	return r.Error
}

func (r *Reconciliation) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *Reconciliation) GetLedgerBalances() map[string]*big.Int {
	if r == nil {
		return map[string]*big.Int{}
	}
	return r.LedgerBalances
}

func (r *Reconciliation) GetPaymentsBalances() map[string]*big.Int {
	if r == nil {
		return map[string]*big.Int{}
	}
	return r.PaymentsBalances
}

func (r *Reconciliation) GetPolicyID() string {
	if r == nil {
		return ""
	}
	return r.PolicyID
}

func (r *Reconciliation) GetReconciledAtLedger() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ReconciledAtLedger
}

func (r *Reconciliation) GetReconciledAtPayments() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.ReconciledAtPayments
}

func (r *Reconciliation) GetStatus() string {
	if r == nil {
		return ""
	}
	return r.Status
}
