// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RunWorkflowResponse struct {
	Data WorkflowInstance `json:"data"`
}

func (r *RunWorkflowResponse) GetData() WorkflowInstance {
	if r == nil {
		return WorkflowInstance{}
	}
	return r.Data
}
