// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ScriptResponse struct {
	Details      *string      `json:"details,omitempty"`
	ErrorCode    *ErrorsEnum  `json:"errorCode,omitempty"`
	ErrorMessage *string      `json:"errorMessage,omitempty"`
	Transaction  *Transaction `json:"transaction,omitempty"`
}

func (s *ScriptResponse) GetDetails() *string {
	if s == nil {
		return nil
	}
	return s.Details
}

func (s *ScriptResponse) GetErrorCode() *ErrorsEnum {
	if s == nil {
		return nil
	}
	return s.ErrorCode
}

func (s *ScriptResponse) GetErrorMessage() *string {
	if s == nil {
		return nil
	}
	return s.ErrorMessage
}

func (s *ScriptResponse) GetTransaction() *Transaction {
	if s == nil {
		return nil
	}
	return s.Transaction
}
