// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Secret struct {
	Clear      string         `json:"clear"`
	ID         string         `json:"id"`
	LastDigits string         `json:"lastDigits"`
	Metadata   map[string]any `json:"metadata,omitempty"`
	Name       string         `json:"name"`
}

func (s *Secret) GetClear() string {
	if s == nil {
		return ""
	}
	return s.Clear
}

func (s *Secret) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Secret) GetLastDigits() string {
	if s == nil {
		return ""
	}
	return s.LastDigits
}

func (s *Secret) GetMetadata() map[string]any {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *Secret) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}
