// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ServerInfo struct {
	Version string `json:"version"`
}

func (s *ServerInfo) GetVersion() string {
	if s == nil {
		return ""
	}
	return s.Version
}
