// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type StageSendDestinationAccount struct {
	ID     string  `json:"id"`
	Ledger *string `json:"ledger,omitempty"`
}

func (s StageSendDestinationAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StageSendDestinationAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (s *StageSendDestinationAccount) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StageSendDestinationAccount) GetLedger() *string {
	if s == nil {
		return nil
	}
	return s.Ledger
}
