// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type StageSendSource struct {
	Account *StageSendDestinationAccount `json:"account,omitempty"`
	Payment *StageSendSourcePayment      `json:"payment,omitempty"`
	Wallet  *StageSendDestinationWallet  `json:"wallet,omitempty"`
}

func (o *StageSendSource) GetAccount() *StageSendDestinationAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *StageSendSource) GetPayment() *StageSendSourcePayment {
	if o == nil {
		return nil
	}
	return o.Payment
}

func (o *StageSendSource) GetWallet() *StageSendDestinationWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}
