// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type StripeConfig struct {
	APIKey string `json:"apiKey"`
	Name   string `json:"name"`
	// Number of BalanceTransaction to fetch at each polling interval.
	//
	PageSize *int64 `default:"10" json:"pageSize"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from Stripe API.
	//
	PollingPeriod *string `default:"120s" json:"pollingPeriod"`
	Provider      *string `default:"Stripe" json:"provider"`
}

func (s StripeConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StripeConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"apiKey", "name"}); err != nil {
		return err
	}
	return nil
}

func (s *StripeConfig) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}

func (s *StripeConfig) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StripeConfig) GetPageSize() *int64 {
	if s == nil {
		return nil
	}
	return s.PageSize
}

func (s *StripeConfig) GetPollingPeriod() *string {
	if s == nil {
		return nil
	}
	return s.PollingPeriod
}

func (s *StripeConfig) GetProvider() *string {
	if s == nil {
		return nil
	}
	return s.Provider
}
