// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TransactionsCursorResponseCursor struct {
	Data     []Transaction `json:"data"`
	HasMore  bool          `json:"hasMore"`
	Next     *string       `json:"next,omitempty"`
	PageSize int64         `json:"pageSize"`
	Previous *string       `json:"previous,omitempty"`
}

func (t *TransactionsCursorResponseCursor) GetData() []Transaction {
	if t == nil {
		return []Transaction{}
	}
	return t.Data
}

func (t *TransactionsCursorResponseCursor) GetHasMore() bool {
	if t == nil {
		return false
	}
	return t.HasMore
}

func (t *TransactionsCursorResponseCursor) GetNext() *string {
	if t == nil {
		return nil
	}
	return t.Next
}

func (t *TransactionsCursorResponseCursor) GetPageSize() int64 {
	if t == nil {
		return 0
	}
	return t.PageSize
}

func (t *TransactionsCursorResponseCursor) GetPrevious() *string {
	if t == nil {
		return nil
	}
	return t.Previous
}

type TransactionsCursorResponse struct {
	Cursor TransactionsCursorResponseCursor `json:"cursor"`
}

func (t *TransactionsCursorResponse) GetCursor() TransactionsCursorResponseCursor {
	if t == nil {
		return TransactionsCursorResponseCursor{}
	}
	return t.Cursor
}
