// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TransferResponse - OK
type TransferResponse struct {
	ID *string `json:"id,omitempty"`
}

func (t *TransferResponse) GetID() *string {
	if t == nil {
		return nil
	}
	return t.ID
}
