// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TransferInitiationResponse - OK
type TransferInitiationResponse struct {
	Data TransferInitiation `json:"data"`
}

func (t *TransferInitiationResponse) GetData() TransferInitiation {
	if t == nil {
		return TransferInitiation{}
	}
	return t.Data
}
