// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TriggerData struct {
	Event      string         `json:"event"`
	Filter     *string        `json:"filter,omitempty"`
	Name       *string        `json:"name,omitempty"`
	Vars       map[string]any `json:"vars,omitempty"`
	Version    *string        `json:"version,omitempty"`
	WorkflowID string         `json:"workflowID"`
}

func (t *TriggerData) GetEvent() string {
	if t == nil {
		return ""
	}
	return t.Event
}

func (t *TriggerData) GetFilter() *string {
	if t == nil {
		return nil
	}
	return t.Filter
}

func (t *TriggerData) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TriggerData) GetVars() map[string]any {
	if t == nil {
		return nil
	}
	return t.Vars
}

func (t *TriggerData) GetVersion() *string {
	if t == nil {
		return nil
	}
	return t.Version
}

func (t *TriggerData) GetWorkflowID() string {
	if t == nil {
		return ""
	}
	return t.WorkflowID
}
