// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityGetWalletOutput struct {
	Data V2WalletWithBalances `json:"data"`
}

func (v *V2ActivityGetWalletOutput) GetData() V2WalletWithBalances {
	if v == nil {
		return V2WalletWithBalances{}
	}
	return v.Data
}
