// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2AccountsCursorResponseCursor struct {
	Data     []V2Account `json:"data"`
	HasMore  bool        `json:"hasMore"`
	Next     *string     `json:"next,omitempty"`
	PageSize int64       `json:"pageSize"`
	Previous *string     `json:"previous,omitempty"`
}

func (v *V2AccountsCursorResponseCursor) GetData() []V2Account {
	if v == nil {
		return []V2Account{}
	}
	return v.Data
}

func (v *V2AccountsCursorResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2AccountsCursorResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2AccountsCursorResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2AccountsCursorResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

type V2AccountsCursorResponse struct {
	Cursor V2AccountsCursorResponseCursor `json:"cursor"`
}

func (v *V2AccountsCursorResponse) GetCursor() V2AccountsCursorResponseCursor {
	if v == nil {
		return V2AccountsCursorResponseCursor{}
	}
	return v.Cursor
}
