// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2Account struct {
	Address          string              `json:"address"`
	EffectiveVolumes map[string]V2Volume `json:"effectiveVolumes,omitempty"`
	Metadata         map[string]string   `json:"metadata"`
	Volumes          map[string]V2Volume `json:"volumes,omitempty"`
}

func (v *V2Account) GetAddress() string {
	if v == nil {
		return ""
	}
	return v.Address
}

func (v *V2Account) GetEffectiveVolumes() map[string]V2Volume {
	if v == nil {
		return nil
	}
	return v.EffectiveVolumes
}

func (v *V2Account) GetMetadata() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.Metadata
}

func (v *V2Account) GetVolumes() map[string]V2Volume {
	if v == nil {
		return nil
	}
	return v.Volumes
}
