// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityGetWallet struct {
	ID string `json:"id"`
}

func (v *V2ActivityGetWallet) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}
