// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityCreateTransactionOutput struct {
	Data []OrchestrationV2Transaction `json:"data"`
}

func (v *V2ActivityCreateTransactionOutput) GetData() []OrchestrationV2Transaction {
	if v == nil {
		return []OrchestrationV2Transaction{}
	}
	return v.Data
}
