// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityDebitWallet struct {
	Data *V2DebitWalletRequest `json:"data,omitempty"`
	ID   *string               `json:"id,omitempty"`
}

func (v *V2ActivityDebitWallet) GetData() *V2DebitWalletRequest {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V2ActivityDebitWallet) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}
