// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2BulkElementResultErrorSchemas struct {
	ErrorCode        string  `json:"errorCode"`
	ErrorDescription string  `json:"errorDescription"`
	ErrorDetails     *string `json:"errorDetails,omitempty"`
	LogID            int64   `json:"logID"`
	ResponseType     string  `json:"responseType"`
}

func (v V2BulkElementResultErrorSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultErrorSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"errorCode", "errorDescription", "logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultErrorSchemas) GetErrorCode() string {
	if v == nil {
		return ""
	}
	return v.ErrorCode
}

func (v *V2BulkElementResultErrorSchemas) GetErrorDescription() string {
	if v == nil {
		return ""
	}
	return v.ErrorDescription
}

func (v *V2BulkElementResultErrorSchemas) GetErrorDetails() *string {
	if v == nil {
		return nil
	}
	return v.ErrorDetails
}

func (v *V2BulkElementResultErrorSchemas) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultErrorSchemas) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

type V2BulkElementResultDeleteMetadataSchemas struct {
	LogID        int64  `json:"logID"`
	ResponseType string `json:"responseType"`
}

func (v V2BulkElementResultDeleteMetadataSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultDeleteMetadataSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultDeleteMetadataSchemas) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultDeleteMetadataSchemas) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

type V2BulkElementResultRevertTransactionSchemas struct {
	Data         V2Transaction `json:"data"`
	LogID        int64         `json:"logID"`
	ResponseType string        `json:"responseType"`
}

func (v V2BulkElementResultRevertTransactionSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultRevertTransactionSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"data", "logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultRevertTransactionSchemas) GetData() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.Data
}

func (v *V2BulkElementResultRevertTransactionSchemas) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultRevertTransactionSchemas) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

type Schemas struct {
	LogID        int64  `json:"logID"`
	ResponseType string `json:"responseType"`
}

func (s Schemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Schemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (s *Schemas) GetLogID() int64 {
	if s == nil {
		return 0
	}
	return s.LogID
}

func (s *Schemas) GetResponseType() string {
	if s == nil {
		return ""
	}
	return s.ResponseType
}

type V2BulkElementResultCreateTransactionSchemas struct {
	Data         V2Transaction `json:"data"`
	LogID        int64         `json:"logID"`
	ResponseType string        `json:"responseType"`
}

func (v V2BulkElementResultCreateTransactionSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultCreateTransactionSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"data", "logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultCreateTransactionSchemas) GetData() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.Data
}

func (v *V2BulkElementResultCreateTransactionSchemas) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultCreateTransactionSchemas) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

type V2BulkElementResultType string

const (
	V2BulkElementResultTypeAddMetadata       V2BulkElementResultType = "ADD_METADATA"
	V2BulkElementResultTypeCreateTransaction V2BulkElementResultType = "CREATE_TRANSACTION"
	V2BulkElementResultTypeDeleteMetadata    V2BulkElementResultType = "DELETE_METADATA"
	V2BulkElementResultTypeError             V2BulkElementResultType = "ERROR"
	V2BulkElementResultTypeRevertTransaction V2BulkElementResultType = "REVERT_TRANSACTION"
)

type V2BulkElementResult struct {
	V2BulkElementResultCreateTransactionSchemas *V2BulkElementResultCreateTransactionSchemas `queryParam:"inline,name=V2BulkElementResult"`
	Schemas                                     *Schemas                                     `queryParam:"inline,name=V2BulkElementResult"`
	V2BulkElementResultRevertTransactionSchemas *V2BulkElementResultRevertTransactionSchemas `queryParam:"inline,name=V2BulkElementResult"`
	V2BulkElementResultDeleteMetadataSchemas    *V2BulkElementResultDeleteMetadataSchemas    `queryParam:"inline,name=V2BulkElementResult"`
	V2BulkElementResultErrorSchemas             *V2BulkElementResultErrorSchemas             `queryParam:"inline,name=V2BulkElementResult"`

	Type V2BulkElementResultType
}

func CreateV2BulkElementResultAddMetadata(addMetadata Schemas) V2BulkElementResult {
	typ := V2BulkElementResultTypeAddMetadata

	typStr := string(typ)
	addMetadata.ResponseType = typStr

	return V2BulkElementResult{
		Schemas: &addMetadata,
		Type:    typ,
	}
}

func CreateV2BulkElementResultCreateTransaction(createTransaction V2BulkElementResultCreateTransactionSchemas) V2BulkElementResult {
	typ := V2BulkElementResultTypeCreateTransaction

	typStr := string(typ)
	createTransaction.ResponseType = typStr

	return V2BulkElementResult{
		V2BulkElementResultCreateTransactionSchemas: &createTransaction,
		Type: typ,
	}
}

func CreateV2BulkElementResultDeleteMetadata(deleteMetadata V2BulkElementResultDeleteMetadataSchemas) V2BulkElementResult {
	typ := V2BulkElementResultTypeDeleteMetadata

	typStr := string(typ)
	deleteMetadata.ResponseType = typStr

	return V2BulkElementResult{
		V2BulkElementResultDeleteMetadataSchemas: &deleteMetadata,
		Type:                                     typ,
	}
}

func CreateV2BulkElementResultError(errorT V2BulkElementResultErrorSchemas) V2BulkElementResult {
	typ := V2BulkElementResultTypeError

	typStr := string(typ)
	errorT.ResponseType = typStr

	return V2BulkElementResult{
		V2BulkElementResultErrorSchemas: &errorT,
		Type:                            typ,
	}
}

func CreateV2BulkElementResultRevertTransaction(revertTransaction V2BulkElementResultRevertTransactionSchemas) V2BulkElementResult {
	typ := V2BulkElementResultTypeRevertTransaction

	typStr := string(typ)
	revertTransaction.ResponseType = typStr

	return V2BulkElementResult{
		V2BulkElementResultRevertTransactionSchemas: &revertTransaction,
		Type: typ,
	}
}

func (u *V2BulkElementResult) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ResponseType string `json:"responseType"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ResponseType {
	case "ADD_METADATA":
		schemas := new(Schemas)
		if err := utils.UnmarshalJSON(data, &schemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ResponseType == ADD_METADATA) type Schemas within V2BulkElementResult: %w", string(data), err)
		}

		u.Schemas = schemas
		u.Type = V2BulkElementResultTypeAddMetadata
		return nil
	case "CREATE_TRANSACTION":
		v2BulkElementResultCreateTransactionSchemas := new(V2BulkElementResultCreateTransactionSchemas)
		if err := utils.UnmarshalJSON(data, &v2BulkElementResultCreateTransactionSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ResponseType == CREATE_TRANSACTION) type V2BulkElementResultCreateTransactionSchemas within V2BulkElementResult: %w", string(data), err)
		}

		u.V2BulkElementResultCreateTransactionSchemas = v2BulkElementResultCreateTransactionSchemas
		u.Type = V2BulkElementResultTypeCreateTransaction
		return nil
	case "DELETE_METADATA":
		v2BulkElementResultDeleteMetadataSchemas := new(V2BulkElementResultDeleteMetadataSchemas)
		if err := utils.UnmarshalJSON(data, &v2BulkElementResultDeleteMetadataSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ResponseType == DELETE_METADATA) type V2BulkElementResultDeleteMetadataSchemas within V2BulkElementResult: %w", string(data), err)
		}

		u.V2BulkElementResultDeleteMetadataSchemas = v2BulkElementResultDeleteMetadataSchemas
		u.Type = V2BulkElementResultTypeDeleteMetadata
		return nil
	case "ERROR":
		v2BulkElementResultErrorSchemas := new(V2BulkElementResultErrorSchemas)
		if err := utils.UnmarshalJSON(data, &v2BulkElementResultErrorSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ResponseType == ERROR) type V2BulkElementResultErrorSchemas within V2BulkElementResult: %w", string(data), err)
		}

		u.V2BulkElementResultErrorSchemas = v2BulkElementResultErrorSchemas
		u.Type = V2BulkElementResultTypeError
		return nil
	case "REVERT_TRANSACTION":
		v2BulkElementResultRevertTransactionSchemas := new(V2BulkElementResultRevertTransactionSchemas)
		if err := utils.UnmarshalJSON(data, &v2BulkElementResultRevertTransactionSchemas, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ResponseType == REVERT_TRANSACTION) type V2BulkElementResultRevertTransactionSchemas within V2BulkElementResult: %w", string(data), err)
		}

		u.V2BulkElementResultRevertTransactionSchemas = v2BulkElementResultRevertTransactionSchemas
		u.Type = V2BulkElementResultTypeRevertTransaction
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2BulkElementResult", string(data))
}

func (u V2BulkElementResult) MarshalJSON() ([]byte, error) {
	if u.V2BulkElementResultCreateTransactionSchemas != nil {
		return utils.MarshalJSON(u.V2BulkElementResultCreateTransactionSchemas, "", true)
	}

	if u.Schemas != nil {
		return utils.MarshalJSON(u.Schemas, "", true)
	}

	if u.V2BulkElementResultRevertTransactionSchemas != nil {
		return utils.MarshalJSON(u.V2BulkElementResultRevertTransactionSchemas, "", true)
	}

	if u.V2BulkElementResultDeleteMetadataSchemas != nil {
		return utils.MarshalJSON(u.V2BulkElementResultDeleteMetadataSchemas, "", true)
	}

	if u.V2BulkElementResultErrorSchemas != nil {
		return utils.MarshalJSON(u.V2BulkElementResultErrorSchemas, "", true)
	}

	return nil, errors.New("could not marshal union type V2BulkElementResult: all fields are null")
}
