// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
)

type V2BulkElementRevertTransactionData struct {
	AtEffectiveDate *bool    `json:"atEffectiveDate,omitempty"`
	Force           *bool    `json:"force,omitempty"`
	ID              *big.Int `json:"id"`
}

func (v V2BulkElementRevertTransactionData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementRevertTransactionData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementRevertTransactionData) GetAtEffectiveDate() *bool {
	if v == nil {
		return nil
	}
	return v.AtEffectiveDate
}

func (v *V2BulkElementRevertTransactionData) GetForce() *bool {
	if v == nil {
		return nil
	}
	return v.Force
}

func (v *V2BulkElementRevertTransactionData) GetID() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.ID
}

type V2BulkElementRevertTransaction struct {
	Action string                              `json:"action"`
	Data   *V2BulkElementRevertTransactionData `json:"data,omitempty"`
	Ik     *string                             `json:"ik,omitempty"`
}

func (v V2BulkElementRevertTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementRevertTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"action"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementRevertTransaction) GetAction() string {
	if v == nil {
		return ""
	}
	return v.Action
}

func (v *V2BulkElementRevertTransaction) GetData() *V2BulkElementRevertTransactionData {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V2BulkElementRevertTransaction) GetIk() *string {
	if v == nil {
		return nil
	}
	return v.Ik
}
