// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2GetWorkflowInstanceResponse struct {
	Data V2WorkflowInstance `json:"data"`
}

func (v *V2GetWorkflowInstanceResponse) GetData() V2WorkflowInstance {
	if v == nil {
		return V2WorkflowInstance{}
	}
	return v.Data
}
