// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2GetWorkflowResponse struct {
	Data V2Workflow `json:"data"`
}

func (v *V2GetWorkflowResponse) GetData() V2Workflow {
	if v == nil {
		return V2Workflow{}
	}
	return v.Data
}
