// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2GetTransactionResponse struct {
	Data V2Transaction `json:"data"`
}

func (v *V2GetTransactionResponse) GetData() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.Data
}
