// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2LedgerListResponseCursor struct {
	Data     []V2Ledger `json:"data"`
	HasMore  bool       `json:"hasMore"`
	Next     *string    `json:"next,omitempty"`
	PageSize int64      `json:"pageSize"`
	Previous *string    `json:"previous,omitempty"`
}

func (v *V2LedgerListResponseCursor) GetData() []V2Ledger {
	if v == nil {
		return []V2Ledger{}
	}
	return v.Data
}

func (v *V2LedgerListResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2LedgerListResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2LedgerListResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2LedgerListResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

type V2LedgerListResponse struct {
	Cursor V2LedgerListResponseCursor `json:"cursor"`
}

func (v *V2LedgerListResponse) GetCursor() V2LedgerListResponseCursor {
	if v == nil {
		return V2LedgerListResponseCursor{}
	}
	return v.Cursor
}
