// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ListTriggersResponseCursor struct {
	Data     []V2Trigger `json:"data"`
	HasMore  bool        `json:"hasMore"`
	Next     *string     `json:"next,omitempty"`
	PageSize int64       `json:"pageSize"`
	Previous *string     `json:"previous,omitempty"`
}

func (v *V2ListTriggersResponseCursor) GetData() []V2Trigger {
	if v == nil {
		return []V2Trigger{}
	}
	return v.Data
}

func (v *V2ListTriggersResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2ListTriggersResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2ListTriggersResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2ListTriggersResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

type V2ListTriggersResponse struct {
	Cursor V2ListTriggersResponseCursor `json:"cursor"`
}

func (v *V2ListTriggersResponse) GetCursor() V2ListTriggersResponseCursor {
	if v == nil {
		return V2ListTriggersResponseCursor{}
	}
	return v.Cursor
}
