// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ReadTriggerResponse struct {
	Data V2Trigger `json:"data"`
}

func (v *V2ReadTriggerResponse) GetData() V2Trigger {
	if v == nil {
		return V2Trigger{}
	}
	return v.Data
}
