// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2SchemasCursor struct {
	Data     []V2Schema `json:"data"`
	HasMore  bool       `json:"hasMore"`
	Next     *string    `json:"next,omitempty"`
	PageSize int64      `json:"pageSize"`
	Previous *string    `json:"previous,omitempty"`
}

func (v *V2SchemasCursor) GetData() []V2Schema {
	if v == nil {
		return []V2Schema{}
	}
	return v.Data
}

func (v *V2SchemasCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2SchemasCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2SchemasCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2SchemasCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

// #region class-body-v2schemascursor
// #endregion class-body-v2schemascursor
