// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2StageSendSource struct {
	Account *V2StageSendDestinationAccount `json:"account,omitempty"`
	Payment *V2StageSendSourcePayment      `json:"payment,omitempty"`
	Wallet  *V2StageSendDestinationWallet  `json:"wallet,omitempty"`
}

func (o *V2StageSendSource) GetAccount() *V2StageSendDestinationAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *V2StageSendSource) GetPayment() *V2StageSendSourcePayment {
	if o == nil {
		return nil
	}
	return o.Payment
}

func (o *V2StageSendSource) GetWallet() *V2StageSendDestinationWallet {
	if o == nil {
		return nil
	}
	return o.Wallet
}
