// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2VolumesWithBalanceCursorResponseCursor struct {
	Data     []V2VolumesWithBalance `json:"data"`
	HasMore  bool                   `json:"hasMore"`
	Next     *string                `json:"next,omitempty"`
	PageSize int64                  `json:"pageSize"`
	Previous *string                `json:"previous,omitempty"`
}

func (v V2VolumesWithBalanceCursorResponseCursor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2VolumesWithBalanceCursorResponseCursor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"data", "hasMore", "pageSize"}); err != nil {
		return err
	}
	return nil
}

func (v *V2VolumesWithBalanceCursorResponseCursor) GetData() []V2VolumesWithBalance {
	if v == nil {
		return []V2VolumesWithBalance{}
	}
	return v.Data
}

func (v *V2VolumesWithBalanceCursorResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2VolumesWithBalanceCursorResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2VolumesWithBalanceCursorResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2VolumesWithBalanceCursorResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

// #region class-body-v2volumeswithbalancecursorresponsecursor
// #endregion class-body-v2volumeswithbalancecursorresponsecursor

type V2VolumesWithBalanceCursorResponseResource string

const (
	V2VolumesWithBalanceCursorResponseResourceVolumes V2VolumesWithBalanceCursorResponseResource = "volumes"
)

func (e V2VolumesWithBalanceCursorResponseResource) ToPointer() *V2VolumesWithBalanceCursorResponseResource {
	return &e
}
func (e *V2VolumesWithBalanceCursorResponseResource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "volumes":
		*e = V2VolumesWithBalanceCursorResponseResource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2VolumesWithBalanceCursorResponseResource: %v", v)
	}
}

type V2VolumesWithBalanceCursorResponse struct {
	Cursor   V2VolumesWithBalanceCursorResponseCursor    `json:"cursor"`
	Resource *V2VolumesWithBalanceCursorResponseResource `json:"resource,omitempty"`
}

func (v V2VolumesWithBalanceCursorResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2VolumesWithBalanceCursorResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"cursor"}); err != nil {
		return err
	}
	return nil
}

func (v *V2VolumesWithBalanceCursorResponse) GetCursor() V2VolumesWithBalanceCursorResponseCursor {
	if v == nil {
		return V2VolumesWithBalanceCursorResponseCursor{}
	}
	return v.Cursor
}

func (v *V2VolumesWithBalanceCursorResponse) GetResource() *V2VolumesWithBalanceCursorResponseResource {
	if v == nil {
		return nil
	}
	return v.Resource
}

// #region class-body-v2volumeswithbalancecursorresponse
// #endregion class-body-v2volumeswithbalancecursorresponse
