// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2WalletSubject struct {
	Balance    *string `json:"balance,omitempty"`
	Identifier string  `json:"identifier"`
	Type       string  `json:"type"`
}

func (v V2WalletSubject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2WalletSubject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"identifier", "type"}); err != nil {
		return err
	}
	return nil
}

func (v *V2WalletSubject) GetBalance() *string {
	if v == nil {
		return nil
	}
	return v.Balance
}

func (v *V2WalletSubject) GetIdentifier() string {
	if v == nil {
		return ""
	}
	return v.Identifier
}

func (v *V2WalletSubject) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}
