// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type V2WorkflowInstanceHistoryStage struct {
	Attempt       int64                                 `json:"attempt"`
	Error         *string                               `json:"error,omitempty"`
	Input         V2WorkflowInstanceHistoryStageInput   `json:"input"`
	LastFailure   *string                               `json:"lastFailure,omitempty"`
	Name          string                                `json:"name"`
	NextExecution *time.Time                            `json:"nextExecution,omitempty"`
	Output        *V2WorkflowInstanceHistoryStageOutput `json:"output,omitempty"`
	StartedAt     time.Time                             `json:"startedAt"`
	Terminated    bool                                  `json:"terminated"`
	TerminatedAt  *time.Time                            `json:"terminatedAt,omitempty"`
}

func (v V2WorkflowInstanceHistoryStage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2WorkflowInstanceHistoryStage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"attempt", "input", "name", "startedAt", "terminated"}); err != nil {
		return err
	}
	return nil
}

func (v *V2WorkflowInstanceHistoryStage) GetAttempt() int64 {
	if v == nil {
		return 0
	}
	return v.Attempt
}

func (v *V2WorkflowInstanceHistoryStage) GetError() *string {
	if v == nil {
		return nil
	}
	return v.Error
}

func (v *V2WorkflowInstanceHistoryStage) GetInput() V2WorkflowInstanceHistoryStageInput {
	if v == nil {
		return V2WorkflowInstanceHistoryStageInput{}
	}
	return v.Input
}

func (v *V2WorkflowInstanceHistoryStage) GetLastFailure() *string {
	if v == nil {
		return nil
	}
	return v.LastFailure
}

func (v *V2WorkflowInstanceHistoryStage) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V2WorkflowInstanceHistoryStage) GetNextExecution() *time.Time {
	if v == nil {
		return nil
	}
	return v.NextExecution
}

func (v *V2WorkflowInstanceHistoryStage) GetOutput() *V2WorkflowInstanceHistoryStageOutput {
	if v == nil {
		return nil
	}
	return v.Output
}

func (v *V2WorkflowInstanceHistoryStage) GetStartedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartedAt
}

func (v *V2WorkflowInstanceHistoryStage) GetTerminated() bool {
	if v == nil {
		return false
	}
	return v.Terminated
}

func (v *V2WorkflowInstanceHistoryStage) GetTerminatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.TerminatedAt
}
