// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2WorkflowInstanceHistoryStageInput struct {
	AddAccountMetadata *V2ActivityAddAccountMetadata `json:"AddAccountMetadata,omitempty"`
	ConfirmHold        *V2ActivityConfirmHold        `json:"ConfirmHold,omitempty"`
	CreateTransaction  *V2ActivityCreateTransaction  `json:"CreateTransaction,omitempty"`
	CreditWallet       *V2ActivityCreditWallet       `json:"CreditWallet,omitempty"`
	DebitWallet        *V2ActivityDebitWallet        `json:"DebitWallet,omitempty"`
	GetAccount         *V2ActivityGetAccount         `json:"GetAccount,omitempty"`
	GetPayment         *V2ActivityGetPayment         `json:"GetPayment,omitempty"`
	GetWallet          *V2ActivityGetWallet          `json:"GetWallet,omitempty"`
	ListWallets        *V2ActivityListWallets        `json:"ListWallets,omitempty"`
	StripeTransfer     *V2ActivityStripeTransfer     `json:"StripeTransfer,omitempty"`
	VoidHold           *V2ActivityVoidHold           `json:"VoidHold,omitempty"`
}

func (v *V2WorkflowInstanceHistoryStageInput) GetAddAccountMetadata() *V2ActivityAddAccountMetadata {
	if v == nil {
		return nil
	}
	return v.AddAccountMetadata
}

func (v *V2WorkflowInstanceHistoryStageInput) GetConfirmHold() *V2ActivityConfirmHold {
	if v == nil {
		return nil
	}
	return v.ConfirmHold
}

func (v *V2WorkflowInstanceHistoryStageInput) GetCreateTransaction() *V2ActivityCreateTransaction {
	if v == nil {
		return nil
	}
	return v.CreateTransaction
}

func (v *V2WorkflowInstanceHistoryStageInput) GetCreditWallet() *V2ActivityCreditWallet {
	if v == nil {
		return nil
	}
	return v.CreditWallet
}

func (v *V2WorkflowInstanceHistoryStageInput) GetDebitWallet() *V2ActivityDebitWallet {
	if v == nil {
		return nil
	}
	return v.DebitWallet
}

func (v *V2WorkflowInstanceHistoryStageInput) GetGetAccount() *V2ActivityGetAccount {
	if v == nil {
		return nil
	}
	return v.GetAccount
}

func (v *V2WorkflowInstanceHistoryStageInput) GetGetPayment() *V2ActivityGetPayment {
	if v == nil {
		return nil
	}
	return v.GetPayment
}

func (v *V2WorkflowInstanceHistoryStageInput) GetGetWallet() *V2ActivityGetWallet {
	if v == nil {
		return nil
	}
	return v.GetWallet
}

func (v *V2WorkflowInstanceHistoryStageInput) GetListWallets() *V2ActivityListWallets {
	if v == nil {
		return nil
	}
	return v.ListWallets
}

func (v *V2WorkflowInstanceHistoryStageInput) GetStripeTransfer() *V2ActivityStripeTransfer {
	if v == nil {
		return nil
	}
	return v.StripeTransfer
}

func (v *V2WorkflowInstanceHistoryStageInput) GetVoidHold() *V2ActivityVoidHold {
	if v == nil {
		return nil
	}
	return v.VoidHold
}
