// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3Address struct {
	City         *string `json:"city,omitempty"`
	Country      *string `json:"country,omitempty"`
	PostalCode   *string `json:"postalCode,omitempty"`
	Region       *string `json:"region,omitempty"`
	StreetName   *string `json:"streetName,omitempty"`
	StreetNumber *string `json:"streetNumber,omitempty"`
}

func (v *V3Address) GetCity() *string {
	if v == nil {
		return nil
	}
	return v.City
}

func (v *V3Address) GetCountry() *string {
	if v == nil {
		return nil
	}
	return v.Country
}

func (v *V3Address) GetPostalCode() *string {
	if v == nil {
		return nil
	}
	return v.PostalCode
}

func (v *V3Address) GetRegion() *string {
	if v == nil {
		return nil
	}
	return v.Region
}

func (v *V3Address) GetStreetName() *string {
	if v == nil {
		return nil
	}
	return v.StreetName
}

func (v *V3Address) GetStreetNumber() *string {
	if v == nil {
		return nil
	}
	return v.StreetNumber
}
