// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3AddressRequest struct {
	City         *string `json:"city,omitempty"`
	Country      *string `json:"country,omitempty"`
	PostalCode   *string `json:"postalCode,omitempty"`
	Region       *string `json:"region,omitempty"`
	StreetName   *string `json:"streetName,omitempty"`
	StreetNumber *string `json:"streetNumber,omitempty"`
}

func (o *V3AddressRequest) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *V3AddressRequest) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *V3AddressRequest) GetPostalCode() *string {
	if o == nil {
		return nil
	}
	return o.PostalCode
}

func (o *V3AddressRequest) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *V3AddressRequest) GetStreetName() *string {
	if o == nil {
		return nil
	}
	return o.StreetName
}

func (o *V3AddressRequest) GetStreetNumber() *string {
	if o == nil {
		return nil
	}
	return o.StreetNumber
}
