// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3BalancesCursorResponseCursor struct {
	Data     []V3Balance `json:"data"`
	HasMore  bool        `json:"hasMore"`
	Next     *string     `json:"next,omitempty"`
	PageSize int64       `json:"pageSize"`
	Previous *string     `json:"previous,omitempty"`
}

func (v *V3BalancesCursorResponseCursor) GetData() []V3Balance {
	if v == nil {
		return []V3Balance{}
	}
	return v.Data
}

func (v *V3BalancesCursorResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V3BalancesCursorResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V3BalancesCursorResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V3BalancesCursorResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

type V3BalancesCursorResponse struct {
	Cursor V3BalancesCursorResponseCursor `json:"cursor"`
}

func (v *V3BalancesCursorResponse) GetCursor() V3BalancesCursorResponseCursor {
	if v == nil {
		return V3BalancesCursorResponseCursor{}
	}
	return v.Cursor
}
