// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3ConfigInfoResponse struct {
	Debug   *bool  `json:"debug,omitempty"`
	Version string `json:"version"`
}

func (o *V3ConfigInfoResponse) GetDebug() *bool {
	if o == nil {
		return nil
	}
	return o.Debug
}

func (o *V3ConfigInfoResponse) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}
