// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3ContactDetailsRequest struct {
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

func (v *V3ContactDetailsRequest) GetEmail() *string {
	if v == nil {
		return nil
	}
	return v.Email
}

func (v *V3ContactDetailsRequest) GetPhoneNumber() *string {
	if v == nil {
		return nil
	}
	return v.PhoneNumber
}
