// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type V3CreatePaymentRequest struct {
	Adjustments          []V3CreatePaymentAdjustmentRequest `json:"adjustments,omitempty"`
	Amount               *big.Int                           `json:"amount"`
	Asset                string                             `json:"asset"`
	ConnectorID          string                             `json:"connectorID"`
	CreatedAt            time.Time                          `json:"createdAt"`
	DestinationAccountID *string                            `json:"destinationAccountID,omitempty"`
	InitialAmount        *big.Int                           `json:"initialAmount"`
	Metadata             map[string]string                  `json:"metadata,omitempty"`
	Reference            string                             `json:"reference"`
	Scheme               string                             `json:"scheme"`
	SourceAccountID      *string                            `json:"sourceAccountID,omitempty"`
	Type                 V3PaymentTypeEnum                  `json:"type"`
}

func (v V3CreatePaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3CreatePaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"amount", "asset", "connectorID", "createdAt", "initialAmount", "reference", "scheme", "type"}); err != nil {
		return err
	}
	return nil
}

func (v *V3CreatePaymentRequest) GetAdjustments() []V3CreatePaymentAdjustmentRequest {
	if v == nil {
		return nil
	}
	return v.Adjustments
}

func (v *V3CreatePaymentRequest) GetAmount() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.Amount
}

func (v *V3CreatePaymentRequest) GetAsset() string {
	if v == nil {
		return ""
	}
	return v.Asset
}

func (v *V3CreatePaymentRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3CreatePaymentRequest) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3CreatePaymentRequest) GetDestinationAccountID() *string {
	if v == nil {
		return nil
	}
	return v.DestinationAccountID
}

func (v *V3CreatePaymentRequest) GetInitialAmount() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.InitialAmount
}

func (v *V3CreatePaymentRequest) GetMetadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.Metadata
}

func (v *V3CreatePaymentRequest) GetReference() string {
	if v == nil {
		return ""
	}
	return v.Reference
}

func (v *V3CreatePaymentRequest) GetScheme() string {
	if v == nil {
		return ""
	}
	return v.Scheme
}

func (v *V3CreatePaymentRequest) GetSourceAccountID() *string {
	if v == nil {
		return nil
	}
	return v.SourceAccountID
}

func (v *V3CreatePaymentRequest) GetType() V3PaymentTypeEnum {
	if v == nil {
		return V3PaymentTypeEnum("")
	}
	return v.Type
}
