// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3GetPaymentResponse struct {
	Data V3Payment `json:"data"`
}

func (v *V3GetPaymentResponse) GetData() V3Payment {
	if v == nil {
		return V3Payment{}
	}
	return v.Data
}
