// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3GetPaymentInitiationResponse struct {
	Data V3PaymentInitiation `json:"data"`
}

func (v *V3GetPaymentInitiationResponse) GetData() V3PaymentInitiation {
	if v == nil {
		return V3PaymentInitiation{}
	}
	return v.Data
}
