// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type V3InitiatePaymentRequest struct {
	Amount               *big.Int                    `json:"amount"`
	Asset                string                      `json:"asset"`
	ConnectorID          string                      `json:"connectorID"`
	Description          string                      `json:"description"`
	DestinationAccountID *string                     `json:"destinationAccountID,omitempty"`
	Metadata             map[string]string           `json:"metadata,omitempty"`
	Reference            string                      `json:"reference"`
	ScheduledAt          time.Time                   `json:"scheduledAt"`
	SourceAccountID      *string                     `json:"sourceAccountID,omitempty"`
	Type                 V3PaymentInitiationTypeEnum `json:"type"`
}

func (v V3InitiatePaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3InitiatePaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"amount", "asset", "connectorID", "description", "reference", "scheduledAt", "type"}); err != nil {
		return err
	}
	return nil
}

func (v *V3InitiatePaymentRequest) GetAmount() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.Amount
}

func (v *V3InitiatePaymentRequest) GetAsset() string {
	if v == nil {
		return ""
	}
	return v.Asset
}

func (v *V3InitiatePaymentRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3InitiatePaymentRequest) GetDescription() string {
	if v == nil {
		return ""
	}
	return v.Description
}

func (v *V3InitiatePaymentRequest) GetDestinationAccountID() *string {
	if v == nil {
		return nil
	}
	return v.DestinationAccountID
}

func (v *V3InitiatePaymentRequest) GetMetadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.Metadata
}

func (v *V3InitiatePaymentRequest) GetReference() string {
	if v == nil {
		return ""
	}
	return v.Reference
}

func (v *V3InitiatePaymentRequest) GetScheduledAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.ScheduledAt
}

func (v *V3InitiatePaymentRequest) GetSourceAccountID() *string {
	if v == nil {
		return nil
	}
	return v.SourceAccountID
}

func (v *V3InitiatePaymentRequest) GetType() V3PaymentInitiationTypeEnum {
	if v == nil {
		return V3PaymentInitiationTypeEnum("")
	}
	return v.Type
}
