// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V3ModulrConfig struct {
	APIKey        string  `json:"apiKey"`
	APISecret     string  `json:"apiSecret"`
	Endpoint      string  `json:"endpoint"`
	Name          string  `json:"name"`
	PageSize      *int64  `default:"25" json:"pageSize"`
	PollingPeriod *string `default:"2m" json:"pollingPeriod"`
	Provider      *string `default:"Modulr" json:"provider"`
}

func (v V3ModulrConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ModulrConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"apiKey", "apiSecret", "endpoint", "name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3ModulrConfig) GetAPIKey() string {
	if v == nil {
		return ""
	}
	return v.APIKey
}

func (v *V3ModulrConfig) GetAPISecret() string {
	if v == nil {
		return ""
	}
	return v.APISecret
}

func (v *V3ModulrConfig) GetEndpoint() string {
	if v == nil {
		return ""
	}
	return v.Endpoint
}

func (v *V3ModulrConfig) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3ModulrConfig) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3ModulrConfig) GetPollingPeriod() *string {
	if v == nil {
		return nil
	}
	return v.PollingPeriod
}

func (v *V3ModulrConfig) GetProvider() *string {
	if v == nil {
		return nil
	}
	return v.Provider
}
