// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3PaymentServiceUserUpdateLinkRequest struct {
	// The name of the application to be displayed to the user when they click the link (depending on the open banking provider). Note that this field might be mandatory for some open banking providers.
	ApplicationName   *string `json:"applicationName,omitempty"`
	ClientRedirectURL string  `json:"clientRedirectURL"`
}

func (v *V3PaymentServiceUserUpdateLinkRequest) GetApplicationName() *string {
	if v == nil {
		return nil
	}
	return v.ApplicationName
}

func (v *V3PaymentServiceUserUpdateLinkRequest) GetClientRedirectURL() string {
	if v == nil {
		return ""
	}
	return v.ClientRedirectURL
}

// #region class-body-v3paymentserviceuserupdatelinkrequest
// #endregion class-body-v3paymentserviceuserupdatelinkrequest
