// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type V3PaymentServiceUser struct {
	Address        *V3Address        `json:"address,omitempty"`
	BankAccountIDs []string          `json:"bankAccountIDs,omitempty"`
	ContactDetails *V3ContactDetails `json:"contactDetails,omitempty"`
	CreatedAt      time.Time         `json:"createdAt"`
	ID             string            `json:"id"`
	Metadata       map[string]string `json:"metadata,omitempty"`
	Name           string            `json:"name"`
}

func (v V3PaymentServiceUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentServiceUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"createdAt", "id", "name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3PaymentServiceUser) GetAddress() *V3Address {
	if v == nil {
		return nil
	}
	return v.Address
}

func (v *V3PaymentServiceUser) GetBankAccountIDs() []string {
	if v == nil {
		return nil
	}
	return v.BankAccountIDs
}

func (v *V3PaymentServiceUser) GetContactDetails() *V3ContactDetails {
	if v == nil {
		return nil
	}
	return v.ContactDetails
}

func (v *V3PaymentServiceUser) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3PaymentServiceUser) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3PaymentServiceUser) GetMetadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.Metadata
}

func (v *V3PaymentServiceUser) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}
