// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type V3PaymentServiceUserConnection struct {
	ConnectionID  string                 `json:"connectionID"`
	ConnectorID   string                 `json:"connectorID"`
	CreatedAt     time.Time              `json:"createdAt"`
	DataUpdatedAt time.Time              `json:"dataUpdatedAt"`
	Error         *string                `json:"error,omitempty"`
	Metadata      map[string]string      `json:"metadata,omitempty"`
	Status        V3ConnectionStatusEnum `json:"status"`
}

func (v V3PaymentServiceUserConnection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentServiceUserConnection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3PaymentServiceUserConnection) GetConnectionID() string {
	if v == nil {
		return ""
	}
	return v.ConnectionID
}

func (v *V3PaymentServiceUserConnection) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3PaymentServiceUserConnection) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3PaymentServiceUserConnection) GetDataUpdatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.DataUpdatedAt
}

func (v *V3PaymentServiceUserConnection) GetError() *string {
	if v == nil {
		return nil
	}
	return v.Error
}

func (v *V3PaymentServiceUserConnection) GetMetadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.Metadata
}

func (v *V3PaymentServiceUserConnection) GetStatus() V3ConnectionStatusEnum {
	if v == nil {
		return V3ConnectionStatusEnum("")
	}
	return v.Status
}

// #region class-body-v3paymentserviceuserconnection
// #endregion class-body-v3paymentserviceuserconnection
