// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3PoolsCursorResponseCursor struct {
	Data     []V3Pool `json:"data"`
	HasMore  bool     `json:"hasMore"`
	Next     *string  `json:"next,omitempty"`
	PageSize int64    `json:"pageSize"`
	Previous *string  `json:"previous,omitempty"`
}

func (v *V3PoolsCursorResponseCursor) GetData() []V3Pool {
	if v == nil {
		return []V3Pool{}
	}
	return v.Data
}

func (v *V3PoolsCursorResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V3PoolsCursorResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V3PoolsCursorResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V3PoolsCursorResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

type V3PoolsCursorResponse struct {
	Cursor V3PoolsCursorResponseCursor `json:"cursor"`
}

func (v *V3PoolsCursorResponse) GetCursor() V3PoolsCursorResponseCursor {
	if v == nil {
		return V3PoolsCursorResponseCursor{}
	}
	return v.Cursor
}
