// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3RetryPaymentInitiationResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to retry the payment initiation to the PSP. You can use the task API to check the status of the task and get the resulting payment ID.
	//
	TaskID string `json:"taskID"`
}

func (v *V3RetryPaymentInitiationResponseData) GetTaskID() string {
	if v == nil {
		return ""
	}
	return v.TaskID
}

type V3RetryPaymentInitiationResponse struct {
	Data V3RetryPaymentInitiationResponseData `json:"data"`
}

func (v *V3RetryPaymentInitiationResponse) GetData() V3RetryPaymentInitiationResponseData {
	if v == nil {
		return V3RetryPaymentInitiationResponseData{}
	}
	return v.Data
}
