// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V3WiseConfig struct {
	APIKey           string  `json:"apiKey"`
	Name             string  `json:"name"`
	PageSize         *int64  `default:"25" json:"pageSize"`
	PollingPeriod    *string `default:"2m" json:"pollingPeriod"`
	Provider         *string `default:"Wise" json:"provider"`
	WebhookPublicKey string  `json:"webhookPublicKey"`
}

func (v V3WiseConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3WiseConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"apiKey", "name", "webhookPublicKey"}); err != nil {
		return err
	}
	return nil
}

func (v *V3WiseConfig) GetAPIKey() string {
	if v == nil {
		return ""
	}
	return v.APIKey
}

func (v *V3WiseConfig) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3WiseConfig) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3WiseConfig) GetPollingPeriod() *string {
	if v == nil {
		return nil
	}
	return v.PollingPeriod
}

func (v *V3WiseConfig) GetProvider() *string {
	if v == nil {
		return nil
	}
	return v.Provider
}

func (v *V3WiseConfig) GetWebhookPublicKey() string {
	if v == nil {
		return ""
	}
	return v.WebhookPublicKey
}
