// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type WalletSubject struct {
	Balance    *string `json:"balance,omitempty"`
	Identifier string  `json:"identifier"`
	Type       string  `json:"type"`
}

func (w WalletSubject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WalletSubject) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"identifier", "type"}); err != nil {
		return err
	}
	return nil
}

func (w *WalletSubject) GetBalance() *string {
	if w == nil {
		return nil
	}
	return w.Balance
}

func (w *WalletSubject) GetIdentifier() string {
	if w == nil {
		return ""
	}
	return w.Identifier
}

func (w *WalletSubject) GetType() string {
	if w == nil {
		return ""
	}
	return w.Type
}
