// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

// AccountResponse - OK
type AccountResponse struct {
	Data Account `json:"data"`
}

func (a *AccountResponse) GetData() Account {
	if a == nil {
		return Account{}
	}
	return a.Data
}
