// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

type Account struct {
	AccountName  string    `json:"accountName"`
	ConnectorID  string    `json:"connectorID"`
	CreatedAt    time.Time `json:"createdAt"`
	DefaultAsset string    `json:"defaultAsset"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	DefaultCurrency string            `json:"defaultCurrency"`
	ID              string            `json:"id"`
	Metadata        map[string]string `json:"metadata"`
	Pools           []string          `json:"pools,omitempty"`
	Provider        *string           `json:"provider,omitempty"`
	Raw             map[string]any    `json:"raw"`
	Reference       string            `json:"reference"`
	Type            AccountType       `json:"type"`
}

func (a Account) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Account) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Account) GetAccountName() string {
	if a == nil {
		return ""
	}
	return a.AccountName
}

func (a *Account) GetConnectorID() string {
	if a == nil {
		return ""
	}
	return a.ConnectorID
}

func (a *Account) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *Account) GetDefaultAsset() string {
	if a == nil {
		return ""
	}
	return a.DefaultAsset
}

func (a *Account) GetDefaultCurrency() string {
	if a == nil {
		return ""
	}
	return a.DefaultCurrency
}

func (a *Account) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *Account) GetMetadata() map[string]string {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *Account) GetPools() []string {
	if a == nil {
		return nil
	}
	return a.Pools
}

func (a *Account) GetProvider() *string {
	if a == nil {
		return nil
	}
	return a.Provider
}

func (a *Account) GetRaw() map[string]any {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *Account) GetReference() string {
	if a == nil {
		return ""
	}
	return a.Reference
}

func (a *Account) GetType() AccountType {
	if a == nil {
		return AccountType("")
	}
	return a.Type
}
