// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

// BankAccount - A bank account registered with Formance and forwardable to connectors
type BankAccount struct {
	// Identifier of the provider-side account created by forwarding
	AccountID *string `json:"accountID,omitempty"`
	// Domestic account number, when the account is identified that way
	AccountNumber *string `json:"accountNumber,omitempty"`
	// Identifier of the connector the account has been forwarded to
	ConnectorID *string `json:"connectorID,omitempty"`
	// Country the account is held in, as an ISO 3166-1 alpha-2 code
	Country string `json:"country"`
	// When the bank account was registered
	CreatedAt time.Time `json:"createdAt"`
	// International bank account number, when the account is identified that way
	Iban *string `json:"iban,omitempty"`
	// Unique identifier of the bank account within Formance
	ID string `json:"id"`
	// Arbitrary key/value pairs attached to the bank account
	Metadata map[string]string `json:"metadata,omitempty"`
	// Human-readable name of the bank account
	Name string `json:"name"`
	// Name of the payment provider behind the connector
	Provider *string `json:"provider,omitempty"`
	// Provider-side accounts this bank account has been forwarded to
	RelatedAccounts []BankAccountRelatedAccounts `json:"relatedAccounts,omitempty"`
	// SWIFT/BIC code identifying the bank
	SwiftBicCode *string `json:"swiftBicCode,omitempty"`
}

func (b BankAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BankAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BankAccount) GetAccountID() *string {
	if b == nil {
		return nil
	}
	return b.AccountID
}

func (b *BankAccount) GetAccountNumber() *string {
	if b == nil {
		return nil
	}
	return b.AccountNumber
}

func (b *BankAccount) GetConnectorID() *string {
	if b == nil {
		return nil
	}
	return b.ConnectorID
}

func (b *BankAccount) GetCountry() string {
	if b == nil {
		return ""
	}
	return b.Country
}

func (b *BankAccount) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BankAccount) GetIban() *string {
	if b == nil {
		return nil
	}
	return b.Iban
}

func (b *BankAccount) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BankAccount) GetMetadata() map[string]string {
	if b == nil {
		return nil
	}
	return b.Metadata
}

func (b *BankAccount) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BankAccount) GetProvider() *string {
	if b == nil {
		return nil
	}
	return b.Provider
}

func (b *BankAccount) GetRelatedAccounts() []BankAccountRelatedAccounts {
	if b == nil {
		return nil
	}
	return b.RelatedAccounts
}

func (b *BankAccount) GetSwiftBicCode() *string {
	if b == nil {
		return nil
	}
	return b.SwiftBicCode
}
