// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d00612cd5584

package payments

// BankAccountResponse - OK
type BankAccountResponse struct {
	BankAccount BankAccount `json:"data"`
}

func (b *BankAccountResponse) GetBankAccount() BankAccount {
	if b == nil {
		return BankAccount{}
	}
	return b.BankAccount
}
