// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a962f39826c1

package payments

// ConnectorConfigResponse - OK
type ConnectorConfigResponse struct {
	ConnectorConfig ConnectorConfig `json:"data"`
}

func (c *ConnectorConfigResponse) GetConnectorConfig() ConnectorConfig {
	if c == nil {
		return ConnectorConfig{}
	}
	return c.ConnectorConfig
}
