// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e02a622dacf7

package payments

type ForwardBankAccountRequest struct {
	ConnectorID string `json:"connectorID"`
}

func (f *ForwardBankAccountRequest) GetConnectorID() string {
	if f == nil {
		return ""
	}
	return f.ConnectorID
}
