// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
)

type ModulrConfig struct {
	// API key issued by Modulr, used to authenticate the connector's requests
	APIKey string `json:"apiKey"`
	// API secret issued by Modulr, paired with the API key to sign requests
	APISecret string `json:"apiSecret"`
	// Base URL of the Modulr API the connector calls
	Endpoint *string `json:"endpoint,omitempty"`
	// Human-readable name identifying this connector instance
	Name string `json:"name"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from Modulr API.
	//
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	// Identifies the payment provider this configuration targets
	Provider *string `default:"Modulr" json:"provider"`
}

func (m ModulrConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ModulrConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"apiKey", "apiSecret", "name"}); err != nil {
		return err
	}
	return nil
}

func (m *ModulrConfig) GetAPIKey() string {
	if m == nil {
		return ""
	}
	return m.APIKey
}

func (m *ModulrConfig) GetAPISecret() string {
	if m == nil {
		return ""
	}
	return m.APISecret
}

func (m *ModulrConfig) GetEndpoint() *string {
	if m == nil {
		return nil
	}
	return m.Endpoint
}

func (m *ModulrConfig) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *ModulrConfig) GetPollingPeriod() *string {
	if m == nil {
		return nil
	}
	return m.PollingPeriod
}

func (m *ModulrConfig) GetProvider() *string {
	if m == nil {
		return nil
	}
	return m.Provider
}
