// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
)

type MoneycorpConfig struct {
	// API key issued by Moneycorp, used to authenticate the connector's requests
	APIKey string `json:"apiKey"`
	// Client ID issued by Moneycorp
	ClientID string `json:"clientID"`
	// Base URL of the Moneycorp API the connector calls
	Endpoint string `json:"endpoint"`
	// Human-readable name identifying this connector instance
	Name string `json:"name"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from MoneyCorp API.
	//
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	// Identifies the payment provider this configuration targets
	Provider *string `default:"Moneycorp" json:"provider"`
}

func (m MoneycorpConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MoneycorpConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"apiKey", "clientID", "endpoint", "name"}); err != nil {
		return err
	}
	return nil
}

func (m *MoneycorpConfig) GetAPIKey() string {
	if m == nil {
		return ""
	}
	return m.APIKey
}

func (m *MoneycorpConfig) GetClientID() string {
	if m == nil {
		return ""
	}
	return m.ClientID
}

func (m *MoneycorpConfig) GetEndpoint() string {
	if m == nil {
		return ""
	}
	return m.Endpoint
}

func (m *MoneycorpConfig) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MoneycorpConfig) GetPollingPeriod() *string {
	if m == nil {
		return nil
	}
	return m.PollingPeriod
}

func (m *MoneycorpConfig) GetProvider() *string {
	if m == nil {
		return nil
	}
	return m.Provider
}
