// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"math/big"
	"time"
)

type PaymentAdjustment struct {
	// Amount carried by this adjustment
	Amount *big.Int `json:"amount"`
	// When the adjustment occurred at the provider
	CreatedAt time.Time `json:"createdAt"`
	// The provider's original payload for this adjustment
	Raw map[string]any `json:"raw"`
	// Identifier the adjustment carries at the provider
	Reference string `json:"reference"`
	// Where a payment stands in its lifecycle
	Status PaymentStatus `json:"status"`
}

func (p PaymentAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentAdjustment) GetAmount() *big.Int {
	if p == nil {
		return big.NewInt(0)
	}
	return p.Amount
}

func (p *PaymentAdjustment) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PaymentAdjustment) GetRaw() map[string]any {
	if p == nil {
		return map[string]any{}
	}
	return p.Raw
}

func (p *PaymentAdjustment) GetReference() string {
	if p == nil {
		return ""
	}
	return p.Reference
}

func (p *PaymentAdjustment) GetStatus() PaymentStatus {
	if p == nil {
		return PaymentStatus("")
	}
	return p.Status
}
