// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"math/big"
	"time"
)

type PaymentRequest struct {
	// Amount of the payment, in the asset's smallest unit
	Amount *big.Int `json:"amount"`
	// Asset the payment is denominated in
	Asset string `json:"asset"`
	// Identifier of the connector the payment belongs to
	ConnectorID string `json:"connectorID"`
	// When the payment was created at the provider
	CreatedAt time.Time `json:"createdAt"`
	// Identifier of the account the funds reach
	DestinationAccountID *string `json:"destinationAccountID,omitempty"`
	// Identifier the payment carries at the provider
	Reference string `json:"reference"`
	// Payment scheme or rail a payment travels over
	Scheme PaymentScheme `json:"scheme"`
	// Identifier of the account the funds leave
	SourceAccountID *string `json:"sourceAccountID,omitempty"`
	// Where a payment stands in its lifecycle
	Status PaymentStatus `json:"status"`
	// Direction of a payment
	Type PaymentType `json:"type"`
}

func (p PaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentRequest) GetAmount() *big.Int {
	if p == nil {
		return big.NewInt(0)
	}
	return p.Amount
}

func (p *PaymentRequest) GetAsset() string {
	if p == nil {
		return ""
	}
	return p.Asset
}

func (p *PaymentRequest) GetConnectorID() string {
	if p == nil {
		return ""
	}
	return p.ConnectorID
}

func (p *PaymentRequest) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PaymentRequest) GetDestinationAccountID() *string {
	if p == nil {
		return nil
	}
	return p.DestinationAccountID
}

func (p *PaymentRequest) GetReference() string {
	if p == nil {
		return ""
	}
	return p.Reference
}

func (p *PaymentRequest) GetScheme() PaymentScheme {
	if p == nil {
		return PaymentScheme("")
	}
	return p.Scheme
}

func (p *PaymentRequest) GetSourceAccountID() *string {
	if p == nil {
		return nil
	}
	return p.SourceAccountID
}

func (p *PaymentRequest) GetStatus() PaymentStatus {
	if p == nil {
		return PaymentStatus("")
	}
	return p.Status
}

func (p *PaymentRequest) GetType() PaymentType {
	if p == nil {
		return PaymentType("")
	}
	return p.Type
}
