// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: deb07ee0fe9c

package payments

type PoolsCursorCursorBase struct {
	Data     []Pool  `json:"data"`
	HasMore  bool    `json:"hasMore"`
	Next     *string `json:"next,omitempty"`
	PageSize int64   `json:"pageSize"`
	Previous *string `json:"previous,omitempty"`
}

func (p *PoolsCursorCursorBase) GetData() []Pool {
	if p == nil {
		return []Pool{}
	}
	return p.Data
}

func (p *PoolsCursorCursorBase) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PoolsCursorCursorBase) GetNext() *string {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *PoolsCursorCursorBase) GetPageSize() int64 {
	if p == nil {
		return 0
	}
	return p.PageSize
}

func (p *PoolsCursorCursorBase) GetPrevious() *string {
	if p == nil {
		return nil
	}
	return p.Previous
}

// PoolsCursor - OK
type PoolsCursor struct {
	CursorBase PoolsCursorCursorBase `json:"cursor"`
}

func (p *PoolsCursor) GetCursorBase() PoolsCursorCursorBase {
	if p == nil {
		return PoolsCursorCursorBase{}
	}
	return p.CursorBase
}
