// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 79d4878c660c

package payments

type Pool struct {
	PoolTypeEnum *PoolTypeEnum  `json:"type,omitempty"`
	Accounts     []string       `json:"accounts"`
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Query        map[string]any `json:"query,omitempty"`
}

func (p *Pool) GetPoolTypeEnum() *PoolTypeEnum {
	if p == nil {
		return nil
	}
	return p.PoolTypeEnum
}

func (p *Pool) GetAccounts() []string {
	if p == nil {
		return []string{}
	}
	return p.Accounts
}

func (p *Pool) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Pool) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Pool) GetQuery() map[string]any {
	if p == nil {
		return nil
	}
	return p.Query
}
