// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

type PoolBalances struct {
	Balances []PoolBalance `json:"balances"`
}

func (p *PoolBalances) GetBalances() []PoolBalance {
	if p == nil {
		return []PoolBalance{}
	}
	return p.Balances
}
