// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 07c861b19715

package payments

// PoolBalancesResponse - OK
type PoolBalancesResponse struct {
	PoolBalances PoolBalances `json:"data"`
}

func (p *PoolBalancesResponse) GetPoolBalances() PoolBalances {
	if p == nil {
		return PoolBalances{}
	}
	return p.PoolBalances
}
