// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c99a0935398d

package payments

// TaskResponse - OK
type TaskResponse struct {
	Data any `json:"data"`
}

func (t *TaskResponse) GetData() any {
	if t == nil {
		return nil
	}
	return t.Data
}
