// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

type TaskDummyPayDescriptor struct {
	FileName *string `json:"fileName,omitempty"`
	Key      *string `json:"key,omitempty"`
	Name     *string `json:"name,omitempty"`
}

func (t TaskDummyPayDescriptor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskDummyPayDescriptor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskDummyPayDescriptor) GetFileName() *string {
	if t == nil {
		return nil
	}
	return t.FileName
}

func (t *TaskDummyPayDescriptor) GetKey() *string {
	if t == nil {
		return nil
	}
	return t.Key
}

func (t *TaskDummyPayDescriptor) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

// TaskDummyPayState - Internal progress state the task resumes from
type TaskDummyPayState struct {
}

func (t TaskDummyPayState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskDummyPayState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

type TaskDummyPay struct {
	// Identifier of the connector the task runs against
	ConnectorID string `json:"connectorID"`
	// When the task was created
	CreatedAt  time.Time              `json:"createdAt"`
	Descriptor TaskDummyPayDescriptor `json:"descriptor"`
	// Why the task failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Unique identifier of the task
	ID string `json:"id"`
	// Internal progress state the task resumes from
	State *TaskDummyPayState `json:"state,omitempty"`
	// Where a task stands, from pending or active through to stopped, terminated or failed
	Status TaskStatus `json:"status"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

func (t TaskDummyPay) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskDummyPay) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"connectorID", "createdAt", "descriptor", "id", "status", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (t *TaskDummyPay) GetConnectorID() string {
	if t == nil {
		return ""
	}
	return t.ConnectorID
}

func (t *TaskDummyPay) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TaskDummyPay) GetDescriptor() TaskDummyPayDescriptor {
	if t == nil {
		return TaskDummyPayDescriptor{}
	}
	return t.Descriptor
}

func (t *TaskDummyPay) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TaskDummyPay) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TaskDummyPay) GetState() *TaskDummyPayState {
	if t == nil {
		return nil
	}
	return t.State
}

func (t *TaskDummyPay) GetStatus() TaskStatus {
	if t == nil {
		return TaskStatus("")
	}
	return t.Status
}

func (t *TaskDummyPay) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
