// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

type TaskWiseDescriptor struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	ProfileID *int64  `json:"profileID,omitempty"`
}

func (t TaskWiseDescriptor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskWiseDescriptor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskWiseDescriptor) GetKey() *string {
	if t == nil {
		return nil
	}
	return t.Key
}

func (t *TaskWiseDescriptor) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *TaskWiseDescriptor) GetProfileID() *int64 {
	if t == nil {
		return nil
	}
	return t.ProfileID
}

// TaskWiseState - Internal progress state the task resumes from
type TaskWiseState struct {
}

func (t TaskWiseState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskWiseState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

type TaskWise struct {
	// Identifier of the connector the task runs against
	ConnectorID string `json:"connectorID"`
	// When the task was created
	CreatedAt  time.Time          `json:"createdAt"`
	Descriptor TaskWiseDescriptor `json:"descriptor"`
	// Why the task failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Unique identifier of the task
	ID string `json:"id"`
	// Internal progress state the task resumes from
	State *TaskWiseState `json:"state,omitempty"`
	// Where a task stands, from pending or active through to stopped, terminated or failed
	Status TaskStatus `json:"status"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

func (t TaskWise) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskWise) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"connectorID", "createdAt", "descriptor", "id", "status", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (t *TaskWise) GetConnectorID() string {
	if t == nil {
		return ""
	}
	return t.ConnectorID
}

func (t *TaskWise) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TaskWise) GetDescriptor() TaskWiseDescriptor {
	if t == nil {
		return TaskWiseDescriptor{}
	}
	return t.Descriptor
}

func (t *TaskWise) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TaskWise) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TaskWise) GetState() *TaskWiseState {
	if t == nil {
		return nil
	}
	return t.State
}

func (t *TaskWise) GetStatus() TaskStatus {
	if t == nil {
		return TaskStatus("")
	}
	return t.Status
}

func (t *TaskWise) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
