// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

type Descriptor struct {
	Key  *string `json:"key,omitempty"`
	Name *string `json:"name,omitempty"`
}

func (d Descriptor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Descriptor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *Descriptor) GetKey() *string {
	if d == nil {
		return nil
	}
	return d.Key
}

func (d *Descriptor) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

// State - Internal progress state the task resumes from
type State struct {
}

func (s State) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *State) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

type TaskBankingCircle struct {
	// Identifier of the connector the task runs against
	ConnectorID string `json:"connectorID"`
	// When the task was created
	CreatedAt  time.Time  `json:"createdAt"`
	Descriptor Descriptor `json:"descriptor"`
	// Why the task failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Unique identifier of the task
	ID string `json:"id"`
	// Internal progress state the task resumes from
	State *State `json:"state,omitempty"`
	// Where a task stands, from pending or active through to stopped, terminated or failed
	Status TaskStatus `json:"status"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

func (t TaskBankingCircle) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskBankingCircle) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"connectorID", "createdAt", "descriptor", "id", "status", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (t *TaskBankingCircle) GetConnectorID() string {
	if t == nil {
		return ""
	}
	return t.ConnectorID
}

func (t *TaskBankingCircle) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TaskBankingCircle) GetDescriptor() Descriptor {
	if t == nil {
		return Descriptor{}
	}
	return t.Descriptor
}

func (t *TaskBankingCircle) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TaskBankingCircle) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TaskBankingCircle) GetState() *State {
	if t == nil {
		return nil
	}
	return t.State
}

func (t *TaskBankingCircle) GetStatus() TaskStatus {
	if t == nil {
		return TaskStatus("")
	}
	return t.Status
}

func (t *TaskBankingCircle) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
