// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

type TaskCurrencyCloudDescriptor struct {
	Name *string `json:"name,omitempty"`
}

func (t TaskCurrencyCloudDescriptor) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskCurrencyCloudDescriptor) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TaskCurrencyCloudDescriptor) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

// TaskCurrencyCloudState - Internal progress state the task resumes from
type TaskCurrencyCloudState struct {
}

func (t TaskCurrencyCloudState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskCurrencyCloudState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

type TaskCurrencyCloud struct {
	// Identifier of the connector the task runs against
	ConnectorID string `json:"connectorID"`
	// When the task was created
	CreatedAt  time.Time                   `json:"createdAt"`
	Descriptor TaskCurrencyCloudDescriptor `json:"descriptor"`
	// Why the task failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Unique identifier of the task
	ID string `json:"id"`
	// Internal progress state the task resumes from
	State *TaskCurrencyCloudState `json:"state,omitempty"`
	// Where a task stands, from pending or active through to stopped, terminated or failed
	Status TaskStatus `json:"status"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

func (t TaskCurrencyCloud) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskCurrencyCloud) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"connectorID", "createdAt", "descriptor", "id", "status", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (t *TaskCurrencyCloud) GetConnectorID() string {
	if t == nil {
		return ""
	}
	return t.ConnectorID
}

func (t *TaskCurrencyCloud) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TaskCurrencyCloud) GetDescriptor() TaskCurrencyCloudDescriptor {
	if t == nil {
		return TaskCurrencyCloudDescriptor{}
	}
	return t.Descriptor
}

func (t *TaskCurrencyCloud) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TaskCurrencyCloud) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TaskCurrencyCloud) GetState() *TaskCurrencyCloudState {
	if t == nil {
		return nil
	}
	return t.State
}

func (t *TaskCurrencyCloud) GetStatus() TaskStatus {
	if t == nil {
		return TaskStatus("")
	}
	return t.Status
}

func (t *TaskCurrencyCloud) GetUpdatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.UpdatedAt
}
