// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

// TransferInitiationResponse - OK
type TransferInitiationResponse struct {
	TransferInitiation TransferInitiation `json:"data"`
}

func (t *TransferInitiationResponse) GetTransferInitiation() TransferInitiation {
	if t == nil {
		return TransferInitiation{}
	}
	return t.TransferInitiation
}
