// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0ce4b8cd56b4

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type TransferInitiationAdjustments struct {
	TransferInitiationStatus TransferInitiationStatus `json:"status"`
	AdjustmentID             string                   `json:"adjustmentID"`
	CreatedAt                time.Time                `json:"createdAt"`
	Error                    *string                  `json:"error,omitempty"`
	Metadata                 map[string]string        `json:"metadata,omitempty"`
}

func (t TransferInitiationAdjustments) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferInitiationAdjustments) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TransferInitiationAdjustments) GetTransferInitiationStatus() TransferInitiationStatus {
	if t == nil {
		return TransferInitiationStatus("")
	}
	return t.TransferInitiationStatus
}

func (t *TransferInitiationAdjustments) GetAdjustmentID() string {
	if t == nil {
		return ""
	}
	return t.AdjustmentID
}

func (t *TransferInitiationAdjustments) GetCreatedAt() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.CreatedAt
}

func (t *TransferInitiationAdjustments) GetError() *string {
	if t == nil {
		return nil
	}
	return t.Error
}

func (t *TransferInitiationAdjustments) GetMetadata() map[string]string {
	if t == nil {
		return nil
	}
	return t.Metadata
}
