// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ce0286cad4cd

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type V3AccountRaw struct {
}

// #region class-body-v3accountraw
// #endregion class-body-v3accountraw

type V3Account struct {
	V3AccountTypeEnum V3AccountTypeEnum `json:"type"`
	V3ConnectorBase   *V3ConnectorBase  `json:"connector,omitempty"`
	V3Metadata        map[string]string `json:"metadata,omitempty"`
	ConnectorID       string            `json:"connectorID"`
	CreatedAt         time.Time         `json:"createdAt"`
	DefaultAsset      *string           `json:"defaultAsset,omitempty"`
	ID                string            `json:"id"`
	Name              *string           `json:"name,omitempty"`
	Provider          string            `json:"provider"`
	Raw               V3AccountRaw      `json:"raw"`
	Reference         string            `json:"reference"`
}

func (v V3Account) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3Account) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3Account) GetV3AccountTypeEnum() V3AccountTypeEnum {
	if v == nil {
		return V3AccountTypeEnum("")
	}
	return v.V3AccountTypeEnum
}

func (v *V3Account) GetV3ConnectorBase() *V3ConnectorBase {
	if v == nil {
		return nil
	}
	return v.V3ConnectorBase
}

func (v *V3Account) GetV3Metadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.V3Metadata
}

func (v *V3Account) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3Account) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3Account) GetDefaultAsset() *string {
	if v == nil {
		return nil
	}
	return v.DefaultAsset
}

func (v *V3Account) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3Account) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *V3Account) GetProvider() string {
	if v == nil {
		return ""
	}
	return v.Provider
}

func (v *V3Account) GetRaw() V3AccountRaw {
	if v == nil {
		return V3AccountRaw{}
	}
	return v.Raw
}

func (v *V3Account) GetReference() string {
	if v == nil {
		return ""
	}
	return v.Reference
}

// #region class-body-v3account
// #endregion class-body-v3account
