// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

// V3Address - A postal address
type V3Address struct {
	// City of the address
	City *string `json:"city,omitempty"`
	// Country of the address, as an ISO 3166-1 alpha-2 code
	Country *string `json:"country,omitempty"`
	// Postal or ZIP code of the address
	PostalCode *string `json:"postalCode,omitempty"`
	// Region, state or province of the address
	Region *string `json:"region,omitempty"`
	// Street name of the address
	StreetName *string `json:"streetName,omitempty"`
	// Street number of the address
	StreetNumber *string `json:"streetNumber,omitempty"`
}

func (v *V3Address) GetCity() *string {
	if v == nil {
		return nil
	}
	return v.City
}

func (v *V3Address) GetCountry() *string {
	if v == nil {
		return nil
	}
	return v.Country
}

func (v *V3Address) GetPostalCode() *string {
	if v == nil {
		return nil
	}
	return v.PostalCode
}

func (v *V3Address) GetRegion() *string {
	if v == nil {
		return nil
	}
	return v.Region
}

func (v *V3Address) GetStreetName() *string {
	if v == nil {
		return nil
	}
	return v.StreetName
}

func (v *V3Address) GetStreetNumber() *string {
	if v == nil {
		return nil
	}
	return v.StreetNumber
}

// #region class-body-v3address
// #endregion class-body-v3address
