// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

type V3ConnectorCapabilityResponse struct {
	Data []V3Capability `json:"data"`
}

func (v *V3ConnectorCapabilityResponse) GetData() []V3Capability {
	if v == nil {
		return []V3Capability{}
	}
	return v.Data
}

// #region class-body-v3connectorcapabilityresponse
// #endregion class-body-v3connectorcapabilityresponse
