// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

// V3ContactDetails - How to reach a payment service user
type V3ContactDetails struct {
	// Email address of the user
	Email *string `json:"email,omitempty"`
	// Phone number of the user, in international format
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

func (v *V3ContactDetails) GetEmail() *string {
	if v == nil {
		return nil
	}
	return v.Email
}

func (v *V3ContactDetails) GetPhoneNumber() *string {
	if v == nil {
		return nil
	}
	return v.PhoneNumber
}

// #region class-body-v3contactdetails
// #endregion class-body-v3contactdetails
