// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 60cf4289de9b

package payments

type V3ContactDetails struct {
	Email       *string `json:"email,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

func (v *V3ContactDetails) GetEmail() *string {
	if v == nil {
		return nil
	}
	return v.Email
}

func (v *V3ContactDetails) GetPhoneNumber() *string {
	if v == nil {
		return nil
	}
	return v.PhoneNumber
}

// #region class-body-v3contactdetails
// #endregion class-body-v3contactdetails
