// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5bd124ed0ee2

package payments

type V3ConnectorScheduleResponse struct {
	V3Schedule V3Schedule `json:"data"`
}

func (v *V3ConnectorScheduleResponse) GetV3Schedule() V3Schedule {
	if v == nil {
		return V3Schedule{}
	}
	return v.V3Schedule
}

// #region class-body-v3connectorscheduleresponse
// #endregion class-body-v3connectorscheduleresponse
