// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

// V3ConversionsCursorResponseCursor - Paginated cursor wrapping the list of conversions
type V3ConversionsCursorResponseCursor struct {
	Data     []V3Conversion `json:"data"`
	HasMore  bool           `json:"hasMore"`
	Next     *string        `json:"next,omitempty"`
	PageSize int64          `json:"pageSize"`
	Previous *string        `json:"previous,omitempty"`
}

func (v *V3ConversionsCursorResponseCursor) GetData() []V3Conversion {
	if v == nil {
		return []V3Conversion{}
	}
	return v.Data
}

func (v *V3ConversionsCursorResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V3ConversionsCursorResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V3ConversionsCursorResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V3ConversionsCursorResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

// #region class-body-v3conversionscursorresponsecursor
// #endregion class-body-v3conversionscursorresponsecursor

type V3ConversionsCursorResponse struct {
	// Paginated cursor wrapping the list of conversions
	Cursor V3ConversionsCursorResponseCursor `json:"cursor"`
}

func (v *V3ConversionsCursorResponse) GetCursor() V3ConversionsCursorResponseCursor {
	if v == nil {
		return V3ConversionsCursorResponseCursor{}
	}
	return v.Cursor
}

// #region class-body-v3conversionscursorresponse
// #endregion class-body-v3conversionscursorresponse
