// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

type V3CreatePaymentServiceUserRequest struct {
	// A postal address to record on the payment service user
	Address *V3AddressRequest `json:"address,omitempty"`
	// Bank accounts to associate with the user
	BankAccountIDs []string `json:"bankAccountIDs,omitempty"`
	// How to reach the payment service user
	ContactDetails *V3ContactDetailsRequest `json:"contactDetails,omitempty"`
	// Arbitrary key/value pairs attached to the resource
	Metadata map[string]string `json:"metadata,omitempty"`
	// Full name of the payment service user
	Name string `json:"name"`
}

func (v *V3CreatePaymentServiceUserRequest) GetAddress() *V3AddressRequest {
	if v == nil {
		return nil
	}
	return v.Address
}

func (v *V3CreatePaymentServiceUserRequest) GetBankAccountIDs() []string {
	if v == nil {
		return nil
	}
	return v.BankAccountIDs
}

func (v *V3CreatePaymentServiceUserRequest) GetContactDetails() *V3ContactDetailsRequest {
	if v == nil {
		return nil
	}
	return v.ContactDetails
}

func (v *V3CreatePaymentServiceUserRequest) GetMetadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.Metadata
}

func (v *V3CreatePaymentServiceUserRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

// #region class-body-v3createpaymentserviceuserrequest
// #endregion class-body-v3createpaymentserviceuserrequest
