// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f44f6180345a

package payments

type V3ForwardPaymentServiceUserBankAccountResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to forward the bank account to the PSP. You can use the task API to check the status of the task and get the resulting bank account ID.
	//
	TaskID string `json:"taskID"`
}

func (v *V3ForwardPaymentServiceUserBankAccountResponseData) GetTaskID() string {
	if v == nil {
		return ""
	}
	return v.TaskID
}

// #region class-body-v3forwardpaymentserviceuserbankaccountresponsedata
// #endregion class-body-v3forwardpaymentserviceuserbankaccountresponsedata

type V3ForwardPaymentServiceUserBankAccountResponse struct {
	Data V3ForwardPaymentServiceUserBankAccountResponseData `json:"data"`
}

func (v *V3ForwardPaymentServiceUserBankAccountResponse) GetData() V3ForwardPaymentServiceUserBankAccountResponseData {
	if v == nil {
		return V3ForwardPaymentServiceUserBankAccountResponseData{}
	}
	return v.Data
}

// #region class-body-v3forwardpaymentserviceuserbankaccountresponse
// #endregion class-body-v3forwardpaymentserviceuserbankaccountresponse
