// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 770f017ee74d

package payments

type V3GetTaskResponse struct {
	V3Task V3Task `json:"data"`
}

func (v *V3GetTaskResponse) GetV3Task() V3Task {
	if v == nil {
		return V3Task{}
	}
	return v.V3Task
}

// #region class-body-v3gettaskresponse
// #endregion class-body-v3gettaskresponse
