// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c67f38ab39d1

package payments

type V3GetPaymentResponse struct {
	V3Payment V3Payment `json:"data"`
}

func (v *V3GetPaymentResponse) GetV3Payment() V3Payment {
	if v == nil {
		return V3Payment{}
	}
	return v.V3Payment
}

// #region class-body-v3getpaymentresponse
// #endregion class-body-v3getpaymentresponse
