// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

type V3GetBankAccountResponse struct {
	// A bank account registered with Formance and forwardable to connectors
	Data V3BankAccount `json:"data"`
}

func (v *V3GetBankAccountResponse) GetData() V3BankAccount {
	if v == nil {
		return V3BankAccount{}
	}
	return v.Data
}

// #region class-body-v3getbankaccountresponse
// #endregion class-body-v3getbankaccountresponse
