// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1cdc6c676136

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V3IncreaseConfig struct {
	APIKey   string `json:"apiKey"`
	Endpoint string `json:"endpoint"`
	Name     string `json:"name"`
	// Deprecated: From v3.1, this parameter will be ignored.
	PageSize            *int64  `default:"25" json:"pageSize"`
	PollingPeriod       *string `default:"30m" json:"pollingPeriod"`
	Provider            *string `default:"Increase" json:"provider"`
	WebhookSharedSecret string  `json:"webhookSharedSecret"`
}

func (v V3IncreaseConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3IncreaseConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"apiKey", "endpoint", "name", "webhookSharedSecret"}); err != nil {
		return err
	}
	return nil
}

func (v *V3IncreaseConfig) GetAPIKey() string {
	if v == nil {
		return ""
	}
	return v.APIKey
}

func (v *V3IncreaseConfig) GetEndpoint() string {
	if v == nil {
		return ""
	}
	return v.Endpoint
}

func (v *V3IncreaseConfig) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3IncreaseConfig) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3IncreaseConfig) GetPollingPeriod() *string {
	if v == nil {
		return nil
	}
	return v.PollingPeriod
}

func (v *V3IncreaseConfig) GetProvider() *string {
	if v == nil {
		return nil
	}
	return v.Provider
}

func (v *V3IncreaseConfig) GetWebhookSharedSecret() string {
	if v == nil {
		return ""
	}
	return v.WebhookSharedSecret
}

// #region class-body-v3increaseconfig
// #endregion class-body-v3increaseconfig
