// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V3MangopayConfig struct {
	APIKey   string `json:"apiKey"`
	ClientID string `json:"clientID"`
	Endpoint string `json:"endpoint"`
	Name     string `json:"name"`
	// Deprecated: From v3.1, this parameter will be ignored.
	PageSize      *int64  `default:"25" json:"pageSize"`
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	Provider      *string `default:"Mangopay" json:"provider"`
}

func (v V3MangopayConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3MangopayConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"apiKey", "clientID", "endpoint", "name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3MangopayConfig) GetAPIKey() string {
	if v == nil {
		return ""
	}
	return v.APIKey
}

func (v *V3MangopayConfig) GetClientID() string {
	if v == nil {
		return ""
	}
	return v.ClientID
}

func (v *V3MangopayConfig) GetEndpoint() string {
	if v == nil {
		return ""
	}
	return v.Endpoint
}

func (v *V3MangopayConfig) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3MangopayConfig) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3MangopayConfig) GetPollingPeriod() *string {
	if v == nil {
		return nil
	}
	return v.PollingPeriod
}

func (v *V3MangopayConfig) GetProvider() *string {
	if v == nil {
		return nil
	}
	return v.Provider
}

// #region class-body-v3mangopayconfig
// #endregion class-body-v3mangopayconfig
