// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ee50f178be3c

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type V3PaymentInitiationAdjustment struct {
	V3Metadata                    map[string]string             `json:"metadata,omitempty"`
	V3PaymentInitiationStatusEnum V3PaymentInitiationStatusEnum `json:"status"`
	Amount                        *big.Int                      `json:"amount,omitempty"`
	Asset                         *string                       `json:"asset,omitempty"`
	CreatedAt                     time.Time                     `json:"createdAt"`
	Error                         *string                       `json:"error,omitempty"`
	ID                            string                        `json:"id"`
}

func (v V3PaymentInitiationAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentInitiationAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3PaymentInitiationAdjustment) GetV3Metadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.V3Metadata
}

func (v *V3PaymentInitiationAdjustment) GetV3PaymentInitiationStatusEnum() V3PaymentInitiationStatusEnum {
	if v == nil {
		return V3PaymentInitiationStatusEnum("")
	}
	return v.V3PaymentInitiationStatusEnum
}

func (v *V3PaymentInitiationAdjustment) GetAmount() *big.Int {
	if v == nil {
		return nil
	}
	return v.Amount
}

func (v *V3PaymentInitiationAdjustment) GetAsset() *string {
	if v == nil {
		return nil
	}
	return v.Asset
}

func (v *V3PaymentInitiationAdjustment) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3PaymentInitiationAdjustment) GetError() *string {
	if v == nil {
		return nil
	}
	return v.Error
}

func (v *V3PaymentInitiationAdjustment) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

// #region class-body-v3paymentinitiationadjustment
// #endregion class-body-v3paymentinitiationadjustment
