// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

type V3PaymentServiceUserDeleteResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to delete the payment service user. You can use the task API to check the status of the task.
	//
	TaskID string `json:"taskID"`
}

func (v *V3PaymentServiceUserDeleteResponseData) GetTaskID() string {
	if v == nil {
		return ""
	}
	return v.TaskID
}

// #region class-body-v3paymentserviceuserdeleteresponsedata
// #endregion class-body-v3paymentserviceuserdeleteresponsedata

type V3PaymentServiceUserDeleteResponse struct {
	Data V3PaymentServiceUserDeleteResponseData `json:"data"`
}

func (v *V3PaymentServiceUserDeleteResponse) GetData() V3PaymentServiceUserDeleteResponseData {
	if v == nil {
		return V3PaymentServiceUserDeleteResponseData{}
	}
	return v.Data
}

// #region class-body-v3paymentserviceuserdeleteresponse
// #endregion class-body-v3paymentserviceuserdeleteresponse
