// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 46194c6c279f

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type V3PaymentAdjustmentRaw struct {
}

// #region class-body-v3paymentadjustmentraw
// #endregion class-body-v3paymentadjustmentraw

type V3PaymentAdjustment struct {
	V3Metadata          map[string]string      `json:"metadata,omitempty"`
	V3PaymentStatusEnum V3PaymentStatusEnum    `json:"status"`
	Amount              *big.Int               `json:"amount,omitempty"`
	Asset               *string                `json:"asset,omitempty"`
	CreatedAt           time.Time              `json:"createdAt"`
	ID                  string                 `json:"id"`
	Raw                 V3PaymentAdjustmentRaw `json:"raw"`
	Reference           string                 `json:"reference"`
}

func (v V3PaymentAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3PaymentAdjustment) GetV3Metadata() map[string]string {
	if v == nil {
		return nil
	}
	return v.V3Metadata
}

func (v *V3PaymentAdjustment) GetV3PaymentStatusEnum() V3PaymentStatusEnum {
	if v == nil {
		return V3PaymentStatusEnum("")
	}
	return v.V3PaymentStatusEnum
}

func (v *V3PaymentAdjustment) GetAmount() *big.Int {
	if v == nil {
		return nil
	}
	return v.Amount
}

func (v *V3PaymentAdjustment) GetAsset() *string {
	if v == nil {
		return nil
	}
	return v.Asset
}

func (v *V3PaymentAdjustment) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3PaymentAdjustment) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3PaymentAdjustment) GetRaw() V3PaymentAdjustmentRaw {
	if v == nil {
		return V3PaymentAdjustmentRaw{}
	}
	return v.Raw
}

func (v *V3PaymentAdjustment) GetReference() string {
	if v == nil {
		return ""
	}
	return v.Reference
}

// #region class-body-v3paymentadjustment
// #endregion class-body-v3paymentadjustment
