// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

// V3PaymentServiceUserDeleteConnectionResponseData - The task tracking the deletion, which completes asynchronously
type V3PaymentServiceUserDeleteConnectionResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to delete the connection. You can use the task API to check the status of the task.
	//
	TaskID string `json:"taskID"`
}

func (v *V3PaymentServiceUserDeleteConnectionResponseData) GetTaskID() string {
	if v == nil {
		return ""
	}
	return v.TaskID
}

// #region class-body-v3paymentserviceuserdeleteconnectionresponsedata
// #endregion class-body-v3paymentserviceuserdeleteconnectionresponsedata

type V3PaymentServiceUserDeleteConnectionResponse struct {
	// The task tracking the deletion, which completes asynchronously
	Data V3PaymentServiceUserDeleteConnectionResponseData `json:"data"`
}

func (v *V3PaymentServiceUserDeleteConnectionResponse) GetData() V3PaymentServiceUserDeleteConnectionResponseData {
	if v == nil {
		return V3PaymentServiceUserDeleteConnectionResponseData{}
	}
	return v.Data
}

// #region class-body-v3paymentserviceuserdeleteconnectionresponse
// #endregion class-body-v3paymentserviceuserdeleteconnectionresponse
