// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd93187c3144

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
)

type V3PoolBalance struct {
	Amount          *big.Int `json:"amount"`
	Asset           string   `json:"asset"`
	RelatedAccounts []string `json:"relatedAccounts,omitempty"`
}

func (v V3PoolBalance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PoolBalance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3PoolBalance) GetAmount() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.Amount
}

func (v *V3PoolBalance) GetAsset() string {
	if v == nil {
		return ""
	}
	return v.Asset
}

func (v *V3PoolBalance) GetRelatedAccounts() []string {
	if v == nil {
		return nil
	}
	return v.RelatedAccounts
}

// #region class-body-v3poolbalance
// #endregion class-body-v3poolbalance
