// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/formancehq/formance-sdk-go/v5/pkg/utils"
	"time"
)

// V3Schedule - A recurring job a connector runs to fetch data from its provider
type V3Schedule struct {
	// Identifier of the connector this schedule belongs to
	ConnectorID string `json:"connectorID"`
	// When the schedule was created
	CreatedAt time.Time `json:"createdAt"`
	// Unique identifier of the schedule
	ID string `json:"id"`
	// When the schedule was paused, absent while it is running
	PausedAt *time.Time `json:"pausedAt,omitempty"`
	// Why the schedule was paused
	PausedReason *string `json:"pausedReason,omitempty"`
}

func (v V3Schedule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3Schedule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V3Schedule) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3Schedule) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V3Schedule) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *V3Schedule) GetPausedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.PausedAt
}

func (v *V3Schedule) GetPausedReason() *string {
	if v == nil {
		return nil
	}
	return v.PausedReason
}

// #region class-body-v3schedule
// #endregion class-body-v3schedule
