// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c5491a51dee5

package payments

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V3StripeConfig struct {
	APIKey string `json:"apiKey"`
	Name   string `json:"name"`
	// Deprecated: From v3.1, this parameter will be ignored.
	PageSize      *int64  `default:"25" json:"pageSize"`
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	Provider      *string `default:"Stripe" json:"provider"`
}

func (v V3StripeConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3StripeConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"apiKey", "name"}); err != nil {
		return err
	}
	return nil
}

func (v *V3StripeConfig) GetAPIKey() string {
	if v == nil {
		return ""
	}
	return v.APIKey
}

func (v *V3StripeConfig) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3StripeConfig) GetPageSize() *int64 {
	if v == nil {
		return nil
	}
	return v.PageSize
}

func (v *V3StripeConfig) GetPollingPeriod() *string {
	if v == nil {
		return nil
	}
	return v.PollingPeriod
}

func (v *V3StripeConfig) GetProvider() *string {
	if v == nil {
		return nil
	}
	return v.Provider
}

// #region class-body-v3stripeconfig
// #endregion class-body-v3stripeconfig
