// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 885d9d3b8c14

package wallets

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type AssetHolder1 struct {
	Assets    map[string]*big.Int `json:"assets"`
	ExpiresAt *time.Time          `json:"expiresAt,omitempty"`
	Name      string              `json:"name"`
	Priority  *big.Int            `json:"priority,omitempty"`
}

func (a AssetHolder1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AssetHolder1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AssetHolder1) GetAssets() map[string]*big.Int {
	if a == nil {
		return map[string]*big.Int{}
	}
	return a.Assets
}

func (a *AssetHolder1) GetExpiresAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ExpiresAt
}

func (a *AssetHolder1) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AssetHolder1) GetPriority() *big.Int {
	if a == nil {
		return nil
	}
	return a.Priority
}

// #region class-body-assetholder1
// #endregion class-body-assetholder1
