// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package wallets

type CreateBalanceResponse struct {
	Data Balance `json:"data"`
}

func (c *CreateBalanceResponse) GetData() Balance {
	if c == nil {
		return Balance{}
	}
	return c.Data
}
