// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package wallets

type CreateBalanceResponse struct {
	Balance Balance `json:"data"`
}

func (c *CreateBalanceResponse) GetBalance() Balance {
	if c == nil {
		return Balance{}
	}
	return c.Balance
}
