// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5acd8869f81a

package wallets

import (
	"encoding/json"
	"fmt"
)

type ErrorCode string

const (
	ErrorCodeValidation       ErrorCode = "VALIDATION"
	ErrorCodeInternalError    ErrorCode = "INTERNAL_ERROR"
	ErrorCodeInsufficientFund ErrorCode = "INSUFFICIENT_FUND"
	ErrorCodeHoldClosed       ErrorCode = "HOLD_CLOSED"
)

func (e ErrorCode) ToPointer() *ErrorCode {
	return &e
}
func (e *ErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "VALIDATION":
		fallthrough
	case "INTERNAL_ERROR":
		fallthrough
	case "INSUFFICIENT_FUND":
		fallthrough
	case "HOLD_CLOSED":
		*e = ErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorCode: %v", v)
	}
}

type ErrorResponse struct {
	ErrorCode    ErrorCode `json:"errorCode"`
	ErrorMessage string    `json:"errorMessage"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
