// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 61c3f3ad250d

package wallets

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
)

type Hold1 struct {
	Subject     *Subject `json:"destination,omitempty"`
	Asset       string   `json:"asset"`
	Description string   `json:"description"`
	// The unique ID of the hold.
	ID string `json:"id"`
	// Metadata associated with the hold.
	Metadata map[string]string `json:"metadata"`
	// Original amount on hold
	OriginalAmount *big.Int `json:"originalAmount"`
	// Remaining amount on hold
	Remaining *big.Int `json:"remaining"`
	// The ID of the wallet the hold is associated with.
	WalletID string `json:"walletID"`
}

func (h Hold1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *Hold1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *Hold1) GetSubject() *Subject {
	if h == nil {
		return nil
	}
	return h.Subject
}

func (h *Hold1) GetAsset() string {
	if h == nil {
		return ""
	}
	return h.Asset
}

func (h *Hold1) GetDescription() string {
	if h == nil {
		return ""
	}
	return h.Description
}

func (h *Hold1) GetID() string {
	if h == nil {
		return ""
	}
	return h.ID
}

func (h *Hold1) GetMetadata() map[string]string {
	if h == nil {
		return map[string]string{}
	}
	return h.Metadata
}

func (h *Hold1) GetOriginalAmount() *big.Int {
	if h == nil {
		return big.NewInt(0)
	}
	return h.OriginalAmount
}

func (h *Hold1) GetRemaining() *big.Int {
	if h == nil {
		return big.NewInt(0)
	}
	return h.Remaining
}

func (h *Hold1) GetWalletID() string {
	if h == nil {
		return ""
	}
	return h.WalletID
}

// #region class-body-hold1
// #endregion class-body-hold1
