workflowVersion: 1.0.0
speakeasyVersion: 1.770.0
sources:
    stacks-source:
        inputs:
            - location: registry.speakeasyapi.dev/formance/formance/stacks-source@sha256:1d9e07120ee16749020c103aba5ef1de0601f8ee52ff065d000a1e651521898e
        registry:
            location: registry.speakeasyapi.dev/formance/formance/stacks-source
targets:
    formance-sdk-go:
        target: go
        source: stacks-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/stacks-source-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
