workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.0-beta.2/generate.json
targets:
    formance-sdk-go:
        target: go
        source: my-source
