workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.2/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    formance-sdk-go:
        target: go
        source: my-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/my-source-code-samples
            blocking: false
