workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    stacks-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v3.1.0/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/stacks-source
targets:
    formance-sdk-go:
        target: go
        source: stacks-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/stacks-source-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
