// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ae0165d4c378

package gateway

type GetVersionsResponse struct {
	Env      string    `json:"env"`
	Region   string    `json:"region"`
	Versions []Version `json:"versions"`
}

func (g *GetVersionsResponse) GetEnv() string {
	if g == nil {
		return ""
	}
	return g.Env
}

func (g *GetVersionsResponse) GetRegion() string {
	if g == nil {
		return ""
	}
	return g.Region
}

func (g *GetVersionsResponse) GetVersions() []Version {
	if g == nil {
		return []Version{}
	}
	return g.Versions
}
