// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package ledger

type AccountResponse struct {
	AccountWithVolumesAndBalances AccountWithVolumesAndBalances `json:"data"`
}

func (a *AccountResponse) GetAccountWithVolumesAndBalances() AccountWithVolumesAndBalances {
	if a == nil {
		return AccountWithVolumesAndBalances{}
	}
	return a.AccountWithVolumesAndBalances
}
