// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package ledger

type ConfigInfo struct {
	Config               Config   `json:"config"`
	ExperimentalFeatures []string `json:"experimentalFeatures,omitempty"`
	Server               string   `json:"server"`
	Version              string   `json:"version"`
}

func (c *ConfigInfo) GetConfig() Config {
	if c == nil {
		return Config{}
	}
	return c.Config
}

func (c *ConfigInfo) GetExperimentalFeatures() []string {
	if c == nil {
		return nil
	}
	return c.ExperimentalFeatures
}

func (c *ConfigInfo) GetServer() string {
	if c == nil {
		return ""
	}
	return c.Server
}

func (c *ConfigInfo) GetVersion() string {
	if c == nil {
		return ""
	}
	return c.Version
}
