// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package ledger

type ConfigInfoResponse struct {
	ConfigInfo ConfigInfo `json:"data"`
}

func (c *ConfigInfoResponse) GetConfigInfo() ConfigInfo {
	if c == nil {
		return ConfigInfo{}
	}
	return c.ConfigInfo
}
