// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0e88f442f9f1

package ledger

type LedgerInfoResponse struct {
	LedgerInfo *LedgerInfo `json:"data,omitempty"`
}

func (l *LedgerInfoResponse) GetLedgerInfo() *LedgerInfo {
	if l == nil {
		return nil
	}
	return l.LedgerInfo
}
