// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2a8b98c5d344

package ledger

type MappingResponse struct {
	Mapping *Mapping `json:"data,omitempty"`
}

func (m *MappingResponse) GetMapping() *Mapping {
	if m == nil {
		return nil
	}
	return m.Mapping
}
