// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ae30faf67052

package ledger

type ScriptResponse struct {
	ErrorsEnum   *ErrorsEnum  `json:"errorCode,omitempty"`
	Transaction  *Transaction `json:"transaction,omitempty"`
	Details      *string      `json:"details,omitempty"`
	ErrorMessage *string      `json:"errorMessage,omitempty"`
}

func (s *ScriptResponse) GetErrorsEnum() *ErrorsEnum {
	if s == nil {
		return nil
	}
	return s.ErrorsEnum
}

func (s *ScriptResponse) GetTransaction() *Transaction {
	if s == nil {
		return nil
	}
	return s.Transaction
}

func (s *ScriptResponse) GetDetails() *string {
	if s == nil {
		return nil
	}
	return s.Details
}

func (s *ScriptResponse) GetErrorMessage() *string {
	if s == nil {
		return nil
	}
	return s.ErrorMessage
}
