// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7d972965f374

package ledger

type TransactionsResponse struct {
	Data []Transaction `json:"data"`
}

func (t *TransactionsResponse) GetData() []Transaction {
	if t == nil {
		return []Transaction{}
	}
	return t.Data
}
