// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d0f4b0ba06c0

package ledger

type V2AccountResponse struct {
	V2Account V2Account `json:"data"`
}

func (v *V2AccountResponse) GetV2Account() V2Account {
	if v == nil {
		return V2Account{}
	}
	return v.V2Account
}

// #region class-body-v2accountresponse
// #endregion class-body-v2accountresponse
