// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package ledger

import (
	"errors"
	"fmt"
	"github.com/formancehq/formance-sdk-go/v4/pkg/utils"
)

type V2BulkElementResultError struct {
	ErrorCode        string  `json:"errorCode"`
	ErrorDescription string  `json:"errorDescription"`
	ErrorDetails     *string `json:"errorDetails,omitempty"`
	LogID            int64   `json:"logID"`
	ResponseType     string  `json:"responseType"`
}

func (v V2BulkElementResultError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"errorCode", "errorDescription", "logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultError) GetErrorCode() string {
	if v == nil {
		return ""
	}
	return v.ErrorCode
}

func (v *V2BulkElementResultError) GetErrorDescription() string {
	if v == nil {
		return ""
	}
	return v.ErrorDescription
}

func (v *V2BulkElementResultError) GetErrorDetails() *string {
	if v == nil {
		return nil
	}
	return v.ErrorDetails
}

func (v *V2BulkElementResultError) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultError) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

// #region class-body-v2bulkelementresulterror
// #endregion class-body-v2bulkelementresulterror

type V2BulkElementResultDeleteMetadata struct {
	LogID        int64  `json:"logID"`
	ResponseType string `json:"responseType"`
}

func (v V2BulkElementResultDeleteMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultDeleteMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultDeleteMetadata) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultDeleteMetadata) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

// #region class-body-v2bulkelementresultdeletemetadata
// #endregion class-body-v2bulkelementresultdeletemetadata

type V2BulkElementResultRevertTransaction struct {
	Data         V2Transaction `json:"data"`
	LogID        int64         `json:"logID"`
	ResponseType string        `json:"responseType"`
}

func (v V2BulkElementResultRevertTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultRevertTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"data", "logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultRevertTransaction) GetData() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.Data
}

func (v *V2BulkElementResultRevertTransaction) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultRevertTransaction) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

// #region class-body-v2bulkelementresultreverttransaction
// #endregion class-body-v2bulkelementresultreverttransaction

type V2BulkElementResultAddMetadata struct {
	LogID        int64  `json:"logID"`
	ResponseType string `json:"responseType"`
}

func (v V2BulkElementResultAddMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultAddMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultAddMetadata) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultAddMetadata) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

// #region class-body-v2bulkelementresultaddmetadata
// #endregion class-body-v2bulkelementresultaddmetadata

type V2BulkElementResultCreateTransaction struct {
	Data         V2Transaction `json:"data"`
	LogID        int64         `json:"logID"`
	ResponseType string        `json:"responseType"`
}

func (v V2BulkElementResultCreateTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2BulkElementResultCreateTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"data", "logID", "responseType"}); err != nil {
		return err
	}
	return nil
}

func (v *V2BulkElementResultCreateTransaction) GetData() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.Data
}

func (v *V2BulkElementResultCreateTransaction) GetLogID() int64 {
	if v == nil {
		return 0
	}
	return v.LogID
}

func (v *V2BulkElementResultCreateTransaction) GetResponseType() string {
	if v == nil {
		return ""
	}
	return v.ResponseType
}

// #region class-body-v2bulkelementresultcreatetransaction
// #endregion class-body-v2bulkelementresultcreatetransaction

type V2BulkElementResultType string

const (
	V2BulkElementResultTypeV2BulkElementResultCreateTransaction V2BulkElementResultType = "V2BulkElementResultCreateTransaction"
	V2BulkElementResultTypeV2BulkElementResultAddMetadata       V2BulkElementResultType = "V2BulkElementResultAddMetadata"
	V2BulkElementResultTypeV2BulkElementResultRevertTransaction V2BulkElementResultType = "V2BulkElementResultRevertTransaction"
	V2BulkElementResultTypeV2BulkElementResultDeleteMetadata    V2BulkElementResultType = "V2BulkElementResultDeleteMetadata"
	V2BulkElementResultTypeV2BulkElementResultError             V2BulkElementResultType = "V2BulkElementResultError"
)

type V2BulkElementResult struct {
	V2BulkElementResultCreateTransaction *V2BulkElementResultCreateTransaction `queryParam:"inline" union:"member"`
	V2BulkElementResultAddMetadata       *V2BulkElementResultAddMetadata       `queryParam:"inline" union:"member"`
	V2BulkElementResultRevertTransaction *V2BulkElementResultRevertTransaction `queryParam:"inline" union:"member"`
	V2BulkElementResultDeleteMetadata    *V2BulkElementResultDeleteMetadata    `queryParam:"inline" union:"member"`
	V2BulkElementResultError             *V2BulkElementResultError             `queryParam:"inline" union:"member"`

	Type V2BulkElementResultType
}

func CreateV2BulkElementResultV2BulkElementResultCreateTransaction(v2BulkElementResultCreateTransaction V2BulkElementResultCreateTransaction) V2BulkElementResult {
	typ := V2BulkElementResultTypeV2BulkElementResultCreateTransaction

	return V2BulkElementResult{
		V2BulkElementResultCreateTransaction: &v2BulkElementResultCreateTransaction,
		Type:                                 typ,
	}
}

func CreateV2BulkElementResultV2BulkElementResultAddMetadata(v2BulkElementResultAddMetadata V2BulkElementResultAddMetadata) V2BulkElementResult {
	typ := V2BulkElementResultTypeV2BulkElementResultAddMetadata

	return V2BulkElementResult{
		V2BulkElementResultAddMetadata: &v2BulkElementResultAddMetadata,
		Type:                           typ,
	}
}

func CreateV2BulkElementResultV2BulkElementResultRevertTransaction(v2BulkElementResultRevertTransaction V2BulkElementResultRevertTransaction) V2BulkElementResult {
	typ := V2BulkElementResultTypeV2BulkElementResultRevertTransaction

	return V2BulkElementResult{
		V2BulkElementResultRevertTransaction: &v2BulkElementResultRevertTransaction,
		Type:                                 typ,
	}
}

func CreateV2BulkElementResultV2BulkElementResultDeleteMetadata(v2BulkElementResultDeleteMetadata V2BulkElementResultDeleteMetadata) V2BulkElementResult {
	typ := V2BulkElementResultTypeV2BulkElementResultDeleteMetadata

	return V2BulkElementResult{
		V2BulkElementResultDeleteMetadata: &v2BulkElementResultDeleteMetadata,
		Type:                              typ,
	}
}

func CreateV2BulkElementResultV2BulkElementResultError(v2BulkElementResultError V2BulkElementResultError) V2BulkElementResult {
	typ := V2BulkElementResultTypeV2BulkElementResultError

	return V2BulkElementResult{
		V2BulkElementResultError: &v2BulkElementResultError,
		Type:                     typ,
	}
}

func (u *V2BulkElementResult) UnmarshalJSON(data []byte) error {

	var v2BulkElementResultError V2BulkElementResultError = V2BulkElementResultError{}
	if err := utils.UnmarshalJSON(data, &v2BulkElementResultError, "", true, nil); err == nil {
		u.V2BulkElementResultError = &v2BulkElementResultError
		u.Type = V2BulkElementResultTypeV2BulkElementResultError
		return nil
	}

	var v2BulkElementResultCreateTransaction V2BulkElementResultCreateTransaction = V2BulkElementResultCreateTransaction{}
	if err := utils.UnmarshalJSON(data, &v2BulkElementResultCreateTransaction, "", true, nil); err == nil {
		u.V2BulkElementResultCreateTransaction = &v2BulkElementResultCreateTransaction
		u.Type = V2BulkElementResultTypeV2BulkElementResultCreateTransaction
		return nil
	}

	var v2BulkElementResultRevertTransaction V2BulkElementResultRevertTransaction = V2BulkElementResultRevertTransaction{}
	if err := utils.UnmarshalJSON(data, &v2BulkElementResultRevertTransaction, "", true, nil); err == nil {
		u.V2BulkElementResultRevertTransaction = &v2BulkElementResultRevertTransaction
		u.Type = V2BulkElementResultTypeV2BulkElementResultRevertTransaction
		return nil
	}

	var v2BulkElementResultAddMetadata V2BulkElementResultAddMetadata = V2BulkElementResultAddMetadata{}
	if err := utils.UnmarshalJSON(data, &v2BulkElementResultAddMetadata, "", true, nil); err == nil {
		u.V2BulkElementResultAddMetadata = &v2BulkElementResultAddMetadata
		u.Type = V2BulkElementResultTypeV2BulkElementResultAddMetadata
		return nil
	}

	var v2BulkElementResultDeleteMetadata V2BulkElementResultDeleteMetadata = V2BulkElementResultDeleteMetadata{}
	if err := utils.UnmarshalJSON(data, &v2BulkElementResultDeleteMetadata, "", true, nil); err == nil {
		u.V2BulkElementResultDeleteMetadata = &v2BulkElementResultDeleteMetadata
		u.Type = V2BulkElementResultTypeV2BulkElementResultDeleteMetadata
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2BulkElementResult", string(data))
}

func (u V2BulkElementResult) MarshalJSON() ([]byte, error) {
	if u.V2BulkElementResultCreateTransaction != nil {
		return utils.MarshalJSON(u.V2BulkElementResultCreateTransaction, "", true)
	}

	if u.V2BulkElementResultAddMetadata != nil {
		return utils.MarshalJSON(u.V2BulkElementResultAddMetadata, "", true)
	}

	if u.V2BulkElementResultRevertTransaction != nil {
		return utils.MarshalJSON(u.V2BulkElementResultRevertTransaction, "", true)
	}

	if u.V2BulkElementResultDeleteMetadata != nil {
		return utils.MarshalJSON(u.V2BulkElementResultDeleteMetadata, "", true)
	}

	if u.V2BulkElementResultError != nil {
		return utils.MarshalJSON(u.V2BulkElementResultError, "", true)
	}

	return nil, errors.New("could not marshal union type V2BulkElementResult: all fields are null")
}
