// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4d8e8736f52d

package ledger

type V2CreatePipelineRequest struct {
	ExporterID string `json:"exporterID"`
}

func (v *V2CreatePipelineRequest) GetExporterID() string {
	if v == nil {
		return ""
	}
	return v.ExporterID
}

// #region class-body-v2createpipelinerequest
// #endregion class-body-v2createpipelinerequest
