// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c4bea9328f91

package ledger

type V2ExporterConfiguration1 struct {
	Config map[string]any `json:"config"`
	Driver string         `json:"driver"`
}

func (v *V2ExporterConfiguration1) GetConfig() map[string]any {
	if v == nil {
		return map[string]any{}
	}
	return v.Config
}

func (v *V2ExporterConfiguration1) GetDriver() string {
	if v == nil {
		return ""
	}
	return v.Driver
}

// #region class-body-v2exporterconfiguration1
// #endregion class-body-v2exporterconfiguration1
