// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7fcf7479499f

package ledger

type V2GetTransactionResponse struct {
	V2Transaction V2Transaction `json:"data"`
}

func (v *V2GetTransactionResponse) GetV2Transaction() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.V2Transaction
}

// #region class-body-v2gettransactionresponse
// #endregion class-body-v2gettransactionresponse
