// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8b3e6c0ca9aa

package ledger

// V2GetPipelineStateV2GetPipelineStateResponse - Pipeline information
type V2GetPipelineStateV2GetPipelineStateResponse struct {
	V2PipelineConfiguration V2PipelineConfiguration `json:"data"`
}

func (v *V2GetPipelineStateV2GetPipelineStateResponse) GetV2PipelineConfiguration() V2PipelineConfiguration {
	if v == nil {
		return V2PipelineConfiguration{}
	}
	return v.V2PipelineConfiguration
}

// #region class-body-v2getpipelinestatev2getpipelinestateresponse
// #endregion class-body-v2getpipelinestatev2getpipelinestateresponse
