// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 642fd96c3083

package ledger

type V2ListExportersCursor struct {
	Data     []V2ExporterConfiguration `json:"data"`
	HasMore  bool                      `json:"hasMore"`
	Next     *string                   `json:"next,omitempty"`
	PageSize int64                     `json:"pageSize"`
	Previous *string                   `json:"previous,omitempty"`
}

func (v *V2ListExportersCursor) GetData() []V2ExporterConfiguration {
	if v == nil {
		return []V2ExporterConfiguration{}
	}
	return v.Data
}

func (v *V2ListExportersCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2ListExportersCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2ListExportersCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2ListExportersCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

// #region class-body-v2listexporterscursor
// #endregion class-body-v2listexporterscursor

type V2ExportersCursorResponse struct {
	V2ListExportersCursor V2ListExportersCursor     `json:"cursor"`
	Data                  []V2ExporterConfiguration `json:"data,omitempty"`
}

func (v *V2ExportersCursorResponse) GetV2ListExportersCursor() V2ListExportersCursor {
	if v == nil {
		return V2ListExportersCursor{}
	}
	return v.V2ListExportersCursor
}

func (v *V2ExportersCursorResponse) GetData() []V2ExporterConfiguration {
	if v == nil {
		return nil
	}
	return v.Data
}

// #region class-body-v2exporterscursorresponse
// #endregion class-body-v2exporterscursorresponse

// V2ListExportersV2ListExportersResponse - Exporters list
type V2ListExportersV2ListExportersResponse struct {
	V2ExportersCursorResponse *V2ExportersCursorResponse `json:"cursor,omitempty"`
}

func (v *V2ListExportersV2ListExportersResponse) GetV2ExportersCursorResponse() *V2ExportersCursorResponse {
	if v == nil {
		return nil
	}
	return v.V2ExportersCursorResponse
}

// #region class-body-v2listexportersv2listexportersresponse
// #endregion class-body-v2listexportersv2listexportersresponse
