// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 86a87233e4cf

package ledger

type V2ListPipelinesCursor struct {
	Data     []V2PipelineConfiguration `json:"data"`
	HasMore  bool                      `json:"hasMore"`
	Next     *string                   `json:"next,omitempty"`
	PageSize int64                     `json:"pageSize"`
	Previous *string                   `json:"previous,omitempty"`
}

func (v *V2ListPipelinesCursor) GetData() []V2PipelineConfiguration {
	if v == nil {
		return []V2PipelineConfiguration{}
	}
	return v.Data
}

func (v *V2ListPipelinesCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2ListPipelinesCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2ListPipelinesCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2ListPipelinesCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

// #region class-body-v2listpipelinescursor
// #endregion class-body-v2listpipelinescursor

type V2PipelinesCursorResponse struct {
	V2ListPipelinesCursor V2ListPipelinesCursor     `json:"cursor"`
	Data                  []V2PipelineConfiguration `json:"data,omitempty"`
}

func (v *V2PipelinesCursorResponse) GetV2ListPipelinesCursor() V2ListPipelinesCursor {
	if v == nil {
		return V2ListPipelinesCursor{}
	}
	return v.V2ListPipelinesCursor
}

func (v *V2PipelinesCursorResponse) GetData() []V2PipelineConfiguration {
	if v == nil {
		return nil
	}
	return v.Data
}

// #region class-body-v2pipelinescursorresponse
// #endregion class-body-v2pipelinescursorresponse

// V2ListPipelinesV2ListPipelinesResponse - Pipelines list
type V2ListPipelinesV2ListPipelinesResponse struct {
	V2PipelinesCursorResponse *V2PipelinesCursorResponse `json:"cursor,omitempty"`
}

func (v *V2ListPipelinesV2ListPipelinesResponse) GetV2PipelinesCursorResponse() *V2PipelinesCursorResponse {
	if v == nil {
		return nil
	}
	return v.V2PipelinesCursorResponse
}

// #region class-body-v2listpipelinesv2listpipelinesresponse
// #endregion class-body-v2listpipelinesv2listpipelinesresponse
