// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 956e16cae79e

package ledger

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
)

type V2QueryTemplateVar struct {
	Default any    `json:"default,omitempty"`
	Type    string `json:"type"`
}

func (v V2QueryTemplateVar) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2QueryTemplateVar) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (v *V2QueryTemplateVar) GetDefault() any {
	if v == nil {
		return nil
	}
	return v.Default
}

func (v *V2QueryTemplateVar) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

// #region class-body-v2querytemplatevar
// #endregion class-body-v2querytemplatevar
