// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package ledger

import (
	"errors"
	"fmt"
	"github.com/formancehq/formance-sdk-go/v4/pkg/utils"
	"time"
)

type QueryTemplateVolumeParams struct {
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor        *string `json:"cursor,omitempty"`
	Expand        *string `json:"expand,omitempty"`
	GroupBy       *int64  `json:"groupBy,omitempty"`
	InsertionDate *bool   `json:"insertionDate,omitempty"`
	// The maximum number of results to return per page.
	//
	PageSize *int64     `json:"pageSize,omitempty"`
	Pit      *time.Time `json:"pit,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	resource string `const:"volumes" json:"resource"`
	// Sort results using a field name and order (ascending or descending).
	// Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
	//
	Sort *string `json:"sort,omitempty"`
}

func (q QueryTemplateVolumeParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryTemplateVolumeParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"resource"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryTemplateVolumeParams) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *QueryTemplateVolumeParams) GetExpand() *string {
	if q == nil {
		return nil
	}
	return q.Expand
}

func (q *QueryTemplateVolumeParams) GetGroupBy() *int64 {
	if q == nil {
		return nil
	}
	return q.GroupBy
}

func (q *QueryTemplateVolumeParams) GetInsertionDate() *bool {
	if q == nil {
		return nil
	}
	return q.InsertionDate
}

func (q *QueryTemplateVolumeParams) GetPageSize() *int64 {
	if q == nil {
		return nil
	}
	return q.PageSize
}

func (q *QueryTemplateVolumeParams) GetPit() *time.Time {
	if q == nil {
		return nil
	}
	return q.Pit
}

func (q *QueryTemplateVolumeParams) GetResource() string {
	return "volumes"
}

func (q *QueryTemplateVolumeParams) GetSort() *string {
	if q == nil {
		return nil
	}
	return q.Sort
}

type QueryTemplateLogParams struct {
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `json:"cursor,omitempty"`
	Expand *string `json:"expand,omitempty"`
	// The maximum number of results to return per page.
	//
	PageSize *int64     `json:"pageSize,omitempty"`
	Pit      *time.Time `json:"pit,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	resource string `const:"logs" json:"resource"`
	// Sort results using a field name and order (ascending or descending).
	// Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
	//
	Sort *string `json:"sort,omitempty"`
}

func (q QueryTemplateLogParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryTemplateLogParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"resource"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryTemplateLogParams) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *QueryTemplateLogParams) GetExpand() *string {
	if q == nil {
		return nil
	}
	return q.Expand
}

func (q *QueryTemplateLogParams) GetPageSize() *int64 {
	if q == nil {
		return nil
	}
	return q.PageSize
}

func (q *QueryTemplateLogParams) GetPit() *time.Time {
	if q == nil {
		return nil
	}
	return q.Pit
}

func (q *QueryTemplateLogParams) GetResource() string {
	return "logs"
}

func (q *QueryTemplateLogParams) GetSort() *string {
	if q == nil {
		return nil
	}
	return q.Sort
}

type QueryTemplateTransactionParams struct {
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `json:"cursor,omitempty"`
	Expand *string `json:"expand,omitempty"`
	// The maximum number of results to return per page.
	//
	PageSize *int64     `json:"pageSize,omitempty"`
	Pit      *time.Time `json:"pit,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	resource string `const:"transactions" json:"resource"`
	// Sort results using a field name and order (ascending or descending).
	// Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
	//
	Sort *string `json:"sort,omitempty"`
}

func (q QueryTemplateTransactionParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryTemplateTransactionParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"resource"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryTemplateTransactionParams) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *QueryTemplateTransactionParams) GetExpand() *string {
	if q == nil {
		return nil
	}
	return q.Expand
}

func (q *QueryTemplateTransactionParams) GetPageSize() *int64 {
	if q == nil {
		return nil
	}
	return q.PageSize
}

func (q *QueryTemplateTransactionParams) GetPit() *time.Time {
	if q == nil {
		return nil
	}
	return q.Pit
}

func (q *QueryTemplateTransactionParams) GetResource() string {
	return "transactions"
}

func (q *QueryTemplateTransactionParams) GetSort() *string {
	if q == nil {
		return nil
	}
	return q.Sort
}

type QueryTemplateAccountParams struct {
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `json:"cursor,omitempty"`
	Expand *string `json:"expand,omitempty"`
	// The maximum number of results to return per page.
	//
	PageSize *int64     `json:"pageSize,omitempty"`
	Pit      *time.Time `json:"pit,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	resource string `const:"accounts" json:"resource"`
	// Sort results using a field name and order (ascending or descending).
	// Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
	//
	Sort *string `json:"sort,omitempty"`
}

func (q QueryTemplateAccountParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryTemplateAccountParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, []string{"resource"}); err != nil {
		return err
	}
	return nil
}

func (q *QueryTemplateAccountParams) GetCursor() *string {
	if q == nil {
		return nil
	}
	return q.Cursor
}

func (q *QueryTemplateAccountParams) GetExpand() *string {
	if q == nil {
		return nil
	}
	return q.Expand
}

func (q *QueryTemplateAccountParams) GetPageSize() *int64 {
	if q == nil {
		return nil
	}
	return q.PageSize
}

func (q *QueryTemplateAccountParams) GetPit() *time.Time {
	if q == nil {
		return nil
	}
	return q.Pit
}

func (q *QueryTemplateAccountParams) GetResource() string {
	return "accounts"
}

func (q *QueryTemplateAccountParams) GetSort() *string {
	if q == nil {
		return nil
	}
	return q.Sort
}

type V2QueryParamsType string

const (
	V2QueryParamsTypeQueryTemplateAccountParams     V2QueryParamsType = "QueryTemplateAccountParams"
	V2QueryParamsTypeQueryTemplateTransactionParams V2QueryParamsType = "QueryTemplateTransactionParams"
	V2QueryParamsTypeQueryTemplateLogParams         V2QueryParamsType = "QueryTemplateLogParams"
	V2QueryParamsTypeQueryTemplateVolumeParams      V2QueryParamsType = "QueryTemplateVolumeParams"
)

type V2QueryParams struct {
	QueryTemplateAccountParams     *QueryTemplateAccountParams     `queryParam:"inline" union:"member"`
	QueryTemplateTransactionParams *QueryTemplateTransactionParams `queryParam:"inline" union:"member"`
	QueryTemplateLogParams         *QueryTemplateLogParams         `queryParam:"inline" union:"member"`
	QueryTemplateVolumeParams      *QueryTemplateVolumeParams      `queryParam:"inline" union:"member"`

	Type V2QueryParamsType
}

func CreateV2QueryParamsQueryTemplateAccountParams(queryTemplateAccountParams QueryTemplateAccountParams) V2QueryParams {
	typ := V2QueryParamsTypeQueryTemplateAccountParams

	return V2QueryParams{
		QueryTemplateAccountParams: &queryTemplateAccountParams,
		Type:                       typ,
	}
}

func CreateV2QueryParamsQueryTemplateTransactionParams(queryTemplateTransactionParams QueryTemplateTransactionParams) V2QueryParams {
	typ := V2QueryParamsTypeQueryTemplateTransactionParams

	return V2QueryParams{
		QueryTemplateTransactionParams: &queryTemplateTransactionParams,
		Type:                           typ,
	}
}

func CreateV2QueryParamsQueryTemplateLogParams(queryTemplateLogParams QueryTemplateLogParams) V2QueryParams {
	typ := V2QueryParamsTypeQueryTemplateLogParams

	return V2QueryParams{
		QueryTemplateLogParams: &queryTemplateLogParams,
		Type:                   typ,
	}
}

func CreateV2QueryParamsQueryTemplateVolumeParams(queryTemplateVolumeParams QueryTemplateVolumeParams) V2QueryParams {
	typ := V2QueryParamsTypeQueryTemplateVolumeParams

	return V2QueryParams{
		QueryTemplateVolumeParams: &queryTemplateVolumeParams,
		Type:                      typ,
	}
}

func (u *V2QueryParams) UnmarshalJSON(data []byte) error {

	var queryTemplateAccountParams QueryTemplateAccountParams = QueryTemplateAccountParams{}
	if err := utils.UnmarshalJSON(data, &queryTemplateAccountParams, "", true, nil); err == nil {
		u.QueryTemplateAccountParams = &queryTemplateAccountParams
		u.Type = V2QueryParamsTypeQueryTemplateAccountParams
		return nil
	}

	var queryTemplateTransactionParams QueryTemplateTransactionParams = QueryTemplateTransactionParams{}
	if err := utils.UnmarshalJSON(data, &queryTemplateTransactionParams, "", true, nil); err == nil {
		u.QueryTemplateTransactionParams = &queryTemplateTransactionParams
		u.Type = V2QueryParamsTypeQueryTemplateTransactionParams
		return nil
	}

	var queryTemplateLogParams QueryTemplateLogParams = QueryTemplateLogParams{}
	if err := utils.UnmarshalJSON(data, &queryTemplateLogParams, "", true, nil); err == nil {
		u.QueryTemplateLogParams = &queryTemplateLogParams
		u.Type = V2QueryParamsTypeQueryTemplateLogParams
		return nil
	}

	var queryTemplateVolumeParams QueryTemplateVolumeParams = QueryTemplateVolumeParams{}
	if err := utils.UnmarshalJSON(data, &queryTemplateVolumeParams, "", true, nil); err == nil {
		u.QueryTemplateVolumeParams = &queryTemplateVolumeParams
		u.Type = V2QueryParamsTypeQueryTemplateVolumeParams
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2QueryParams", string(data))
}

func (u V2QueryParams) MarshalJSON() ([]byte, error) {
	if u.QueryTemplateAccountParams != nil {
		return utils.MarshalJSON(u.QueryTemplateAccountParams, "", true)
	}

	if u.QueryTemplateTransactionParams != nil {
		return utils.MarshalJSON(u.QueryTemplateTransactionParams, "", true)
	}

	if u.QueryTemplateLogParams != nil {
		return utils.MarshalJSON(u.QueryTemplateLogParams, "", true)
	}

	if u.QueryTemplateVolumeParams != nil {
		return utils.MarshalJSON(u.QueryTemplateVolumeParams, "", true)
	}

	return nil, errors.New("could not marshal union type V2QueryParams: all fields are null")
}
