// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cc7ff00f36fa

package ledger

type V2StatsResponse struct {
	V2Stats V2Stats `json:"data"`
}

func (v *V2StatsResponse) GetV2Stats() V2Stats {
	if v == nil {
		return V2Stats{}
	}
	return v.V2Stats
}

// #region class-body-v2statsresponse
// #endregion class-body-v2statsresponse
