// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 328b393505c5

package ledger

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type V2Transaction struct {
	V2AggregatedVolumes  map[string]map[string]V2Volume `json:"preCommitVolumes,omitempty"`
	V2AggregatedVolumes1 map[string]map[string]V2Volume `json:"postCommitVolumes,omitempty"`
	V2AggregatedVolumes2 map[string]map[string]V2Volume `json:"preCommitEffectiveVolumes,omitempty"`
	V2AggregatedVolumes3 map[string]map[string]V2Volume `json:"postCommitEffectiveVolumes,omitempty"`
	V2Metadata           map[string]string              `json:"metadata"`
	ID                   *big.Int                       `json:"id"`
	InsertedAt           *time.Time                     `json:"insertedAt,omitempty"`
	Postings             []V2Posting                    `json:"postings"`
	Reference            *string                        `json:"reference,omitempty"`
	Reverted             bool                           `json:"reverted"`
	RevertedAt           *time.Time                     `json:"revertedAt,omitempty"`
	Template             *string                        `json:"template,omitempty"`
	Timestamp            time.Time                      `json:"timestamp"`
	UpdatedAt            *time.Time                     `json:"updatedAt,omitempty"`
}

func (v V2Transaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2Transaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"metadata", "id", "postings", "reverted", "timestamp"}); err != nil {
		return err
	}
	return nil
}

func (v *V2Transaction) GetV2AggregatedVolumes() map[string]map[string]V2Volume {
	if v == nil {
		return nil
	}
	return v.V2AggregatedVolumes
}

func (v *V2Transaction) GetV2AggregatedVolumes1() map[string]map[string]V2Volume {
	if v == nil {
		return nil
	}
	return v.V2AggregatedVolumes1
}

func (v *V2Transaction) GetV2AggregatedVolumes2() map[string]map[string]V2Volume {
	if v == nil {
		return nil
	}
	return v.V2AggregatedVolumes2
}

func (v *V2Transaction) GetV2AggregatedVolumes3() map[string]map[string]V2Volume {
	if v == nil {
		return nil
	}
	return v.V2AggregatedVolumes3
}

func (v *V2Transaction) GetV2Metadata() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.V2Metadata
}

func (v *V2Transaction) GetID() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.ID
}

func (v *V2Transaction) GetInsertedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.InsertedAt
}

func (v *V2Transaction) GetPostings() []V2Posting {
	if v == nil {
		return []V2Posting{}
	}
	return v.Postings
}

func (v *V2Transaction) GetReference() *string {
	if v == nil {
		return nil
	}
	return v.Reference
}

func (v *V2Transaction) GetReverted() bool {
	if v == nil {
		return false
	}
	return v.Reverted
}

func (v *V2Transaction) GetRevertedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.RevertedAt
}

func (v *V2Transaction) GetTemplate() *string {
	if v == nil {
		return nil
	}
	return v.Template
}

func (v *V2Transaction) GetTimestamp() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.Timestamp
}

func (v *V2Transaction) GetUpdatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.UpdatedAt
}

// #region class-body-v2transaction
// #endregion class-body-v2transaction
