// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package reconciliation

type AlertsCursorResponseCursor struct {
	Data     []Alert `json:"data"`
	HasMore  bool    `json:"hasMore"`
	Next     *string `json:"next,omitempty"`
	PageSize int64   `json:"pageSize"`
	Previous *string `json:"previous,omitempty"`
}

func (a *AlertsCursorResponseCursor) GetData() []Alert {
	if a == nil {
		return []Alert{}
	}
	return a.Data
}

func (a *AlertsCursorResponseCursor) GetHasMore() bool {
	if a == nil {
		return false
	}
	return a.HasMore
}

func (a *AlertsCursorResponseCursor) GetNext() *string {
	if a == nil {
		return nil
	}
	return a.Next
}

func (a *AlertsCursorResponseCursor) GetPageSize() int64 {
	if a == nil {
		return 0
	}
	return a.PageSize
}

func (a *AlertsCursorResponseCursor) GetPrevious() *string {
	if a == nil {
		return nil
	}
	return a.Previous
}

// AlertsCursorResponse - OK
type AlertsCursorResponse struct {
	Cursor AlertsCursorResponseCursor `json:"cursor"`
}

func (a *AlertsCursorResponse) GetCursor() AlertsCursorResponseCursor {
	if a == nil {
		return AlertsCursorResponseCursor{}
	}
	return a.Cursor
}
