// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package reconciliation

type EvaluationsCursorResponseCursor struct {
	Data     []Evaluation `json:"data"`
	HasMore  bool         `json:"hasMore"`
	Next     *string      `json:"next,omitempty"`
	PageSize int64        `json:"pageSize"`
	Previous *string      `json:"previous,omitempty"`
}

func (e *EvaluationsCursorResponseCursor) GetData() []Evaluation {
	if e == nil {
		return []Evaluation{}
	}
	return e.Data
}

func (e *EvaluationsCursorResponseCursor) GetHasMore() bool {
	if e == nil {
		return false
	}
	return e.HasMore
}

func (e *EvaluationsCursorResponseCursor) GetNext() *string {
	if e == nil {
		return nil
	}
	return e.Next
}

func (e *EvaluationsCursorResponseCursor) GetPageSize() int64 {
	if e == nil {
		return 0
	}
	return e.PageSize
}

func (e *EvaluationsCursorResponseCursor) GetPrevious() *string {
	if e == nil {
		return nil
	}
	return e.Previous
}

// EvaluationsCursorResponse - OK
type EvaluationsCursorResponse struct {
	Cursor EvaluationsCursorResponseCursor `json:"cursor"`
}

func (e *EvaluationsCursorResponse) GetCursor() EvaluationsCursorResponseCursor {
	if e == nil {
		return EvaluationsCursorResponseCursor{}
	}
	return e.Cursor
}
