// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a9eefa3251de

package reconciliation

// ReconciliationResponse - OK
type ReconciliationResponse struct {
	Reconciliation Reconciliation `json:"data"`
}

func (r *ReconciliationResponse) GetReconciliation() Reconciliation {
	if r == nil {
		return Reconciliation{}
	}
	return r.Reconciliation
}
