// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

type DeliveryAttemptsResponseCursor struct {
	Data     []DeliveryAttempt `json:"data"`
	HasMore  bool              `json:"hasMore"`
	Next     *string           `json:"next,omitempty"`
	PageSize *int64            `json:"pageSize,omitempty"`
}

func (d *DeliveryAttemptsResponseCursor) GetData() []DeliveryAttempt {
	if d == nil {
		return []DeliveryAttempt{}
	}
	return d.Data
}

func (d *DeliveryAttemptsResponseCursor) GetHasMore() bool {
	if d == nil {
		return false
	}
	return d.HasMore
}

func (d *DeliveryAttemptsResponseCursor) GetNext() *string {
	if d == nil {
		return nil
	}
	return d.Next
}

func (d *DeliveryAttemptsResponseCursor) GetPageSize() *int64 {
	if d == nil {
		return nil
	}
	return d.PageSize
}

type DeliveryAttemptsResponse struct {
	Cursor DeliveryAttemptsResponseCursor `json:"cursor"`
}

func (d *DeliveryAttemptsResponse) GetCursor() DeliveryAttemptsResponseCursor {
	if d == nil {
		return DeliveryAttemptsResponseCursor{}
	}
	return d.Cursor
}
