// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"encoding/json"
	"fmt"
)

type DeliveryStatus string

const (
	DeliveryStatusPending    DeliveryStatus = "pending"
	DeliveryStatusDelivering DeliveryStatus = "delivering"
	DeliveryStatusSucceeded  DeliveryStatus = "succeeded"
	DeliveryStatusFailed     DeliveryStatus = "failed"
	DeliveryStatusCancelled  DeliveryStatus = "cancelled"
)

func (e DeliveryStatus) ToPointer() *DeliveryStatus {
	return &e
}
func (e *DeliveryStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "delivering":
		fallthrough
	case "succeeded":
		fallthrough
	case "failed":
		fallthrough
	case "cancelled":
		*e = DeliveryStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeliveryStatus: %v", v)
	}
}
