// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

type DeliveryResponse struct {
	Data Delivery `json:"data"`
}

func (d *DeliveryResponse) GetData() Delivery {
	if d == nil {
		return Delivery{}
	}
	return d.Data
}
