// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1d66ef8f4cbf

package webhooks

import (
	"encoding/json"
)

type ErrorResponse struct {
	ErrorsEnum   ErrorsEnum `json:"errorCode"`
	Details      *string    `json:"details,omitempty"`
	ErrorMessage string     `json:"errorMessage"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
